import {pool} from '../db/pool.js';
import {getCommercialSeller,sellerCompleteness,sellerSnapshot} from './commercial-seller.service.js';
import {getActiveCommercialDocumentTemplate} from './commercial-document-template.service.js';
import {renderCommercialTemplate} from './commercial-template-core.js';
import {buildCommercialDocumentSnapshots} from './commercial-document-snapshot-core.js';
import {formatDateBr,formatMoney} from './commercial-document-utils.js';
import {BRASILIA_NOW_SQL} from '../utils/db-time.js';

const parse=(v:any,f:any={})=>{try{return typeof v==='string'?JSON.parse(v):v??f;}catch{return f;}};
const address=(x:any)=>[x.street||x.billing_street,x.number||x.billing_number,x.complement||x.billing_complement,x.district||x.billing_district,x.city||x.billing_city,x.state||x.billing_state,(x.zip_code||x.billing_zip_code)&&`CEP ${x.zip_code||x.billing_zip_code}`].filter(Boolean).join(', ');
async function commonContext(entity:any,kind:'PROPOSAL'|'CONTRACT'){
  const seller=await getCommercialSeller();const complete=sellerCompleteness(seller);if(!complete.complete)throw Object.assign(new Error(`Cadastre os dados completos da Empresa Vendedora antes de gerar documentos. Campos: ${complete.missing.join(', ')}`),{status:409,code:'SELLER_PROFILE_INCOMPLETE',missing:complete.missing});
  let customer:any={};if(entity.commercial_customer_id){const [rows]=await pool.query<any[]>('SELECT * FROM commercial_customers WHERE id=? LIMIT 1',[entity.commercial_customer_id]);customer=rows[0]||{};}
  const customerSnapshot={legal_name:customer.legal_name||entity.company_name||'',trade_name:customer.trade_name||'',document:customer.document||entity.cnpj||'',email:customer.email||entity.email||'',phone:customer.phone||entity.phone||'',address:address(customer),financial_contact_name:customer.financial_contact_name||entity.responsible_name||'',financial_contact_email:customer.financial_contact_email||entity.email||''};
  const product={code:entity.product_code||'PONTO_CERTO',name:entity.product_name||'Ponto Certo',description:entity.product_description||''};
  const plan={code:entity.product_plan_code||entity.plan_code||'',name:entity.product_plan_name||entity.plan_name||entity.plan_name_snapshot||'Plano contratado'};
  const commercial=parse(entity.commercial_snapshot_json,{});const billing=parse(entity.billing_snapshot_json,{});
  const price=Number(entity.price_monthly||commercial.priceMonthly||0),discount=Number(commercial.discountPercent||0),effective=Math.round(price*(1-discount/100)*100)/100;
  const billingContext={provider:billing.provider||entity.default_provider||'conforme configuração financeira',method:billing.method||entity.default_payment_method||entity.payment_method||'Boleto/BolePix',fine_percent:billing.finePercent??'conforme contrato',interest_daily_percent:billing.interestDailyPercent??'conforme contrato',grace_days:billing.graceDays??entity.default_grace_days??3,auto_block:billing.autoBlock===false?'não':'sim'};
  const context:any={seller:sellerSnapshot(seller),customer:customerSnapshot,product,plan,subscription:{monthly_price:formatMoney(price),discount_percent:`${discount.toLocaleString('pt-BR')}%`,effective_price:formatMoney(effective),due_day:entity.due_day||commercial.dueDay||'a definir'},billing:billingContext};
  if(kind==='PROPOSAL')context.proposal={number:entity.proposal_number||'',created_at:formatDateBr(entity.created_at),valid_until:formatDateBr(entity.valid_until),implementation_days:entity.implementation_days??0,notes:entity.notes||'Sem observações adicionais.'};
  else context.contract={number:entity.contract_number||'',date:formatDateBr(entity.contract_date),start_date:formatDateBr(entity.start_date),term_months:entity.term_months?`${entity.term_months} meses`:'prazo indeterminado',due_day:entity.due_day||'a definir',payment_method:entity.payment_method||billingContext.method,adjustment_rule:entity.adjustment_rule||'Conforme condições comerciais acordadas entre as partes.',forum:entity.forum||'legalmente competente',notes:entity.notes||'Sem observações adicionais.'};
  const snapshots=buildCommercialDocumentSnapshots({seller:context.seller,customer:context.customer,product:context.product,plan:context.plan,pricing:{monthlyPrice:price,discountPercent:discount,effectivePrice:effective,implementationFee:Number(entity.implementation_fee||0)},billing:billingContext});
  return{context,snapshots};
}
export async function ensureProposalRendered(proposal:any,actorUserId?:number|null){if(proposal.rendered_content&&proposal.template_id)return proposal;if((proposal.product_code||'PONTO_CERTO')==='PONTO_CERTO')return proposal;const template=await getActiveCommercialDocumentTemplate(Number(proposal.product_id),'PROPOSAL');const {context,snapshots}=await commonContext(proposal,'PROPOSAL');const rendered=renderCommercialTemplate(template.template_content,context);await pool.query(`UPDATE commercial_proposals SET template_id=?,template_version=?,seller_snapshot_json=?,customer_snapshot_json=?,product_snapshot_json=?,plan_snapshot_json=?,pricing_snapshot_json=?,billing_snapshot_json=?,rendered_content=?,updated_by=COALESCE(?,updated_by),updated_at=${BRASILIA_NOW_SQL} WHERE id=?`,[template.id,template.version,JSON.stringify(snapshots.seller),JSON.stringify(snapshots.customer),JSON.stringify(snapshots.product),JSON.stringify(snapshots.plan),JSON.stringify(snapshots.pricing),JSON.stringify(snapshots.billing),rendered,actorUserId||null,proposal.id]);return{...proposal,template_id:template.id,template_version:template.version,rendered_content:rendered,...Object.fromEntries(Object.entries(snapshots).map(([k,v])=>[`${k}_snapshot_json`,JSON.stringify(v)]))};}
export async function ensureContractRendered(contract:any,actorUserId?:number|null){if(contract.rendered_content&&contract.template_id)return contract;if((contract.product_code||'PONTO_CERTO')==='PONTO_CERTO')return contract;const template=await getActiveCommercialDocumentTemplate(Number(contract.product_id),'CONTRACT');const {context,snapshots}=await commonContext(contract,'CONTRACT');const rendered=renderCommercialTemplate(template.template_content,context);await pool.query(`UPDATE commercial_contracts SET template_id=?,template_version=?,seller_snapshot_json=?,customer_snapshot_json=?,product_snapshot_json=?,plan_snapshot_json=?,pricing_snapshot_json=?,billing_snapshot_json=?,rendered_content=?,updated_by=COALESCE(?,updated_by),updated_at=${BRASILIA_NOW_SQL} WHERE id=?`,[template.id,template.version,JSON.stringify(snapshots.seller),JSON.stringify(snapshots.customer),JSON.stringify(snapshots.product),JSON.stringify(snapshots.plan),JSON.stringify(snapshots.pricing),JSON.stringify(snapshots.billing),rendered,actorUserId||null,contract.id]);return{...contract,template_id:template.id,template_version:template.version,rendered_content:rendered};}
