export type Company = {
  id: number;
  legal_name: string;
  trade_name?: string | null;
  cnpj?: string | null;
  active: number;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  zip_code?: string | null;
  street?: string | null;
  address_number?: string | null;
  complement?: string | null;
  district?: string | null;
  city?: string | null;
  state?: string | null;
  country?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  punch_radius_meters?: number | null;
  require_location?: number | null;
  block_outside_radius?: number | null;
  max_gps_accuracy_meters?: number | null;
  require_device_biometric?: number | null;
  require_registered_device?: number | null;
  max_registered_devices?: number | null;
  enforce_schedule_window?: number | null;
  schedule_early_margin_minutes?: number | null;
  schedule_late_margin_minutes?: number | null;
  mapbox_place_id?: string | null;
};
export type Employee = {
  id: number;
  company_id: number;
  company_name: string;
  name: string;
  cpf?: string | null;
  pis?: string | null;
  registration_number?: string | null;
  admission_date?: string | null;
  ctps?: string | null;
  position_name?: string | null;
  department_name?: string | null;
  work_schedule_id?: number | null;
  schedule_name?: string | null;
  biometric_exempt?: number | null;
  active: number;
  access_email?: string | null;
  location_names?: string | null;
  device_count?: number | null;
  last_device_seen_at?: string | null;
};
export type Schedule = {
  id: number;
  company_id: number;
  company_name: string;
  name: string;
  weekly_minutes: number;
  tolerance_late_minutes: number;
  tolerance_overtime_minutes: number;
  active: number;
  employee_count: number;
};
export type TimeEntry = {
  id: number;
  employee_id: number;
  employee_name: string;
  registration_number?: string | null;
  registered_at: string;
  entry_type: string;
  source: string;
  manually_adjusted: number;
  adjustment_reason?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  accuracy?: number | null;
  location_mocked?: number | null;
  device_biometric_verified?: number | null;
  device_biometric_type?: string | null;
  device_id?: string | null;
  device_decision?: string | null;
  device_model?: string | null;
  device_manufacturer?: string | null;
  geo_decision?: string | null;
  distance_meters?: number | null;
  within_radius?: number | null;
  geo_location_name?: string | null;
  schedule_decision?: string | null;
  scheduled_work_date?: string | null;
  schedule_text?: string | null;
  has_selfie?: number | null;
};
export type WorkLocation = {
  id: number;
  company_id: number;
  company_name: string;
  name: string;
  address?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  radius_meters?: number | null;
  geo_mode: "DISABLED" | "WARN" | "BLOCK";
  active: number;
  employee_count: number;
};
