import {pool} from '../db/pool.js';import {BRASILIA_NOW_SQL} from '../utils/db-time.js';import {assertAllowedPlaceholders,assertTemplateEditable} from './commercial-template-core.js';import {MOVYO_PROPOSAL_V1} from '../templates/movyo/proposal-v1.js';import {MOVYO_CONTRACT_V1} from '../templates/movyo/contract-v1.js';
export type CommercialDocumentType='PROPOSAL'|'CONTRACT';
export async function ensureDefaultCommercialTemplates(){
  const [products]=await pool.query<any[]>("SELECT id,code FROM commercial_products WHERE code IN ('PONTO_CERTO','MOVYO')");const ids=new Map(products.map(p=>[p.code,Number(p.id)]));
  const seeds=[
    {product:'PONTO_CERTO',type:'PROPOSAL',status:'ACTIVE',title:'Proposta Ponto Certo V1',content:'__LEGACY_DOCX__:proposta-ponto-certo.docx',meta:{renderer:'LEGACY_DOCX',filename:'proposta-ponto-certo.docx'}},
    {product:'PONTO_CERTO',type:'CONTRACT',status:'ACTIVE',title:'Contrato Ponto Certo V1',content:'__LEGACY_DOCX__:contrato-ponto-certo.docx',meta:{renderer:'LEGACY_DOCX',filename:'contrato-ponto-certo.docx'}},
    {product:'MOVYO',type:'PROPOSAL',status:'DRAFT',title:'Proposta Movyo V1',content:MOVYO_PROPOSAL_V1,meta:{renderer:'TEXT_DOCX',legalReviewRequired:true}},
    {product:'MOVYO',type:'CONTRACT',status:'DRAFT',title:'Contrato Movyo V1',content:MOVYO_CONTRACT_V1,meta:{renderer:'TEXT_DOCX',legalReviewRequired:true}},
  ];
  for(const seed of seeds){const productId=ids.get(seed.product);if(!productId)continue;const [exists]=await pool.query<any[]>('SELECT id FROM commercial_document_templates WHERE product_id=? AND document_type=? AND version=1 LIMIT 1',[productId,seed.type]);if(!exists[0])await pool.query(`INSERT INTO commercial_document_templates(product_id,document_type,version,status,title,template_content,template_metadata_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,${BRASILIA_NOW_SQL},${BRASILIA_NOW_SQL})`,[productId,seed.type,1,seed.status,seed.title,seed.content,JSON.stringify(seed.meta)]);}
}
export async function listCommercialDocumentTemplates(filters:{productId?:number;documentType?:string}={}){await ensureDefaultCommercialTemplates();const where=['1=1'],args:any[]=[];if(filters.productId){where.push('t.product_id=?');args.push(filters.productId);}if(filters.documentType){where.push('t.document_type=?');args.push(filters.documentType);}const [rows]=await pool.query<any[]>(`SELECT t.*,p.code AS product_code,p.name AS product_name FROM commercial_document_templates t JOIN commercial_products p ON p.id=t.product_id WHERE ${where.join(' AND ')} ORDER BY p.name,t.document_type,t.version DESC`,args);return rows;}
export async function getCommercialDocumentTemplate(id:number){const [rows]=await pool.query<any[]>('SELECT t.*,p.code AS product_code,p.name AS product_name FROM commercial_document_templates t JOIN commercial_products p ON p.id=t.product_id WHERE t.id=? LIMIT 1',[id]);if(!rows[0])throw Object.assign(new Error('Modelo de documento não encontrado.'),{status:404,code:'TEMPLATE_NOT_FOUND'});return rows[0];}
export async function getActiveCommercialDocumentTemplate(productId:number,documentType:CommercialDocumentType){await ensureDefaultCommercialTemplates();const [rows]=await pool.query<any[]>('SELECT * FROM commercial_document_templates WHERE product_id=? AND document_type=? AND status=\'ACTIVE\' ORDER BY version DESC LIMIT 1',[productId,documentType]);if(!rows[0])throw Object.assign(new Error('Este produto ainda não possui modelo ativo para este documento.'),{status:409,code:'TEMPLATE_NOT_CONFIGURED'});return rows[0];}
export async function createCommercialDocumentTemplate(input:{productId:number;documentType:CommercialDocumentType;title:string;templateContent:string;metadata?:unknown;actorUserId?:number|null}){if(!input.templateContent.startsWith('__LEGACY_DOCX__:'))assertAllowedPlaceholders(input.templateContent);const [v]=await pool.query<any[]>('SELECT COALESCE(MAX(version),0)+1 AS next_version FROM commercial_document_templates WHERE product_id=? AND document_type=?',[input.productId,input.documentType]);const version=Number(v[0]?.next_version||1);const [r]=await pool.query<any>(`INSERT INTO commercial_document_templates(product_id,document_type,version,status,title,template_content,template_metadata_json,created_by,updated_by,created_at,updated_at) VALUES(?,?,?,'DRAFT',?,?,?,?,?,${BRASILIA_NOW_SQL},${BRASILIA_NOW_SQL})`,[input.productId,input.documentType,version,input.title,input.templateContent,input.metadata==null?null:JSON.stringify(input.metadata),input.actorUserId||null,input.actorUserId||null]);return getCommercialDocumentTemplate(Number(r.insertId));}
export async function updateCommercialDocumentTemplate(id:number,input:{title?:string;templateContent?:string;metadata?:unknown;actorUserId?:number|null}){const current=await getCommercialDocumentTemplate(id);assertTemplateEditable(current.status);const content=input.templateContent??current.template_content;if(!content.startsWith('__LEGACY_DOCX__:'))assertAllowedPlaceholders(content);await pool.query(`UPDATE commercial_document_templates SET title=?,template_content=?,template_metadata_json=?,updated_by=?,updated_at=${BRASILIA_NOW_SQL} WHERE id=?`,[input.title??current.title,content,input.metadata===undefined?current.template_metadata_json:JSON.stringify(input.metadata),input.actorUserId||null,id]);return getCommercialDocumentTemplate(id);}
export async function activateCommercialDocumentTemplate(id:number,actorUserId?:number|null){const t=await getCommercialDocumentTemplate(id);const conn=await pool.getConnection();try{await conn.beginTransaction();await conn.query("UPDATE commercial_document_templates SET status='ARCHIVED',updated_at="+BRASILIA_NOW_SQL+" WHERE product_id=? AND document_type=? AND status='ACTIVE' AND id<>?",[t.product_id,t.document_type,id]);await conn.query(`UPDATE commercial_document_templates SET status='ACTIVE',updated_by=?,updated_at=${BRASILIA_NOW_SQL} WHERE id=?`,[actorUserId||null,id]);await conn.commit();}catch(e){await conn.rollback();throw e;}finally{conn.release();}return getCommercialDocumentTemplate(id);}
export async function archiveCommercialDocumentTemplate(id:number,actorUserId?:number|null){await pool.query(`UPDATE commercial_document_templates SET status='ARCHIVED',updated_by=?,updated_at=${BRASILIA_NOW_SQL} WHERE id=?`,[actorUserId||null,id]);return getCommercialDocumentTemplate(id);}
