import { randomUUID } from "node:crypto";
import { env } from "../config/env.js";
import { assertProviderIssueAmount, PROVIDER_CAPABILITIES } from "./payment-provider-core.js";
import type { PaymentMethodCode, PaymentProvider, ProviderChargeSnapshot, ProviderIssueInput, ProviderIssueResult } from "./payment-provider.types.js";
import { ProviderHttpError, centsFromMoney, cleanObject, digits, errorMessageFromResponse, fileExists, httpsRequest, moneyFromCents } from "./provider-http.js";

let tokenCache:{token:string;expiresAt:number}|null=null;
const base=()=>env.CORA_ENV==="sandbox"?"https://matls-clients.api.stage.cora.com.br":"https://matls-clients.api.cora.com.br";
const tls=()=>({certPath:env.CORA_CERT_PATH,keyPath:env.CORA_KEY_PATH});

function authConfig(){const missing:string[]=[];if(!env.CORA_CLIENT_ID)missing.push("CORA_CLIENT_ID");if(!fileExists(env.CORA_CERT_PATH))missing.push("CORA_CERT_PATH");if(!fileExists(env.CORA_KEY_PATH))missing.push("CORA_KEY_PATH");return missing;}
function config(){const missing=authConfig();if(!env.CORA_WEBHOOK_URL)missing.push("CORA_WEBHOOK_URL");return missing;}
async function token(force=false){if(!force&&tokenCache&&tokenCache.expiresAt>Date.now()+60000)return tokenCache.token;const missing=authConfig();if(missing.length)throw new ProviderHttpError("CORA",`Configuração Cora incompleta: ${missing.join(", ")}.`,409,"PROVIDER_NOT_CONFIGURED");const body=new URLSearchParams({grant_type:"client_credentials",client_id:env.CORA_CLIENT_ID!}).toString();let response;try{response=await httpsRequest(`${base()}/token`,{method:"POST",tls:tls(),headers:{"Content-Type":"application/x-www-form-urlencoded"},body});}catch(e:any){throw new ProviderHttpError("CORA",e?.message||"Falha TLS com a Cora.",502,"CORA_CONNECTION_ERROR");}if(response.status<200||response.status>=300||!response.json?.access_token)throw new ProviderHttpError("CORA",errorMessageFromResponse(response.json,response.text,"Falha ao autenticar na Cora."),response.status||502,"CORA_AUTH_ERROR",response.json);tokenCache={token:String(response.json.access_token),expiresAt:Date.now()+Number(response.json.expires_in||3600)*1000};return tokenCache.token;}
async function request(path:string,options:{method?:string;body?:any;idempotencyKey?:string;binary?:boolean}={}){const auth=await token();const headers:Record<string,string>={Authorization:`Bearer ${auth}`,Accept:options.binary?"application/pdf":"application/json"};let body:string|undefined;if(options.body!==undefined){headers["Content-Type"]="application/json";body=JSON.stringify(options.body);}if(options.idempotencyKey)headers["Idempotency-Key"]=options.idempotencyKey;let response;try{response=await httpsRequest(`${base()}${path}`,{method:options.method||"GET",tls:tls(),headers,body,binary:options.binary});}catch(e:any){throw new ProviderHttpError("CORA",e?.message||"Falha de comunicação com a Cora.",502,"CORA_CONNECTION_ERROR");}if(response.status===401){tokenCache=null;}if(response.status<200||response.status>=300)throw new ProviderHttpError("CORA",errorMessageFromResponse(response.json,response.text,"Falha na API Cora."),response.status||502,"CORA_API_ERROR",response.json);return response;}
function status(value:any){const s=String(value||"").toUpperCase();if(s==="PAID")return "PAID" as const;if(s==="CANCELED"||s==="CANCELLED")return "CANCELED" as const;if(s==="DRAFT"||s==="IN_PAYMENT")return "PROCESSING" as const;if(s==="OPEN"||s==="LATE"||s==="OVERDUE")return "OPEN" as const;return "PROCESSING" as const;}
function normalize(raw:any,method:PaymentMethodCode,externalReference:string|null):ProviderChargeSnapshot{const invoice=raw?.data||raw||{};const bank=invoice?.payment_options?.bank_slip||invoice?.paymentOptions?.bankSlip||{};const pix=invoice?.pix||{};const payments=Array.isArray(invoice?.payments)?invoice.payments:[];const paid=payments.find((p:any)=>String(p?.status||"").toUpperCase()==="PAID")||payments[payments.length-1];const confirmed=String(paid?.method||"").toUpperCase();const totalCents=invoice?.total_amount??invoice?.totalAmount;const receivedCents=paid?.total_paid??paid?.totalPaid;const terms=invoice?.payment_terms||invoice?.paymentTerms||{};const discount=terms?.discount||{};const discountType=String(discount?.type||"").toUpperCase();const discountAmount=discount?.amount??(discountType==="FIXED"?discount?.value:null);const discountPercent=discount?.percent??(discountType==="PERCENT"?discount?.value:null);return {provider:"CORA",requestedMethod:method,externalReference:invoice?.code?String(invoice.code):externalReference,providerChargeId:String(invoice?.id||invoice?.invoice_id||invoice?.invoiceId||""),status:status(invoice?.status),paymentUrl:bank?.url||invoice?.url||null,pdfUrl:bank?.url||null,barcode:bank?.barcode||null,digitableLine:bank?.digitable||bank?.digitable_line||null,pixCopyPaste:pix?.emv||null,pixQrCode:pix?.qr_code||pix?.qrCode||null,paidAt:paid?.finalized_at||paid?.finalizedAt||null,confirmedPaymentMethod:confirmed==="PIX"?"PIX":confirmed==="BANK_SLIP"?"BOLETO":paid?"OTHER":null,providerPaymentId:paid?.id?String(paid.id):null,nominalAmount:moneyFromCents(totalCents),receivedAmount:moneyFromCents(receivedCents),providerFee:null,netAmount:moneyFromCents(receivedCents),paidFine:moneyFromCents(paid?.fine),paidInterest:moneyFromCents(paid?.interest),configuredDiscountAmount:moneyFromCents(discountAmount),configuredDiscountPercent:discountPercent==null?null:Number(discountPercent),raw};}
function customer(input:ProviderIssueInput){const doc=digits(input.payer.document);const result:any={name:input.payer.name.slice(0,60),document:{identity:doc,type:doc.length===11?"CPF":"CNPJ"}};if(input.payer.email)result.email=input.payer.email.slice(0,60);if(input.payer.address&&input.payer.number&&input.payer.district&&input.payer.city&&input.payer.state&&input.payer.zipCode)result.address={street:input.payer.address,number:String(input.payer.number),district:input.payer.district,city:input.payer.city,state:String(input.payer.state).toUpperCase(),complement:input.payer.complement||"",zip_code:digits(input.payer.zipCode)};return result;}

export const coraProvider:PaymentProvider={
  code:"CORA",capabilities:()=>PROVIDER_CAPABILITIES.CORA,
  connectionStatus(){const missing=config();return{code:"CORA",configured:missing.length===0,enabledByEnvironment:env.CORA_ENABLED==="1",environment:env.CORA_ENV,missing,capabilities:this.capabilities(),webhookUrl:env.CORA_WEBHOOK_URL||null};},
  async testConnection(){await token(true);return{ok:true,provider:"CORA",environment:env.CORA_ENV,message:"Autenticação Cora realizada com sucesso."};},
  async issue(input:ProviderIssueInput):Promise<ProviderIssueResult>{assertProviderIssueAmount("CORA",input.paymentMethod,input.amount);const payment_forms=input.paymentMethod==="HYBRID"?["BANK_SLIP","PIX"]:input.paymentMethod==="PIX"?["PIX"]:["BANK_SLIP"];const terms:any={due_date:input.dueDate};const configured=input.paymentTerms||{};if(Number(configured.discountAmount||0)>=Number(input.amount)&&Number(configured.discountAmount||0)>0)throw new ProviderHttpError("CORA","O desconto antes do vencimento deve ser menor que o valor da cobrança.",422,"CORA_DISCOUNT_INVALID");if(Number(configured.discountAmount||0)>0)terms.discount={type:"FIXED",value:centsFromMoney(Number(configured.discountAmount))};if(Number(configured.fineAmount||0)>0)terms.fine={amount:centsFromMoney(Number(configured.fineAmount))};if(Number(configured.interestRate||0)>0)terms.interest={rate:Math.round(Number(configured.interestRate)*100)/100};const payload={code:input.externalReference,customer:customer(input),services:[{name:input.description.slice(0,60),description:input.description.slice(0,100),amount:centsFromMoney(input.amount)}],payment_terms:terms,payment_forms};const response=await request("/v2/invoices",{method:"POST",body:payload,idempotencyKey:input.idempotencyKey});const normalized=normalize(response.json,input.paymentMethod,input.externalReference);if(!normalized.providerChargeId)throw new ProviderHttpError("CORA","A Cora aceitou a solicitação sem retornar o ID da cobrança.",502,"CORA_ID_MISSING",response.json);return normalized;},
  async getCharge(providerChargeId,externalReference,requestedMethod){try{return normalize((await request(`/v2/invoices/${encodeURIComponent(providerChargeId)}`)).json,requestedMethod,externalReference);}catch(e:any){if(e instanceof ProviderHttpError&&e.status===404)return null;throw e;}},
  async findChargeByExternalReference(externalReference,requestedMethod,hint){const center=new Date(hint?.dueDate||hint?.createdAt||Date.now());const baseDate=Number.isNaN(center.getTime())?new Date():center;const iso=(d:Date)=>d.toISOString().slice(0,10);const start=new Date(baseDate);start.setUTCDate(start.getUTCDate()-31);const end=new Date(baseDate);end.setUTCDate(end.getUTCDate()+31);const params=new URLSearchParams({start:iso(start),end:iso(end),page:'1',perPage:'200'});const document=digits(hint?.payerDocument);if(document)params.set('search',document);const response=await request(`/v2/invoices/?${params.toString()}`);const raw=response.json?.data||response.json||{};const list=Array.isArray(raw)?raw:Array.isArray(raw?.items)?raw.items:Array.isArray(raw?.data)?raw.data:[];const item=list.find((x:any)=>String(x?.code||'')===externalReference);if(!item)return null;const invoiceId=item?.id||item?.invoice_id||item?.invoiceId;if(invoiceId){const full=await this.getCharge(String(invoiceId),externalReference,requestedMethod);if(full)return full;}return normalize(item,requestedMethod,externalReference);},
  async cancel(providerChargeId){await request(`/v2/invoices/${encodeURIComponent(providerChargeId)}`,{method:"DELETE"});},
  async getPdf(providerChargeId,requestedMethod){const snapshot=await this.getCharge(providerChargeId,"",requestedMethod);if(!snapshot?.pdfUrl)throw new ProviderHttpError("CORA","PDF não disponibilizado para esta cobrança.",404,"PDF_UNAVAILABLE");const response=await httpsRequest(snapshot.pdfUrl,{method:"GET"});if(response.status<200||response.status>=300)throw new ProviderHttpError("CORA","Não foi possível baixar o PDF da Cora.",response.status||502,"CORA_PDF_ERROR");return response.body;},
  async configureWebhook(url){if(!/^https:\/\//i.test(url))throw new ProviderHttpError("CORA","Webhook deve usar HTTPS.",400,"WEBHOOK_HTTPS_REQUIRED");return (await request("/endpoints",{method:"POST",idempotencyKey:randomUUID(),body:{url,resource:"invoice",trigger:"*"}})).json;},
};
