import { createHash } from "node:crypto";
import { env } from "../config/env.js";
import { PROVIDER_CAPABILITIES } from "./payment-provider-core.js";
import type { PaymentMethodCode, PaymentProvider, ProviderChargeSnapshot, ProviderIssueInput, ProviderIssueResult } from "./payment-provider.types.js";
import { ProviderHttpError, centsFromMoney, digits, errorMessageFromResponse, fileExists, httpsRequest, moneyFromCents } from "./provider-http.js";

let billingTokenCache:{token:string;expiresAt:number}|null=null;
let pixTokenCache:{token:string;expiresAt:number}|null=null;
const billingBase=()=>env.EFI_ENV==="sandbox"?"https://cobrancas-h.api.efipay.com.br":"https://cobrancas.api.efipay.com.br";
const pixBase=()=>env.EFI_ENV==="sandbox"?"https://pix-h.api.efipay.com.br":"https://pix.api.efipay.com.br";

function billingMissing(){const m:string[]=[];if(!env.EFI_CLIENT_ID)m.push("EFI_CLIENT_ID");if(!env.EFI_CLIENT_SECRET)m.push("EFI_CLIENT_SECRET");return m;}
function pixMissing(){const m=billingMissing();if(!env.EFI_PIX_CERT_PATH||!fileExists(env.EFI_PIX_CERT_PATH))m.push("EFI_PIX_CERT_PATH");if(!env.EFI_PIX_KEY)m.push("EFI_PIX_KEY");return m;}
function fullConfigMissing(){const m=pixMissing();if(!env.EFI_WEBHOOK_URL)m.push("EFI_WEBHOOK_URL");return Array.from(new Set(m));}
const pixTls=()=>({pfxPath:env.EFI_PIX_CERT_PATH,passphrase:env.EFI_PIX_CERT_PASSWORD});

async function billingToken(force=false){if(!force&&billingTokenCache&&billingTokenCache.expiresAt>Date.now()+60000)return billingTokenCache.token;const missing=billingMissing();if(missing.length)throw new ProviderHttpError("EFI",`Configuração Efí incompleta: ${missing.join(", ")}.`,409,"PROVIDER_NOT_CONFIGURED");const basic=Buffer.from(`${env.EFI_CLIENT_ID}:${env.EFI_CLIENT_SECRET}`).toString("base64");let response;try{response=await httpsRequest(`${billingBase()}/v1/authorize`,{method:"POST",headers:{Authorization:`Basic ${basic}`,"Content-Type":"application/json"},body:JSON.stringify({grant_type:"client_credentials"})});}catch(e:any){throw new ProviderHttpError("EFI",e?.message||"Falha de comunicação com a Efí.",502,"EFI_CONNECTION_ERROR");}if(response.status<200||response.status>=300||!response.json?.access_token)throw new ProviderHttpError("EFI",errorMessageFromResponse(response.json,response.text,"Falha ao autenticar na Efí."),response.status||502,"EFI_AUTH_ERROR",response.json);billingTokenCache={token:String(response.json.access_token),expiresAt:Date.now()+Number(response.json.expires_in||600)*1000};return billingTokenCache.token;}
async function billingRequest(path:string,options:{method?:string;body?:any;binary?:boolean}={}){const token=await billingToken();const headers:Record<string,string>={Authorization:`Bearer ${token}`,Accept:options.binary?"application/pdf":"application/json"};let body:string|undefined;if(options.body!==undefined){headers["Content-Type"]="application/json";body=JSON.stringify(options.body);}let response;try{response=await httpsRequest(`${billingBase()}${path}`,{method:options.method||"GET",headers,body,binary:options.binary});}catch(e:any){throw new ProviderHttpError("EFI",e?.message||"Falha de comunicação com a Efí.",502,"EFI_CONNECTION_ERROR");}if(response.status===401)billingTokenCache=null;if(response.status<200||response.status>=300)throw new ProviderHttpError("EFI",errorMessageFromResponse(response.json,response.text,"Falha na API Cobranças Efí."),response.status||502,"EFI_API_ERROR",response.json);return response;}

async function pixToken(force=false){if(!force&&pixTokenCache&&pixTokenCache.expiresAt>Date.now()+60000)return pixTokenCache.token;const missing=pixMissing();if(missing.length)throw new ProviderHttpError("EFI",`Configuração Pix Efí incompleta: ${missing.join(", ")}.`,409,"PROVIDER_NOT_CONFIGURED");const basic=Buffer.from(`${env.EFI_CLIENT_ID}:${env.EFI_CLIENT_SECRET}`).toString("base64");let response;try{response=await httpsRequest(`${pixBase()}/oauth/token`,{method:"POST",tls:pixTls(),headers:{Authorization:`Basic ${basic}`,"Content-Type":"application/json"},body:JSON.stringify({grant_type:"client_credentials"})});}catch(e:any){throw new ProviderHttpError("EFI",e?.message||"Falha mTLS com a API Pix Efí.",502,"EFI_PIX_CONNECTION_ERROR");}if(response.status<200||response.status>=300||!response.json?.access_token)throw new ProviderHttpError("EFI",errorMessageFromResponse(response.json,response.text,"Falha ao autenticar na API Pix Efí."),response.status||502,"EFI_PIX_AUTH_ERROR",response.json);pixTokenCache={token:String(response.json.access_token),expiresAt:Date.now()+Number(response.json.expires_in||3600)*1000};return pixTokenCache.token;}
async function pixRequest(path:string,options:{method?:string;body?:any}={}){const token=await pixToken();const headers:Record<string,string>={Authorization:`Bearer ${token}`,Accept:"application/json"};let body:string|undefined;if(options.body!==undefined){headers["Content-Type"]="application/json";body=JSON.stringify(options.body);}let response;try{response=await httpsRequest(`${pixBase()}${path}`,{method:options.method||"GET",tls:pixTls(),headers,body});}catch(e:any){throw new ProviderHttpError("EFI",e?.message||"Falha de comunicação com a API Pix Efí.",502,"EFI_PIX_CONNECTION_ERROR");}if(response.status===401)pixTokenCache=null;if(response.status<200||response.status>=300)throw new ProviderHttpError("EFI",errorMessageFromResponse(response.json,response.text,"Falha na API Pix Efí."),response.status||502,"EFI_PIX_API_ERROR",response.json);return response;}

function efiBillingStatus(value:any){const s=String(value||"").toLowerCase();if(s==="paid"||s==="settled")return "PAID" as const;if(["canceled","expired","refunded"].includes(s))return "CANCELED" as const;if(["waiting","unpaid","new"].includes(s))return "OPEN" as const;return "PROCESSING" as const;}
function efiPixStatus(value:any){const s=String(value||"").toUpperCase();if(s==="CONCLUIDA")return "PAID" as const;if(s.startsWith("REMOVIDA"))return "CANCELED" as const;if(s==="ATIVA")return "OPEN" as const;return "PROCESSING" as const;}
function billingSnapshot(raw:any,method:PaymentMethodCode,externalReference:string|null):ProviderChargeSnapshot{const data=raw?.data||raw||{};const payment=data?.payment?.banking_billet||data?.payment||{};const pix=data?.pix||payment?.pix||{};const total=data?.total;const chargeId=String(data?.charge_id||data?.chargeId||"");const paid=efiBillingStatus(data?.status)==="PAID";const confirmedRaw=String(data?.payment_method||data?.payment?.method||data?.payment?.type||data?.payment_type||"").toUpperCase();const confirmed=confirmedRaw.includes("PIX")?"PIX":confirmedRaw.includes("BILLET")||confirmedRaw.includes("BOLETO")||confirmedRaw.includes("BANK")?"BOLETO":paid?"OTHER":null;return {provider:"EFI",requestedMethod:method,externalReference:data?.custom_id?String(data.custom_id):externalReference,providerChargeId:chargeId?`BOLIX:${chargeId}`:"",status:efiBillingStatus(data?.status),paymentUrl:data?.link||data?.billet_link||payment?.link||null,pdfUrl:data?.pdf?.charge||payment?.pdf?.charge||null,barcode:data?.barcode||payment?.barcode||null,digitableLine:data?.barcode||payment?.barcode||null,pixCopyPaste:pix?.qrcode||null,pixQrCode:pix?.qrcode_image||null,paidAt:data?.paid_at||data?.payment_date||null,confirmedPaymentMethod:confirmed,providerPaymentId:paid?`EFI:${chargeId}`:null,nominalAmount:moneyFromCents(total),receivedAmount:paid?moneyFromCents(data?.amount_paid??total):null,providerFee:data?.fee==null?null:moneyFromCents(data.fee),netAmount:data?.net_value==null?null:moneyFromCents(data.net_value),raw};}
async function enrichPix(raw:any,method:PaymentMethodCode,externalReference:string|null):Promise<ProviderChargeSnapshot>{const data=raw?.data||raw||{};const txid=String(data?.txid||"");const pixList=Array.isArray(data?.pix)?data.pix:[];const payment=pixList[pixList.length-1];let qr:any=null;const locId=data?.loc?.id??data?.location?.id;if(locId!=null){try{qr=(await pixRequest(`/v2/loc/${encodeURIComponent(String(locId))}/qrcode`)).json;}catch{qr=null;}}const nominal=Number(data?.valor?.original);const received=payment?.valor!=null?Number(payment.valor):null;return {provider:"EFI",requestedMethod:method,externalReference:data?.solicitacaoPagador?externalReference:externalReference,providerChargeId:txid?`PIX:${txid}`:"",status:efiPixStatus(data?.status),paymentUrl:qr?.linkVisualizacao||null,pdfUrl:null,barcode:null,digitableLine:null,pixCopyPaste:qr?.qrcode||null,pixQrCode:qr?.imagemQrcode||null,paidAt:payment?.horario||null,confirmedPaymentMethod:payment?"PIX":null,providerPaymentId:payment?.endToEndId||payment?.txid||null,nominalAmount:Number.isFinite(nominal)?nominal:null,receivedAmount:Number.isFinite(received as number)?received:null,providerFee:null,netAmount:Number.isFinite(received as number)?received:null,raw:{charge:data,qrcode:qr}};}
function billingCustomer(input:ProviderIssueInput){const doc=digits(input.payer.document);const address=input.payer.address&&input.payer.number&&input.payer.district&&input.payer.city&&input.payer.state&&input.payer.zipCode?{street:input.payer.address,number:String(input.payer.number),neighborhood:input.payer.district,zipcode:digits(input.payer.zipCode),city:input.payer.city,complement:input.payer.complement||"",state:String(input.payer.state).toUpperCase()}:undefined;const common:any={email:input.payer.email||undefined,phone_number:digits(input.payer.phone)||undefined,address};if(doc.length===14)common.juridical_person={corporate_name:input.payer.name,cnpj:doc};else{common.name=input.payer.name;common.cpf=doc;}return common;}
function pixTxid(externalReference:string){return `PC${createHash("sha256").update(externalReference).digest("hex").slice(0,24)}`;}
function splitProviderId(value:string){const [kind,...rest]=String(value).split(":");return {kind,id:rest.join(":")};}

export const efiProvider:PaymentProvider={
  code:"EFI",capabilities:()=>PROVIDER_CAPABILITIES.EFI,
  connectionStatus(){const missing=fullConfigMissing();return{code:"EFI",configured:missing.length===0,enabledByEnvironment:env.EFI_ENABLED==="1",environment:env.EFI_ENV,missing,capabilities:this.capabilities(),webhookUrl:env.EFI_WEBHOOK_URL||null};},
  async testConnection(){await billingToken(true);return{ok:true,provider:"EFI",environment:env.EFI_ENV,message:"Autenticação da API Cobranças Efí realizada com sucesso."};},
  async issue(input:ProviderIssueInput):Promise<ProviderIssueResult>{if(input.paymentMethod==="PIX"){const txid=pixTxid(input.externalReference);const doc=digits(input.payer.document);const devedor:any={nome:input.payer.name};if(doc.length===14)devedor.cnpj=doc;else devedor.cpf=doc;const body:any={calendario:{dataDeVencimento:input.dueDate,validadeAposVencimento:30},devedor,valor:{original:input.amount.toFixed(2)},chave:env.EFI_PIX_KEY,solicitacaoPagador:input.description.slice(0,140)};const response=await pixRequest(`/v2/cobv/${txid}`,{method:"PUT",body});return enrichPix(response.json,"PIX",input.externalReference);}
    const body:any={items:[{name:input.description.slice(0,255),value:centsFromMoney(input.amount),amount:1}],metadata:{custom_id:input.externalReference,...(env.EFI_WEBHOOK_URL?{notification_url:env.EFI_WEBHOOK_URL}:{})},payment:{banking_billet:{customer:billingCustomer(input),expire_at:input.dueDate,message:input.paymentMethod==="HYBRID"?"Pague pelo código de barras ou pelo QR Code Pix":"Cobrança Ponto Certo"}}};const response=await billingRequest("/v1/charge/one-step",{method:"POST",body});const snap=billingSnapshot(response.json,input.paymentMethod,input.externalReference);if(!snap.providerChargeId)throw new ProviderHttpError("EFI","A Efí não retornou o ID da cobrança.",502,"EFI_ID_MISSING",response.json);return snap;},
  async getCharge(providerChargeId,externalReference,requestedMethod){const parsed=splitProviderId(providerChargeId);try{if(parsed.kind==="PIX")return enrichPix((await pixRequest(`/v2/cobv/${encodeURIComponent(parsed.id)}`)).json,requestedMethod,externalReference);if(parsed.kind==="BOLIX")return billingSnapshot((await billingRequest(`/v1/charge/${encodeURIComponent(parsed.id)}`)).json,requestedMethod,externalReference);throw new ProviderHttpError("EFI","Identificador Efí inválido.",400,"EFI_INVALID_PROVIDER_ID");}catch(e:any){if(e instanceof ProviderHttpError&&e.status===404)return null;throw e;}},
  async findChargeByExternalReference(externalReference,requestedMethod,hint){
    if(requestedMethod==="PIX"){const txid=pixTxid(externalReference);try{return await enrichPix((await pixRequest(`/v2/cobv/${encodeURIComponent(txid)}`)).json,requestedMethod,externalReference);}catch(e:any){if(e instanceof ProviderHttpError&&e.status===404)return null;throw e;}}
    const referenceDate=new Date(hint?.createdAt||hint?.dueDate||Date.now());const baseDate=Number.isNaN(referenceDate.getTime())?new Date():referenceDate;
    const iso=(d:Date)=>d.toISOString().slice(0,10);const begin=new Date(baseDate);begin.setUTCDate(begin.getUTCDate()-2);const end=new Date(baseDate);end.setUTCDate(end.getUTCDate()+7);
    const qs=new URLSearchParams({charge_type:'billet',begin_date:iso(begin),end_date:iso(end),date_of:'creation',custom_id:externalReference,limit:'100',page:'1'});
    const response=await billingRequest(`/v1/charges?${qs.toString()}`);const list=Array.isArray(response.json?.data)?response.json.data:[];const item=list.find((x:any)=>String(x?.custom_id||x?.metadata?.custom_id||'')===externalReference)||list[0];if(!item)return null;const chargeId=item?.charge_id||item?.id;if(chargeId){const full=await this.getCharge(`BOLIX:${chargeId}`,externalReference,requestedMethod);if(full)return full;}return billingSnapshot(item,requestedMethod,externalReference);
  },
  async cancel(providerChargeId){const parsed=splitProviderId(providerChargeId);if(parsed.kind==="BOLIX"){await billingRequest(`/v1/charge/${encodeURIComponent(parsed.id)}/cancel`,{method:"PUT",body:{}});return;}if(parsed.kind==="PIX"){await pixRequest(`/v2/cobv/${encodeURIComponent(parsed.id)}`,{method:"PATCH",body:[{op:"replace",path:"/status",value:"REMOVIDA_PELO_USUARIO_RECEBEDOR"}]});return;}throw new ProviderHttpError("EFI","Identificador Efí inválido.",400,"EFI_INVALID_PROVIDER_ID");},
  async getPdf(providerChargeId,requestedMethod){const parsed=splitProviderId(providerChargeId);if(parsed.kind!=="BOLIX")throw new ProviderHttpError("EFI","Cobrança Pix não possui PDF de boleto.",404,"PDF_UNAVAILABLE");const snapshot=await this.getCharge(providerChargeId,"",requestedMethod);if(!snapshot?.pdfUrl)throw new ProviderHttpError("EFI","PDF não disponibilizado pela Efí.",404,"PDF_UNAVAILABLE");const response=await httpsRequest(snapshot.pdfUrl,{method:"GET",binary:true});if(response.status<200||response.status>=300)throw new ProviderHttpError("EFI","Não foi possível baixar o PDF da Efí.",response.status||502,"EFI_PDF_ERROR");return response.body;},
  async configureWebhook(url){if(!/^https:\/\//i.test(url))throw new ProviderHttpError("EFI","Webhook deve usar HTTPS.",400,"WEBHOOK_HTTPS_REQUIRED");if(pixMissing().length===0){await pixRequest(`/v2/webhook/${encodeURIComponent(env.EFI_PIX_KEY!)}`,{method:"PUT",body:{webhookUrl:url}});}return{ok:true,provider:"EFI",billingNotificationUrl:"A URL é vinculada automaticamente a cada Bolix emitido.",pixWebhookConfigured:pixMissing().length===0,url};},
};

export async function resolveEfiNotificationToken(token:string){
  const response=await billingRequest(`/v1/notification/${encodeURIComponent(token)}`);
  const data=Array.isArray(response.json?.data)?response.json.data:[];
  const latest=data[data.length-1]||data[0]||null;
  const identifiers=latest?.identifiers||latest?.identifier||{};
  const chargeId=identifiers?.charge_id||identifiers?.chargeId||latest?.charge_id||latest?.chargeId||null;
  return {chargeId:chargeId==null?null:String(chargeId),raw:response.json};
}
