import { createHash, randomUUID } from "node:crypto";
import { pool } from "../db/pool.js";
import { BRASILIA_NOW_SQL } from "../utils/db-time.js";
import {
  calculateBlockAt,
  dueDateForCompetence,
  normalizedMoney,
  todayInBrasilia,
  validateDueDay,
  type ChargeStatus,
  type ChargeType,
} from "./financial-rules.js";
import { monthlyDescription, providerYourNumber } from "./financial-service-core.js";
import { assertProviderMethod, isPaymentMethodCode, isPaymentProviderCode, providerStatusToChargeStatus, validateProviderSnapshot } from "./payment-provider-core.js";
import { getDefaultPaymentSelection } from "./payment-provider-settings.service.js";
import { getPaymentProvider } from "./provider-registry.js";
import type { PaymentMethodCode, PaymentProviderCode, ProviderChargeSnapshot } from "./payment-provider.types.js";
import { ProviderHttpError } from "./provider-http.js";

const financeError=(message:string,status=400,code="FINANCE_ERROR")=>Object.assign(new Error(message),{status,code});
const json=(value:unknown)=>value==null?null:JSON.stringify(value);

export async function recordFinancialEvent(input:{tenantId:number;chargeId?:number|null;eventType:string;actorUserId?:number|null;details?:unknown},db:any=pool){
  await db.query(`INSERT INTO financial_events(tenant_id,charge_id,event_type,actor_user_id,details_json,created_at) VALUES(?,?,?,?,?,${BRASILIA_NOW_SQL})`,[input.tenantId,input.chargeId||null,input.eventType,input.actorUserId||null,json(input.details)]);
}

export async function ensureBillingProfile(tenantId:number,db:any=pool){
  await db.query(`INSERT IGNORE INTO saas_billing_profiles(tenant_id,due_day,grace_days,auto_block_enabled,auto_monthly_enabled,provider_expiration_days,created_at,updated_at) VALUES(?,10,3,1,1,30,${BRASILIA_NOW_SQL},${BRASILIA_NOW_SQL})`,[tenantId]);
  return getBillingProfile(tenantId,db);
}

export async function getBillingProfile(tenantId:number,db:any=pool){
  const [rows]=await db.query(`SELECT bp.tenant_id,bp.due_day,bp.grace_days,bp.auto_block_enabled,bp.auto_monthly_enabled,t.name AS tenant_name,t.status AS tenant_status,COALESCE(tc.price_monthly,p.price_monthly) AS price_monthly,s.status AS subscription_status FROM tenants t LEFT JOIN saas_billing_profiles bp ON bp.tenant_id=t.id LEFT JOIN subscriptions s ON s.id=(SELECT MAX(s2.id) FROM subscriptions s2 WHERE s2.tenant_id=t.id) LEFT JOIN plans p ON p.id=s.plan_id LEFT JOIN tenant_contracts tc ON tc.tenant_id=t.id WHERE t.id=? LIMIT 1`,[tenantId]);
  const row=rows[0];if(!row)throw financeError("Cliente não encontrado.",404,"TENANT_NOT_FOUND");
  if(!row.tenant_id){await db.query(`INSERT IGNORE INTO saas_billing_profiles(tenant_id,due_day,grace_days,auto_block_enabled,auto_monthly_enabled,provider_expiration_days,created_at,updated_at) VALUES(?,10,3,1,1,30,${BRASILIA_NOW_SQL},${BRASILIA_NOW_SQL})`,[tenantId]);return getBillingProfile(tenantId,db);}
  return{tenantId:Number(row.tenant_id),tenantName:row.tenant_name,tenantStatus:row.tenant_status,dueDay:Number(row.due_day),graceDays:Number(row.grace_days),autoBlockEnabled:Boolean(row.auto_block_enabled),autoMonthlyEnabled:Boolean(row.auto_monthly_enabled),priceMonthly:row.price_monthly==null?null:Number(row.price_monthly),subscriptionStatus:row.subscription_status||null};
}

export async function updateBillingProfile(tenantId:number,input:{dueDay:number;autoBlockEnabled:boolean;autoMonthlyEnabled:boolean},actorUserId:number){
  const dueDay=validateDueDay(input.dueDay);await ensureBillingProfile(tenantId);
  await pool.query(`UPDATE saas_billing_profiles SET due_day=?,grace_days=3,auto_block_enabled=?,auto_monthly_enabled=?,updated_at=${BRASILIA_NOW_SQL} WHERE tenant_id=?`,[dueDay,input.autoBlockEnabled?1:0,input.autoMonthlyEnabled?1:0,tenantId]);
  await recordFinancialEvent({tenantId,eventType:"BILLING_PROFILE_UPDATED",actorUserId,details:{...input,dueDay,graceDays:3}});return getBillingProfile(tenantId);
}

async function tenantMonthlyAmount(tenantId:number,db:any=pool){
  const [rows]=await db.query(`SELECT COALESCE(tc.price_monthly,p.price_monthly) AS amount,s.status AS subscription_status,t.status AS tenant_status FROM tenants t LEFT JOIN subscriptions s ON s.id=(SELECT MAX(s2.id) FROM subscriptions s2 WHERE s2.tenant_id=t.id) LEFT JOIN plans p ON p.id=s.plan_id LEFT JOIN tenant_contracts tc ON tc.tenant_id=t.id WHERE t.id=? LIMIT 1`,[tenantId]);
  const row=rows[0];if(!row)throw financeError("Cliente não encontrado.",404,"TENANT_NOT_FOUND");if(row.tenant_status==="CANCELED")throw financeError("Cliente cancelado não pode receber nova cobrança.",409,"TENANT_CANCELED");const amount=Number(row.amount||0);if(!(amount>0))throw financeError("O cliente não possui mensalidade contratada válida.",409,"MONTHLY_PRICE_MISSING");return normalizedMoney(amount);
}

export async function getImplementationSuggestion(tenantId:number){const [rows]=await pool.query<any[]>(`SELECT implementation_fee,contract_number,status FROM commercial_contracts WHERE tenant_id=? ORDER BY id DESC LIMIT 1`,[tenantId]);return rows[0]?{amount:Number(rows[0].implementation_fee||0),contractNumber:rows[0].contract_number,contractStatus:rows[0].status}:{amount:0,contractNumber:null,contractStatus:null};}

async function resolveSelection(override?:{provider?:PaymentProviderCode;method?:PaymentMethodCode}){
  if(override?.provider||override?.method){if(!override.provider||!override.method)throw financeError("Informe provedor e método juntos.",400,"PAYMENT_SELECTION_INCOMPLETE");if(!isPaymentProviderCode(override.provider)||!isPaymentMethodCode(override.method))throw financeError("Provedor ou método inválido.");assertProviderMethod(override.provider,override.method);const status=getPaymentProvider(override.provider).connectionStatus();if(!status.enabledByEnvironment||!status.configured)throw financeError("O provedor selecionado ainda não está pronto para emissão.",409,"PROVIDER_UNAVAILABLE");return{provider:override.provider,method:override.method};}
  return getDefaultPaymentSelection();
}

async function insertCharge(db:any,input:{tenantId:number;type:ChargeType;competence?:string|null;description:string;amount:number;dueDate:string;blockAt:string;actorUserId?:number|null;provider:PaymentProviderCode;paymentMethod:PaymentMethodCode}){
  const idempotencyKey=randomUUID();
  const [result]=await db.query(`INSERT INTO financial_charges(tenant_id,type,competence,description,amount,due_date,block_at,status,provider,requested_payment_method,idempotency_key,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'DRAFT',?,?,?,?,${BRASILIA_NOW_SQL},${BRASILIA_NOW_SQL})`,[input.tenantId,input.type,input.competence||null,input.description,normalizedMoney(input.amount),input.dueDate,input.blockAt,input.provider,input.paymentMethod,idempotencyKey,input.actorUserId||null]);
  const id=Number(result.insertId);const ref=providerYourNumber(id);await db.query(`UPDATE financial_charges SET provider_your_number=? WHERE id=?`,[ref,id]);return id;
}

export async function createMonthlyCharge(tenantId:number,competence:string,actorUserId?:number|null,options:{issue?:boolean}={}){
  if(!/^\d{4}-\d{2}$/.test(competence))throw financeError("Competência deve estar no formato AAAA-MM.");const profile=await ensureBillingProfile(tenantId),amount=await tenantMonthlyAmount(tenantId),dueDate=dueDateForCompetence(competence,profile.dueDay),blockAt=calculateBlockAt(dueDate,profile.graceDays);let id:number;let alreadyExists=false;
  try{const selection=await resolveSelection();id=await insertCharge(pool,{tenantId,type:"MONTHLY",competence,description:monthlyDescription(competence),amount,dueDate,blockAt,actorUserId,provider:selection.provider,paymentMethod:selection.method});await recordFinancialEvent({tenantId,chargeId:id,eventType:"CHARGE_CREATED",actorUserId,details:{type:"MONTHLY",competence,amount,dueDate,provider:selection.provider,paymentMethod:selection.method}});}catch(error:any){if(error?.code!=="ER_DUP_ENTRY")throw error;const [rows]=await pool.query<any[]>("SELECT id FROM financial_charges WHERE tenant_id=? AND type='MONTHLY' AND competence=? LIMIT 1",[tenantId,competence]);if(!rows[0])throw error;id=Number(rows[0].id);alreadyExists=true;}
  if(options.issue&&!alreadyExists)await issueCharge(id,actorUserId||null);return{...(await getCharge(id)),alreadyExists};
}

export async function createImplementationCharge(input:{tenantId:number;amount:number;dueDate:string;description?:string;actorUserId?:number|null;issue?:boolean}){
  const profile=await ensureBillingProfile(input.tenantId),amount=normalizedMoney(input.amount);if(!(amount>0))throw financeError("Informe um valor de implantação maior que zero.");const selection=await resolveSelection();const id=await insertCharge(pool,{tenantId:input.tenantId,type:"IMPLEMENTATION",description:input.description?.trim()||"Implantação Ponto Certo",amount,dueDate:input.dueDate,blockAt:calculateBlockAt(input.dueDate,profile.graceDays),actorUserId:input.actorUserId,provider:selection.provider,paymentMethod:selection.method});await recordFinancialEvent({tenantId:input.tenantId,chargeId:id,eventType:"CHARGE_CREATED",actorUserId:input.actorUserId,details:{type:"IMPLEMENTATION",amount,dueDate:input.dueDate,provider:selection.provider,paymentMethod:selection.method}});if(input.issue)await issueCharge(id,input.actorUserId||null);return getCharge(id);
}

export async function createAdHocCharge(input:{tenantId:number;amount:number;dueDate:string;description:string;provider?:PaymentProviderCode;paymentMethod?:PaymentMethodCode;actorUserId?:number|null;issue?:boolean}){
  const profile=await ensureBillingProfile(input.tenantId),amount=normalizedMoney(input.amount);if(!(amount>0))throw financeError("Informe um valor maior que zero.");if(!input.description?.trim())throw financeError("Informe a descrição da cobrança avulsa.");const selection=await resolveSelection(input.provider||input.paymentMethod?{provider:input.provider,method:input.paymentMethod}:undefined);const id=await insertCharge(pool,{tenantId:input.tenantId,type:"AD_HOC",description:input.description.trim(),amount,dueDate:input.dueDate,blockAt:calculateBlockAt(input.dueDate,profile.graceDays),actorUserId:input.actorUserId,provider:selection.provider,paymentMethod:selection.method});await recordFinancialEvent({tenantId:input.tenantId,chargeId:id,eventType:"CHARGE_CREATED",actorUserId:input.actorUserId,details:{type:"AD_HOC",amount,dueDate:input.dueDate,provider:selection.provider,paymentMethod:selection.method}});if(input.issue)await issueCharge(id,input.actorUserId||null);return getCharge(id);
}

async function payerForTenant(tenantId:number){const [rows]=await pool.query<any[]>(`SELECT c.legal_name,c.cnpj,p.email,p.phone,p.address,p.street,p.address_number,p.complement,p.district,p.city,p.state,p.zip_code FROM companies c LEFT JOIN company_profiles p ON p.company_id=c.id AND p.tenant_id=c.tenant_id WHERE c.tenant_id=? AND c.company_type='MATRIX' ORDER BY c.id LIMIT 1`,[tenantId]);const row=rows[0];if(!row)throw financeError("Empresa matriz do cliente não encontrada.",409,"PAYER_NOT_FOUND");return{document:row.cnpj||"",name:row.legal_name||"",address:row.street||row.address||"",number:row.address_number||null,complement:row.complement||null,district:row.district||null,city:row.city||"",state:row.state||"",zipCode:row.zip_code||"",email:row.email||null,phone:row.phone||null};}

export async function getCharge(id:number,db:any=pool){const [rows]=await db.query(`SELECT c.*,t.name AS tenant_name,bp.due_day,bp.grace_days,bp.auto_block_enabled,bp.auto_monthly_enabled FROM financial_charges c JOIN tenants t ON t.id=c.tenant_id LEFT JOIN saas_billing_profiles bp ON bp.tenant_id=c.tenant_id WHERE c.id=? LIMIT 1`,[id]);if(!rows[0])throw financeError("Cobrança não encontrada.",404,"CHARGE_NOT_FOUND");const row=rows[0];return{...row,id:Number(row.id),tenant_id:Number(row.tenant_id),amount:Number(row.amount),due_day:row.due_day==null?null:Number(row.due_day),grace_days:row.grace_days==null?3:Number(row.grace_days),auto_block_enabled:Boolean(row.auto_block_enabled),auto_monthly_enabled:Boolean(row.auto_monthly_enabled)};}

async function applyProviderDetails(chargeId:number,details:ProviderChargeSnapshot,actorUserId?:number|null){
  const conn=await pool.getConnection();try{await conn.beginTransaction();const [rows]=await conn.query<any[]>("SELECT * FROM financial_charges WHERE id=? FOR UPDATE",[chargeId]);const charge=rows[0];if(!charge)throw financeError("Cobrança não encontrada.",404,"CHARGE_NOT_FOUND");const externalReference=String(charge.provider_your_number||providerYourNumber(chargeId));const decision=validateProviderSnapshot({localAmount:Number(charge.amount),externalReference,snapshot:details});
    const common=[details.providerChargeId||null,details.paymentUrl||null,details.pdfUrl||null,details.barcode||null,details.digitableLine||null,details.pixCopyPaste||null,details.pixQrCode||null,json(details.raw)];
    if(decision.action==="HOLD"){await conn.query(`UPDATE financial_charges SET provider_charge_id=COALESCE(provider_charge_id,?),provider_payment_url=COALESCE(?,provider_payment_url),provider_pdf_url=COALESCE(?,provider_pdf_url),barcode=COALESCE(?,barcode),digitable_line=COALESCE(?,digitable_line),pix_copy_paste=COALESCE(?,pix_copy_paste),pix_qr_code=COALESCE(?,pix_qr_code),provider_payload_json=?,failure_message=?,updated_at=${BRASILIA_NOW_SQL} WHERE id=?`,[...common,decision.reason,chargeId]);await recordFinancialEvent({tenantId:Number(charge.tenant_id),chargeId,eventType:"RECONCILIATION_HELD",actorUserId,details:{provider:charge.provider,reason:decision.reason}},conn);await conn.commit();return{charge:await getCharge(chargeId),reconciled:false,reason:decision.reason};}
    if(decision.action==="PAY"){const paidAt=details.paidAt?new Date(details.paidAt):new Date(),paidDate=Number.isNaN(paidAt.getTime())?new Date():paidAt;const paymentId=details.providerPaymentId||details.providerChargeId||`${charge.provider}:${chargeId}`;const method=details.confirmedPaymentMethod||"OTHER";const origin=method==="PIX"?"PIX":method==="BOLETO"?"BOLETO":"OTHER";await conn.query(`INSERT IGNORE INTO financial_payments(charge_id,tenant_id,provider,requested_payment_method,payment_method,provider_payment_id,amount,provider_fee,net_amount,paid_at,origin,payload_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?, ?,${BRASILIA_NOW_SQL})`,[chargeId,charge.tenant_id,charge.provider,charge.requested_payment_method,method,paymentId,Number(details.receivedAmount??charge.amount),details.providerFee??null,details.netAmount??null,paidDate,origin,json(details.raw)]);await conn.query(`UPDATE financial_charges SET status='PAID',provider_charge_id=COALESCE(?,provider_charge_id),provider_payment_url=COALESCE(?,provider_payment_url),provider_pdf_url=COALESCE(?,provider_pdf_url),barcode=COALESCE(?,barcode),digitable_line=COALESCE(?,digitable_line),pix_copy_paste=COALESCE(?,pix_copy_paste),pix_qr_code=COALESCE(?,pix_qr_code),provider_payload_json=?,failure_message=NULL,paid_at=?,issued_at=COALESCE(issued_at,${BRASILIA_NOW_SQL}),updated_at=${BRASILIA_NOW_SQL} WHERE id=?`,[...common,paidDate,chargeId]);await recordFinancialEvent({tenantId:Number(charge.tenant_id),chargeId,eventType:"PAYMENT_CONFIRMED",actorUserId,details:{provider:charge.provider,paymentMethod:method,amount:details.receivedAmount??charge.amount,providerPaymentId:paymentId,providerFee:details.providerFee??null,netAmount:details.netAmount??null}},conn);
    }else{let next=providerStatusToChargeStatus(details.status);if(next==="OPEN"&&String(charge.due_date)<todayInBrasilia())next="OVERDUE";await conn.query(`UPDATE financial_charges SET status=?,provider_charge_id=COALESCE(?,provider_charge_id),provider_payment_url=COALESCE(?,provider_payment_url),provider_pdf_url=COALESCE(?,provider_pdf_url),barcode=COALESCE(?,barcode),digitable_line=COALESCE(?,digitable_line),pix_copy_paste=COALESCE(?,pix_copy_paste),pix_qr_code=COALESCE(?,pix_qr_code),provider_payload_json=?,failure_message=NULL,issued_at=COALESCE(issued_at,${BRASILIA_NOW_SQL}),canceled_at=IF(?='CANCELED',COALESCE(canceled_at,${BRASILIA_NOW_SQL}),canceled_at),updated_at=${BRASILIA_NOW_SQL} WHERE id=?`,[next,...common,next,chargeId]);await recordFinancialEvent({tenantId:Number(charge.tenant_id),chargeId,eventType:"CHARGE_RECONCILED",actorUserId,details:{provider:charge.provider,providerStatus:details.status,localStatus:next}},conn);}
    await conn.commit();return{charge:await getCharge(chargeId),reconciled:true,reason:null};
  }catch(error){await conn.rollback();throw error;}finally{conn.release();}
}

function providerForCharge(charge:any){if(!isPaymentProviderCode(charge.provider))throw financeError(`A cobrança usa o provedor histórico ${charge.provider||"desconhecido"}, que está disponível somente para consulta.`,409,"HISTORICAL_PROVIDER_READ_ONLY");if(!isPaymentMethodCode(charge.requested_payment_method))throw financeError("A cobrança não possui método de pagamento válido.",409,"PAYMENT_METHOD_MISSING");assertProviderMethod(charge.provider,charge.requested_payment_method);return{provider:getPaymentProvider(charge.provider),code:charge.provider as PaymentProviderCode,method:charge.requested_payment_method as PaymentMethodCode};}

export async function issueCharge(chargeId:number,actorUserId?:number|null){
  const charge=await getCharge(chargeId);if(["PAID","CANCELED"].includes(charge.status))throw financeError("Esta cobrança não pode ser emitida novamente.",409,"CHARGE_FINALIZED");if(charge.provider_charge_id)return reconcileCharge(chargeId,actorUserId);if(charge.status==="ISSUING")throw financeError("A emissão anterior ainda está sem confirmação. Reconcile a cobrança antes de uma nova tentativa.",409,"CHARGE_ISSUE_UNCERTAIN");const {provider,code,method}=providerForCharge(charge);const connection=provider.connectionStatus();if(!connection.enabledByEnvironment||!connection.configured)throw financeError("O provedor desta cobrança não está configurado no servidor.",409,"PROVIDER_UNAVAILABLE");const payer=await payerForTenant(charge.tenant_id);await pool.query(`UPDATE financial_charges SET status='ISSUING',failure_message=NULL,updated_at=${BRASILIA_NOW_SQL} WHERE id=?`,[chargeId]);await recordFinancialEvent({tenantId:charge.tenant_id,chargeId,eventType:"CHARGE_ISSUE_STARTED",actorUserId,details:{provider:code,paymentMethod:method,externalReference:charge.provider_your_number}});
  try{const issued=await provider.issue({externalReference:String(charge.provider_your_number),idempotencyKey:String(charge.idempotency_key||randomUUID()),amount:Number(charge.amount),dueDate:String(charge.due_date).slice(0,10),description:charge.description,payer,paymentMethod:method});await pool.query(`UPDATE financial_charges SET provider_charge_id=?,provider_payment_url=?,provider_pdf_url=?,barcode=?,digitable_line=?,pix_copy_paste=?,pix_qr_code=?,provider_payload_json=?,issued_at=${BRASILIA_NOW_SQL},updated_at=${BRASILIA_NOW_SQL} WHERE id=?`,[issued.providerChargeId,issued.paymentUrl||null,issued.pdfUrl||null,issued.barcode||null,issued.digitableLine||null,issued.pixCopyPaste||null,issued.pixQrCode||null,json(issued.raw),chargeId]);await recordFinancialEvent({tenantId:charge.tenant_id,chargeId,eventType:"CHARGE_ISSUED",actorUserId,details:{provider:code,paymentMethod:method,providerChargeId:issued.providerChargeId}});return applyProviderDetails(chargeId,issued,actorUserId);}
  catch(error:any){const deterministic=error instanceof ProviderHttpError&&error.status>=400&&error.status<500&&![408,409,429].includes(error.status);const nextStatus:ChargeStatus=deterministic?"FAILED":"ISSUING";const message=String(error?.message||`Falha ao emitir cobrança em ${code}.`).slice(0,500);await pool.query(`UPDATE financial_charges SET status=?,failure_message=?,updated_at=${BRASILIA_NOW_SQL} WHERE id=?`,[nextStatus,message,chargeId]);await recordFinancialEvent({tenantId:charge.tenant_id,chargeId,eventType:deterministic?"CHARGE_ISSUE_FAILED":"CHARGE_ISSUE_UNCERTAIN",actorUserId,details:{provider:code,paymentMethod:method,message,code:error?.code||null}});throw error;}
}

export async function reconcileCharge(chargeId:number,actorUserId?:number|null){const charge=await getCharge(chargeId);const {provider,method}=providerForCharge(charge);if(!charge.provider_charge_id){await recordFinancialEvent({tenantId:charge.tenant_id,chargeId,eventType:"RECONCILIATION_NOT_FOUND",actorUserId,details:{provider:charge.provider}});return{charge,reconciled:false,reason:"Cobrança ainda não possui identificador no provedor."};}const details=await provider.getCharge(charge.provider_charge_id,String(charge.provider_your_number||""),method);if(!details){await recordFinancialEvent({tenantId:charge.tenant_id,chargeId,eventType:"RECONCILIATION_NOT_FOUND",actorUserId,details:{provider:charge.provider}});return{charge,reconciled:false,reason:"Cobrança ainda não localizada no provedor."};}return applyProviderDetails(chargeId,details,actorUserId);}

export async function cancelCharge(chargeId:number,actorUserId?:number|null,reason="SOLICITACAO_ADMIN"){const charge=await getCharge(chargeId);if(charge.status==="PAID")throw financeError("Cobrança paga não pode ser cancelada.",409,"PAID_CHARGE");if(charge.status==="CANCELED")return charge;if(charge.provider_charge_id){const {provider,method}=providerForCharge(charge);await provider.cancel(charge.provider_charge_id,method);}await pool.query(`UPDATE financial_charges SET status='CANCELED',canceled_at=${BRASILIA_NOW_SQL},updated_at=${BRASILIA_NOW_SQL} WHERE id=?`,[chargeId]);await recordFinancialEvent({tenantId:charge.tenant_id,chargeId,eventType:"CHARGE_CANCELED",actorUserId,details:{provider:charge.provider,providerCancelRequested:Boolean(charge.provider_charge_id),reason}});return getCharge(chargeId);}

export async function recordManualPayment(chargeId:number,actorUserId:number,paidAt?:string){const charge=await getCharge(chargeId);if(charge.status==="PAID")return charge;if(charge.status==="CANCELED")throw financeError("Cobrança cancelada não pode receber baixa manual.",409,"CANCELED_CHARGE");const when=paidAt?new Date(paidAt):new Date();if(Number.isNaN(when.getTime()))throw financeError("Data de pagamento inválida.");const paymentId=`MANUAL:${chargeId}:${createHash("sha256").update(`${actorUserId}:${when.toISOString()}`).digest("hex").slice(0,24)}`;const conn=await pool.getConnection();try{await conn.beginTransaction();await conn.query(`INSERT INTO financial_payments(charge_id,tenant_id,provider,requested_payment_method,payment_method,provider_payment_id,amount,net_amount,paid_at,origin,payload_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,'MANUAL',?,${BRASILIA_NOW_SQL})`,[chargeId,charge.tenant_id,charge.provider,charge.requested_payment_method,"MANUAL",paymentId,charge.amount,charge.amount,when,json({actorUserId})]);await conn.query(`UPDATE financial_charges SET status='PAID',paid_at=?,failure_message=NULL,updated_at=${BRASILIA_NOW_SQL} WHERE id=?`,[when,chargeId]);await recordFinancialEvent({tenantId:charge.tenant_id,chargeId,eventType:"PAYMENT_CONFIRMED_MANUAL",actorUserId,details:{provider:charge.provider,amount:charge.amount,paidAt:when.toISOString()}},conn);await conn.commit();}catch(error){await conn.rollback();throw error;}finally{conn.release();}return getCharge(chargeId);}

export async function getChargePdf(chargeId:number){const charge=await getCharge(chargeId);if(!charge.provider_charge_id)throw financeError("Cobrança ainda não foi emitida.",409,"CHARGE_NOT_ISSUED");const {provider,method}=providerForCharge(charge);if(!provider.getPdf)throw financeError("Este provedor não disponibiliza PDF de boleto para esta cobrança.",404,"PDF_UNAVAILABLE");return provider.getPdf(charge.provider_charge_id,method);}

export async function listCharges(filters:{tenantId?:number;status?:string;type?:string;provider?:string;paymentMethod?:string;from?:string;to?:string;limit?:number}={}){const where:string[]=["1=1"],params:any[]=[];if(filters.tenantId){where.push("c.tenant_id=?");params.push(filters.tenantId);}if(filters.status){where.push("c.status=?");params.push(filters.status);}if(filters.type){where.push("c.type=?");params.push(filters.type);}if(filters.provider){where.push("c.provider=?");params.push(filters.provider);}if(filters.paymentMethod){where.push("c.requested_payment_method=?");params.push(filters.paymentMethod);}if(filters.from){where.push("c.due_date>=?");params.push(filters.from);}if(filters.to){where.push("c.due_date<=?");params.push(filters.to);}const limit=Math.min(500,Math.max(1,Number(filters.limit||200)));const [rows]=await pool.query<any[]>(`SELECT c.*,t.name AS tenant_name,EXISTS(SELECT 1 FROM financial_access_exceptions e WHERE e.tenant_id=c.tenant_id AND e.revoked_at IS NULL AND ${BRASILIA_NOW_SQL} BETWEEN e.starts_at AND e.ends_at AND (e.charge_id IS NULL OR e.charge_id=c.id)) AS has_active_exception FROM financial_charges c JOIN tenants t ON t.id=c.tenant_id WHERE ${where.join(" AND ")} ORDER BY c.due_date DESC,c.id DESC LIMIT ${limit}`,params);return rows.map((r:any)=>({...r,id:Number(r.id),tenant_id:Number(r.tenant_id),amount:Number(r.amount),has_active_exception:Boolean(r.has_active_exception)}));}

export async function listReceipts(filters:{tenantId?:number;provider?:string;paymentMethod?:string;from?:string;to?:string;limit?:number}={}){const where=["1=1"],params:any[]=[];if(filters.tenantId){where.push("p.tenant_id=?");params.push(filters.tenantId);}if(filters.provider){where.push("p.provider=?");params.push(filters.provider);}if(filters.paymentMethod){where.push("p.payment_method=?");params.push(filters.paymentMethod);}if(filters.from){where.push("DATE(p.paid_at)>=?");params.push(filters.from);}if(filters.to){where.push("DATE(p.paid_at)<=?");params.push(filters.to);}const limit=Math.min(500,Math.max(1,Number(filters.limit||200)));const [rows]=await pool.query<any[]>(`SELECT p.*,c.type,c.description,c.due_date,t.name AS tenant_name FROM financial_payments p JOIN financial_charges c ON c.id=p.charge_id JOIN tenants t ON t.id=p.tenant_id WHERE ${where.join(" AND ")} ORDER BY p.paid_at DESC,p.id DESC LIMIT ${limit}`,params);return rows.map((r:any)=>({...r,id:Number(r.id),charge_id:Number(r.charge_id),tenant_id:Number(r.tenant_id),amount:Number(r.amount),provider_fee:r.provider_fee==null?null:Number(r.provider_fee),net_amount:r.net_amount==null?null:Number(r.net_amount)}));}

export async function listFinancialEvents(filters:{tenantId?:number;chargeId?:number;provider?:string;limit?:number}={}){const where=["1=1"],params:any[]=[];if(filters.tenantId){where.push("e.tenant_id=?");params.push(filters.tenantId);}if(filters.chargeId){where.push("e.charge_id=?");params.push(filters.chargeId);}if(filters.provider){where.push("c.provider=?");params.push(filters.provider);}const limit=Math.min(500,Math.max(1,Number(filters.limit||200)));const [rows]=await pool.query<any[]>(`SELECT e.*,t.name AS tenant_name,c.description AS charge_description,c.provider,c.requested_payment_method,u.name AS actor_name FROM financial_events e JOIN tenants t ON t.id=e.tenant_id LEFT JOIN financial_charges c ON c.id=e.charge_id LEFT JOIN users u ON u.id=e.actor_user_id WHERE ${where.join(" AND ")} ORDER BY e.created_at DESC,e.id DESC LIMIT ${limit}`,params);return rows;}

export async function getFinancialDashboard(){const today=todayInBrasilia(),monthStart=`${today.slice(0,7)}-01`;const [paymentRows]=await pool.query<any[]>(`SELECT COALESCE(SUM(amount),0) AS received_month FROM financial_payments WHERE DATE(paid_at)>=? AND DATE(paid_at)<=?`,[monthStart,today]);const [chargeRows]=await pool.query<any[]>(`SELECT COALESCE(SUM(CASE WHEN fc.status IN ('OPEN','OVERDUE','ISSUING') THEN fc.amount ELSE 0 END),0) AS receivable,COALESCE(SUM(CASE WHEN fc.status='OVERDUE' THEN fc.amount ELSE 0 END),0) AS overdue,COUNT(DISTINCT CASE WHEN fc.status='OVERDUE' THEN fc.tenant_id END) AS delinquent,COUNT(DISTINCT CASE WHEN bp.auto_block_enabled=1 AND fc.status IN ('OPEN','OVERDUE') AND fc.block_at<=? AND NOT EXISTS(SELECT 1 FROM financial_access_exceptions e WHERE e.tenant_id=fc.tenant_id AND e.revoked_at IS NULL AND ${BRASILIA_NOW_SQL} BETWEEN e.starts_at AND e.ends_at AND (e.charge_id IS NULL OR e.charge_id=fc.id)) THEN fc.tenant_id END) AS blocked FROM financial_charges fc LEFT JOIN saas_billing_profiles bp ON bp.tenant_id=fc.tenant_id`,[today]);const [mrrRows]=await pool.query<any[]>(`SELECT COALESCE(SUM(COALESCE(tc.price_monthly,p.price_monthly)),0) AS mrr FROM tenants t JOIN subscriptions s ON s.id=(SELECT MAX(s2.id) FROM subscriptions s2 WHERE s2.tenant_id=t.id) JOIN plans p ON p.id=s.plan_id LEFT JOIN tenant_contracts tc ON tc.tenant_id=t.id WHERE t.status='ACTIVE' AND s.status IN ('ACTIVE','PAST_DUE')`);const [providerRows]=await pool.query<any[]>(`SELECT provider,COALESCE(SUM(amount),0) AS received,COALESCE(SUM(provider_fee),0) AS fees,COALESCE(SUM(net_amount),0) AS net FROM financial_payments WHERE DATE(paid_at)>=? AND DATE(paid_at)<=? GROUP BY provider ORDER BY received DESC`,[monthStart,today]);return{receivedMonth:Number(paymentRows[0]?.received_month||0),receivable:Number(chargeRows[0]?.receivable||0),overdue:Number(chargeRows[0]?.overdue||0),delinquentTenants:Number(chargeRows[0]?.delinquent||0),blockedTenants:Number(chargeRows[0]?.blocked||0),mrr:Number(mrrRows[0]?.mrr||0),byProvider:providerRows.map((r:any)=>({provider:r.provider,received:Number(r.received||0),fees:Number(r.fees||0),net:Number(r.net||0)})),recentReceipts:await listReceipts({limit:8})};}

export async function markOverdueCharges(){const today=todayInBrasilia();const [result]=await pool.query<any>(`UPDATE financial_charges SET status='OVERDUE',updated_at=${BRASILIA_NOW_SQL} WHERE status='OPEN' AND due_date<?`,[today]);return Number(result.affectedRows||0);}
export async function listAmbiguousCharges(limit=50){const [rows]=await pool.query<any[]>(`SELECT id FROM financial_charges WHERE status='ISSUING' AND provider_charge_id IS NOT NULL AND provider IN ('CORA','EFI','MERCADO_PAGO') ORDER BY updated_at ASC LIMIT ${Math.min(200,Math.max(1,limit))}`);return rows.map((r:any)=>Number(r.id));}
