import { env } from "../config/env.js";
import { PROVIDER_CAPABILITIES } from "./payment-provider-core.js";
import type { PaymentProvider, ProviderChargeSnapshot, ProviderIssueInput, ProviderIssueResult } from "./payment-provider.types.js";
import { ProviderHttpError, digits, errorMessageFromResponse, httpsRequest } from "./provider-http.js";

const base="https://api.mercadopago.com";
function authMissing(){const result:string[]=[];if(!env.MP_ACCESS_TOKEN)result.push("MP_ACCESS_TOKEN");return result;}
function missing(){const result=authMissing();if(!env.MP_WEBHOOK_SECRET)result.push("MP_WEBHOOK_SECRET");if(!env.MP_WEBHOOK_URL)result.push("MP_WEBHOOK_URL");return result;}
async function request(path:string,options:{method?:string;body?:any;idempotencyKey?:string}={}){const m=authMissing();if(m.length)throw new ProviderHttpError("MERCADO_PAGO",`Configuração Mercado Pago incompleta: ${m.join(", ")}.`,409,"PROVIDER_NOT_CONFIGURED");const headers:Record<string,string>={Authorization:`Bearer ${env.MP_ACCESS_TOKEN}`,Accept:"application/json"};let body:string|undefined;if(options.body!==undefined){headers["Content-Type"]="application/json";body=JSON.stringify(options.body);}if(options.idempotencyKey)headers["X-Idempotency-Key"]=options.idempotencyKey;let response;try{response=await httpsRequest(`${base}${path}`,{method:options.method||"GET",headers,body});}catch(e:any){throw new ProviderHttpError("MERCADO_PAGO",e?.message||"Falha de comunicação com o Mercado Pago.",502,"MP_CONNECTION_ERROR");}if(response.status<200||response.status>=300)throw new ProviderHttpError("MERCADO_PAGO",errorMessageFromResponse(response.json,response.text,"Falha na API Mercado Pago."),response.status||502,"MP_API_ERROR",response.json);return response;}
function status(value:any){const s=String(value||"").toLowerCase();if(s==="approved")return "PAID" as const;if(["cancelled","canceled","refunded","charged_back"].includes(s))return "CANCELED" as const;if(["rejected"].includes(s))return "FAILED" as const;if(["pending","in_process","authorized"].includes(s))return "OPEN" as const;return "PROCESSING" as const;}
function splitName(name:string){const parts=String(name||"").trim().split(/\s+/).filter(Boolean);return {first_name:parts[0]||"Cliente",last_name:parts.slice(1).join(" ")||"Ponto Certo"};}
function normalize(raw:any,method:"PIX"|"BOLETO",externalReference:string|null):ProviderChargeSnapshot{const data=raw?.response||raw?.data||raw||{};const td=data?.transaction_details||{};const poi=data?.point_of_interaction?.transaction_data||{};const fees=Array.isArray(data?.fee_details)?data.fee_details:[];const fee=fees.reduce((sum:number,x:any)=>sum+Number(x?.amount||0),0);const paid=status(data?.status)==="PAID";const confirmed=data?.payment_method_id==="pix"?"PIX":data?.payment_type_id==="ticket"||String(data?.payment_method_id||"").includes("bol")?"BOLETO":paid?"OTHER":null;const amount=Number(data?.transaction_amount);const net=td?.net_received_amount==null?null:Number(td.net_received_amount);return{provider:"MERCADO_PAGO",requestedMethod:method,externalReference:data?.external_reference?String(data.external_reference):externalReference,providerChargeId:data?.id?`PAYMENT:${data.id}`:"",status:status(data?.status),paymentUrl:poi?.ticket_url||td?.external_resource_url||null,pdfUrl:null,barcode:td?.barcode?.content||td?.barcode_content||null,digitableLine:td?.barcode?.content||td?.barcode_content||null,pixCopyPaste:poi?.qr_code||null,pixQrCode:poi?.qr_code_base64||null,paidAt:data?.date_approved||null,confirmedPaymentMethod:confirmed,providerPaymentId:data?.id?String(data.id):null,nominalAmount:Number.isFinite(amount)?amount:null,receivedAmount:paid&&Number.isFinite(amount)?amount:null,providerFee:fee||null,netAmount:Number.isFinite(net as number)?net:null,raw};}
function id(providerChargeId:string){const parts=String(providerChargeId).split(":");return parts.length>1?parts.slice(1).join(":"):providerChargeId;}
function expirationFor(dueDate:string){return `${dueDate}T23:59:59.000-03:00`;}

export const mercadoPagoProvider:PaymentProvider={
  code:"MERCADO_PAGO",capabilities:()=>PROVIDER_CAPABILITIES.MERCADO_PAGO,
  connectionStatus(){const m=missing();return{code:"MERCADO_PAGO",configured:m.length===0,enabledByEnvironment:env.MP_ENABLED==="1",environment:env.MP_ENV,missing:m,capabilities:this.capabilities(),webhookUrl:env.MP_WEBHOOK_URL||null};},
  async testConnection(){await request("/users/me");return{ok:true,provider:"MERCADO_PAGO",environment:env.MP_ENV,message:"Credencial Mercado Pago validada com sucesso."};},
  async issue(input:ProviderIssueInput):Promise<ProviderIssueResult>{if(input.paymentMethod==="HYBRID")throw new ProviderHttpError("MERCADO_PAGO","Mercado Pago não oferece Boleto + Pix como cobrança híbrida única.",409,"PAYMENT_METHOD_UNSUPPORTED");const doc=digits(input.payer.document);const names=splitName(input.payer.name);const payer:any={email:input.payer.email||undefined,first_name:names.first_name,last_name:names.last_name,identification:{type:doc.length===14?"CNPJ":"CPF",number:doc}};if(input.paymentMethod==="BOLETO"){if(!(input.payer.address&&input.payer.number&&input.payer.district&&input.payer.city&&input.payer.state&&input.payer.zipCode))throw new ProviderHttpError("MERCADO_PAGO","Endereço completo do pagador é obrigatório para boleto Mercado Pago.",409,"PAYER_ADDRESS_REQUIRED");payer.address={zip_code:digits(input.payer.zipCode),street_name:input.payer.address,street_number:String(input.payer.number),neighborhood:input.payer.district,city:input.payer.city,federal_unit:String(input.payer.state).toUpperCase()};}
    const body:any={transaction_amount:Number(input.amount),description:input.description,external_reference:input.externalReference,payment_method_id:input.paymentMethod==="PIX"?"pix":env.MP_BOLETO_PAYMENT_METHOD_ID,payer,date_of_expiration:expirationFor(input.dueDate)};if(env.MP_WEBHOOK_URL)body.notification_url=env.MP_WEBHOOK_URL;const response=await request("/v1/payments",{method:"POST",body,idempotencyKey:input.idempotencyKey});const result=normalize(response.json,input.paymentMethod,input.externalReference);if(!result.providerChargeId)throw new ProviderHttpError("MERCADO_PAGO","Mercado Pago não retornou o ID do pagamento.",502,"MP_ID_MISSING",response.json);return result;},
  async getCharge(providerChargeId,externalReference,requestedMethod){if(requestedMethod==="HYBRID")throw new ProviderHttpError("MERCADO_PAGO","Método híbrido não é suportado pelo Mercado Pago.",409,"PAYMENT_METHOD_UNSUPPORTED");try{return normalize((await request(`/v1/payments/${encodeURIComponent(id(providerChargeId))}`)).json,requestedMethod,externalReference);}catch(e:any){if(e instanceof ProviderHttpError&&e.status===404)return null;throw e;}},
  async cancel(providerChargeId){await request(`/v1/payments/${encodeURIComponent(id(providerChargeId))}`,{method:"PUT",body:{status:"cancelled"}});},
  async configureWebhook(url){if(!/^https:\/\//i.test(url))throw new ProviderHttpError("MERCADO_PAGO","Webhook deve usar HTTPS.",400,"WEBHOOK_HTTPS_REQUIRED");return{ok:true,provider:"MERCADO_PAGO",url,message:"Configure esta URL em Suas integrações > Webhooks no Mercado Pago. Novos pagamentos também recebem notification_url automaticamente."};},
};
