import {pool} from '../db/pool.js';
import {BRASILIA_NOW_SQL} from '../utils/db-time.js';
import {assertConfiguredProductBillingPair} from './product-billing-policy.service.js';

export async function listCommercialProducts(includeInactive=true){const [rows]=await pool.query<any[]>(`SELECT * FROM commercial_products ${includeInactive?'':'WHERE active=1'} ORDER BY name`);for(const row of rows){const [plans]=await pool.query<any[]>('SELECT * FROM commercial_product_plans WHERE product_id=? ORDER BY price_monthly,name',[row.id]);row.plans=plans.map((p:any)=>({...p,id:Number(p.id),price_monthly:Number(p.price_monthly),active:Boolean(p.active)}));row.id=Number(row.id);row.active=Boolean(row.active);row.default_auto_block=Boolean(row.default_auto_block);}return rows;}
export async function getCommercialProduct(id:number){const [rows]=await pool.query<any[]>('SELECT * FROM commercial_products WHERE id=? LIMIT 1',[id]);if(!rows[0])throw Object.assign(new Error('Produto não encontrado.'),{status:404,code:'PRODUCT_NOT_FOUND'});const [plans]=await pool.query<any[]>('SELECT * FROM commercial_product_plans WHERE product_id=? ORDER BY price_monthly,name',[id]);return{...rows[0],id:Number(rows[0].id),plans};}
export async function updateCommercialProduct(id:number,input:{name?:string;description?:string|null;active?:boolean;defaultProvider?:string|null;defaultMethod?:string|null;defaultGraceDays?:number;defaultAutoBlock?:boolean}){const current=await getCommercialProduct(id);const provider=input.defaultProvider===undefined?current.default_provider:input.defaultProvider,method=input.defaultMethod===undefined?current.default_payment_method:input.defaultMethod;assertConfiguredProductBillingPair(provider,method);await pool.query(`UPDATE commercial_products SET name=?,description=?,active=?,default_provider=?,default_payment_method=?,default_grace_days=?,default_auto_block=?,updated_at=${BRASILIA_NOW_SQL} WHERE id=?`,[input.name??current.name,input.description===undefined?current.description:input.description,input.active===undefined?Number(current.active):input.active?1:0,provider,method,input.defaultGraceDays??current.default_grace_days,input.defaultAutoBlock===undefined?Number(current.default_auto_block):input.defaultAutoBlock?1:0,id]);return getCommercialProduct(id);}
export async function createProductPlan(productId:number,input:{code:string;name:string;priceMonthly:number;active?:boolean;metadata?:unknown}){await getCommercialProduct(productId);const [r]=await pool.query<any>(`INSERT INTO commercial_product_plans(product_id,code,name,price_monthly,active,metadata_json,created_at,updated_at) VALUES(?,?,?,?,?,?,${BRASILIA_NOW_SQL},${BRASILIA_NOW_SQL})`,[productId,input.code.trim().toLowerCase(),input.name.trim(),Number(input.priceMonthly),input.active===false?0:1,input.metadata==null?null:JSON.stringify(input.metadata)]);return Number(r.insertId);}
export async function updateProductPlan(productId:number,planId:number,input:{code?:string;name?:string;priceMonthly?:number;active?:boolean;metadata?:unknown}){const [rows]=await pool.query<any[]>('SELECT * FROM commercial_product_plans WHERE id=? AND product_id=? LIMIT 1',[planId,productId]);const p=rows[0];if(!p)throw Object.assign(new Error('Plano do produto não encontrado.'),{status:404});await pool.query(`UPDATE commercial_product_plans SET code=?,name=?,price_monthly=?,active=?,metadata_json=?,updated_at=${BRASILIA_NOW_SQL} WHERE id=? AND product_id=?`,[input.code?.trim().toLowerCase()??p.code,input.name?.trim()??p.name,input.priceMonthly??p.price_monthly,input.active===undefined?Number(p.active):input.active?1:0,input.metadata===undefined?p.metadata_json:JSON.stringify(input.metadata),planId,productId]);return planId;}
