import {pool} from '../db/pool.js';
import {BRASILIA_NOW_SQL} from '../utils/db-time.js';
import {addOneCalendarMonthDate,effectiveSubscriptionPrice} from './product-subscription-core.js';
import {assertConfiguredProductBillingPair} from './product-billing-policy.service.js';

export async function listProductSubscriptions(filters:{productCode?:string;status?:string;customerId?:number}={}){const where=['1=1'],args:any[]=[];if(filters.productCode){where.push('cp.code=?');args.push(filters.productCode);}if(filters.status){where.push('ps.status=?');args.push(filters.status);}if(filters.customerId){where.push('ps.commercial_customer_id=?');args.push(filters.customerId);}const [rows]=await pool.query<any[]>(`SELECT ps.*,cc.legal_name AS customer_name,cc.document AS customer_document,cc.financial_contact_email AS customer_financial_email,cc.email AS customer_email,cp.code AS product_code,cp.name AS product_name,cp.default_provider,cp.default_payment_method,cpp.code AS plan_code,cpp.name AS plan_name,cpp.price_monthly AS plan_price FROM product_subscriptions ps JOIN commercial_customers cc ON cc.id=ps.commercial_customer_id JOIN commercial_products cp ON cp.id=ps.product_id LEFT JOIN commercial_product_plans cpp ON cpp.id=ps.product_plan_id WHERE ${where.join(' AND ')} ORDER BY cc.legal_name,cp.name`,args);return rows.map(r=>({...r,id:Number(r.id),commercial_customer_id:Number(r.commercial_customer_id),product_id:Number(r.product_id),product_plan_id:r.product_plan_id==null?null:Number(r.product_plan_id),monthly_price:Number(r.monthly_price),discount_percent:Number(r.discount_percent),effective_price:effectiveSubscriptionPrice({monthlyPrice:Number(r.monthly_price),discountPercent:Number(r.discount_percent)})}));}
export async function getProductSubscription(id:number,db:any=pool){const [rows]=await db.query<any[]>(`SELECT ps.*,cc.legal_name AS customer_name,cc.trade_name AS customer_trade_name,cc.person_type,cc.document AS customer_document,cc.email AS customer_email,cc.phone AS customer_phone,cc.financial_contact_name,cc.financial_contact_document,cc.financial_contact_email,cc.financial_contact_phone,cc.zip_code,cc.street,cc.number,cc.complement,cc.district,cc.city,cc.state,cp.code AS product_code,cp.name AS product_name,cp.default_provider,cp.default_payment_method,cp.default_grace_days,cp.default_auto_block,cpp.code AS plan_code,cpp.name AS plan_name,cpp.price_monthly AS plan_price FROM product_subscriptions ps JOIN commercial_customers cc ON cc.id=ps.commercial_customer_id JOIN commercial_products cp ON cp.id=ps.product_id LEFT JOIN commercial_product_plans cpp ON cpp.id=ps.product_plan_id WHERE ps.id=? LIMIT 1`,[id]);if(!rows[0])throw Object.assign(new Error('Assinatura de produto não encontrada.'),{status:404,code:'PRODUCT_SUBSCRIPTION_NOT_FOUND'});return rows[0];}
export async function createProductSubscription(input:{commercialCustomerId:number;productId:number;productPlanId?:number|null;externalSource?:string|null;externalAccountId?:string|null;billingSource?:string;status?:string;monthlyPrice?:number;discountPercent?:number;startsAt?:string|null;currentPeriodEnd?:string|null;nextDueDate?:string|null;billingProvider?:string|null;billingMethod?:string|null;graceDays?:number;autoBlock?:boolean;firstCycleProrataEnabled?:boolean;metadata?:unknown}){assertConfiguredProductBillingPair(input.billingProvider??null,input.billingMethod??null);let price=input.monthlyPrice; if(price==null&&input.productPlanId){const [rows]=await pool.query<any[]>('SELECT price_monthly FROM commercial_product_plans WHERE id=? AND product_id=? LIMIT 1',[input.productPlanId,input.productId]);if(!rows[0])throw Object.assign(new Error('Plano não pertence ao produto selecionado.'),{status:400});price=Number(rows[0].price_monthly);}const [r]=await pool.query<any>(`INSERT INTO product_subscriptions(commercial_customer_id,product_id,product_plan_id,external_source,external_account_id,billing_source,status,monthly_price,discount_percent,starts_at,current_period_end,next_due_date,billing_provider,billing_method,grace_days,auto_block,first_cycle_prorata_enabled,metadata_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,${BRASILIA_NOW_SQL},${BRASILIA_NOW_SQL})`,[input.commercialCustomerId,input.productId,input.productPlanId||null,input.externalSource||null,input.externalAccountId||null,input.billingSource||'PONTO_CERTO',input.status||'ACTIVE',Number(price||0),Number(input.discountPercent||0),input.startsAt||null,input.currentPeriodEnd||null,input.nextDueDate||null,input.billingProvider||null,input.billingMethod||null,input.graceDays??3,input.autoBlock===false?0:1,input.firstCycleProrataEnabled===false?0:1,input.metadata==null?null:JSON.stringify(input.metadata)]);return getProductSubscription(Number(r.insertId));}
export async function updateProductSubscription(id:number,input:any){
  const conn=await pool.getConnection();
  try{
    await conn.beginTransaction();
    const current:any=await getProductSubscription(id,conn);
    const provider=input.billingProvider===undefined?current.billing_provider:input.billingProvider;
    const method=input.billingMethod===undefined?current.billing_method:input.billingMethod;
    assertConfiguredProductBillingPair(provider,method);
    const nextPlanId=input.productPlanId===undefined?current.product_plan_id:input.productPlanId;
    if(nextPlanId!=null){const [plans]:any=await conn.query('SELECT id FROM commercial_product_plans WHERE id=? AND product_id=? LIMIT 1',[nextPlanId,current.product_id]);if(!plans[0])throw Object.assign(new Error('Plano não pertence ao produto da assinatura.'),{status:400,code:'PRODUCT_PLAN_MISMATCH'});}
    const nextDue=input.nextDueDate===undefined?current.next_due_date:input.nextDueDate;
    const nextPeriodEnd=input.currentPeriodEnd===undefined?(input.nextDueDate!==undefined&&nextDue?`${String(nextDue).slice(0,10)} 23:59:59`:current.current_period_end):input.currentPeriodEnd;
    await conn.query(`UPDATE product_subscriptions SET product_plan_id=?,billing_source=?,status=?,monthly_price=?,discount_percent=?,current_period_start=?,current_period_end=?,next_due_date=?,billing_provider=?,billing_method=?,grace_days=?,auto_block=?,first_cycle_prorata_enabled=?,blocked_at=?,metadata_json=?,updated_at=${BRASILIA_NOW_SQL} WHERE id=?`,[nextPlanId,input.billingSource??current.billing_source,input.status??current.status,input.monthlyPrice??current.monthly_price,input.discountPercent??current.discount_percent,input.currentPeriodStart===undefined?current.current_period_start:input.currentPeriodStart,nextPeriodEnd,nextDue,provider,method,input.graceDays??current.grace_days,input.autoBlock===undefined?Number(current.auto_block):input.autoBlock?1:0,input.firstCycleProrataEnabled===undefined?Number(current.first_cycle_prorata_enabled||0):input.firstCycleProrataEnabled?1:0,input.blockedAt===undefined?current.blocked_at:input.blockedAt,input.metadata===undefined?current.metadata_json:JSON.stringify(input.metadata),id]);
    if(input.financialContactEmail!==undefined){const email=String(input.financialContactEmail||'').trim().toLowerCase()||null;await conn.query(`UPDATE commercial_customers SET financial_contact_email=?,updated_at=${BRASILIA_NOW_SQL} WHERE id=?`,[email,current.commercial_customer_id]);}
    await conn.commit();
    return getProductSubscription(id);
  }catch(error){await conn.rollback();throw error;}finally{conn.release();}
}

export async function advanceProductSubscriptionPeriod(db:any,subscriptionId:number,fallbackDate:string){
  const [rows]=await db.query<any[]>(`SELECT id,current_period_end,next_due_date,status FROM product_subscriptions WHERE id=? FOR UPDATE`,[subscriptionId]);
  const current=rows[0];
  if(!current)throw Object.assign(new Error('Assinatura de produto não encontrada.'),{status:404,code:'PRODUCT_SUBSCRIPTION_NOT_FOUND'});
  const base=current.current_period_end||current.next_due_date||fallbackDate;
  const nextDate=addOneCalendarMonthDate(base);
  const currentStart=current.current_period_end||current.next_due_date||fallbackDate;
  await db.query(`UPDATE product_subscriptions SET current_period_start=?,current_period_end=?,next_due_date=?,status='ACTIVE',blocked_at=NULL,grace_until=NULL,updated_at=${BRASILIA_NOW_SQL} WHERE id=?`,[currentStart,`${nextDate} 23:59:59`,nextDate,subscriptionId]);
  return{subscriptionId,nextDueDate:nextDate,currentPeriodEnd:`${nextDate} 23:59:59`};
}
