import {Router} from 'express';import {z} from 'zod';import {safe} from './saas-commercial.routes.js';import {createProductPlan,getCommercialProduct,listCommercialProducts,updateCommercialProduct,updateProductPlan} from '../services/product-catalog.service.js';import {createProductSubscription,getProductSubscription,listProductSubscriptions,updateProductSubscription} from '../services/product-subscription.service.js';import {grantProductFinancialException,revokeProductFinancialException,syncProductFinancialAccess} from '../services/product-financial-access.service.js';import {writeAudit} from '../utils/audit.js';import {syncSubscriptionOperationalState} from '../services/product-integration.service.js';
export const commercialProductsRouter=Router();export const productSubscriptionsRouter=Router();const id=(v:unknown)=>z.coerce.number().int().positive().parse(v);
commercialProductsRouter.get('/',safe(async(_req,res)=>res.json(await listCommercialProducts(true))));
commercialProductsRouter.get('/:id(\\d+)',safe(async(req,res)=>res.json(await getCommercialProduct(id(req.params.id)))));
commercialProductsRouter.put('/:id(\\d+)',safe(async(req,res)=>{const key=id(req.params.id);const before=await getCommercialProduct(key);const d=z.object({name:z.string().min(2).max(120).optional(),description:z.string().max(500).optional().nullable(),active:z.boolean().optional(),defaultProvider:z.enum(['EFI','CORA','MERCADO_PAGO']).optional().nullable(),defaultMethod:z.enum(['HYBRID','PIX','BOLETO']).optional().nullable(),defaultGraceDays:z.number().int().min(0).max(365).optional(),defaultAutoBlock:z.boolean().optional()}).parse(req.body);const out=await updateCommercialProduct(key,d);await writeAudit(req,'UPDATE','commercial_product',key,before,out);res.json(out);}));
commercialProductsRouter.post('/:id(\\d+)/plans',safe(async(req,res)=>{const productId=id(req.params.id);const d=z.object({code:z.string().min(2).max(80),name:z.string().min(2).max(160),priceMonthly:z.number().min(0),active:z.boolean().optional(),metadata:z.any().optional()}).parse(req.body);const planId=await createProductPlan(productId,d);await writeAudit(req,'CREATE','commercial_product_plan',planId,undefined,d);res.status(201).json({id:planId});}));
commercialProductsRouter.put('/:id(\\d+)/plans/:planId(\\d+)',safe(async(req,res)=>{const productId=id(req.params.id),planId=id(req.params.planId);const d=z.object({code:z.string().min(2).max(80).optional(),name:z.string().min(2).max(160).optional(),priceMonthly:z.number().min(0).optional(),active:z.boolean().optional(),metadata:z.any().optional()}).parse(req.body);await updateProductPlan(productId,planId,d);await writeAudit(req,'UPDATE','commercial_product_plan',planId,undefined,d);res.json({ok:true});}));
productSubscriptionsRouter.get('/',safe(async(req,res)=>res.json(await listProductSubscriptions({productCode:String(req.query.productCode||'').trim()||undefined,status:String(req.query.status||'').trim()||undefined,customerId:req.query.customerId?id(req.query.customerId):undefined}))));
productSubscriptionsRouter.get('/:id(\\d+)',safe(async(req,res)=>res.json(await getProductSubscription(id(req.params.id)))));
productSubscriptionsRouter.post('/',safe(async(req,res)=>{const d=z.object({commercialCustomerId:z.number().int().positive(),productId:z.number().int().positive(),productPlanId:z.number().int().positive().optional().nullable(),externalSource:z.string().max(40).optional().nullable(),externalAccountId:z.string().max(190).optional().nullable(),billingSource:z.string().max(40).optional(),status:z.enum(['ACTIVE','GRACE','PAST_DUE','BLOCKED','CANCELED','PENDING_DATA']).optional(),monthlyPrice:z.number().min(0).optional(),discountPercent:z.number().min(0).max(100).optional(),startsAt:z.string().optional().nullable(),currentPeriodEnd:z.string().optional().nullable(),nextDueDate:z.string().optional().nullable(),billingProvider:z.enum(['EFI','CORA','MERCADO_PAGO']).optional().nullable(),billingMethod:z.enum(['HYBRID','PIX','BOLETO']).optional().nullable(),graceDays:z.number().int().min(0).max(365).optional(),autoBlock:z.boolean().optional(),firstCycleProrataEnabled:z.boolean().optional(),metadata:z.any().optional()}).parse(req.body);const out=await createProductSubscription(d);await writeAudit(req,'CREATE','product_subscription',out.id,undefined,out);res.status(201).json(out);}));
productSubscriptionsRouter.put('/:id(\\d+)',safe(async(req,res)=>{const key=id(req.params.id);const before=await getProductSubscription(key);const d=z.object({productPlanId:z.number().int().positive().optional().nullable(),billingSource:z.string().max(40).optional(),status:z.enum(['ACTIVE','GRACE','PAST_DUE','BLOCKED','CANCELED','PENDING_DATA','PROVISIONING','PROVISIONING_ERROR']).optional(),monthlyPrice:z.number().min(0).optional(),discountPercent:z.number().min(0).max(100).optional(),currentPeriodStart:z.string().optional().nullable(),currentPeriodEnd:z.string().optional().nullable(),nextDueDate:z.string().optional().nullable(),billingProvider:z.enum(['EFI','CORA','MERCADO_PAGO']).optional().nullable(),billingMethod:z.enum(['HYBRID','PIX','BOLETO']).optional().nullable(),graceDays:z.number().int().min(0).max(365).optional(),autoBlock:z.boolean().optional(),firstCycleProrataEnabled:z.boolean().optional(),blockedAt:z.string().optional().nullable(),financialContactEmail:z.string().email().max(190).optional().nullable(),metadata:z.any().optional()}).parse(req.body);let out=await updateProductSubscription(key,d);if(d.graceDays!==undefined||d.autoBlock!==undefined){await syncProductFinancialAccess(key);out=await getProductSubscription(key);}await writeAudit(req,'UPDATE','product_subscription',key,before,out);if(String(out.product_code||'').toUpperCase()==='MOVYO'&&String(out.billing_source||'').toUpperCase()==='PONTO_CERTO')await syncSubscriptionOperationalState(key,'SUBSCRIPTION_UPDATED');res.json(out);}));

productSubscriptionsRouter.post('/:id(\\d+)/access-exception',safe(async(req,res)=>{const key=id(req.params.id);const before=await getProductSubscription(key);const d=z.object({days:z.union([z.literal(5),z.literal(10),z.literal(30)]).optional(),endsAt:z.string().optional(),reason:z.string().min(3).max(500)}).refine(v=>Boolean(v.days)||Boolean(v.endsAt),{message:'Informe dias ou data final.'}).parse(req.body);const endsAt=d.endsAt?new Date(d.endsAt):new Date(Date.now()+Number(d.days||0)*86400000);const out=await grantProductFinancialException({subscriptionId:key,endsAt:endsAt.toISOString(),reason:d.reason,actorUserId:req.auth!.userId});await writeAudit(req,'UPDATE','product_subscription_access',key,before,out);res.json(out);}));
productSubscriptionsRouter.post('/:id(\\d+)/revoke-access-exception',safe(async(req,res)=>{const key=id(req.params.id);const before=await getProductSubscription(key);const out=await revokeProductFinancialException({subscriptionId:key,actorUserId:req.auth!.userId});await writeAudit(req,'UPDATE','product_subscription_access',key,before,out);res.json(out);}));
