import {Router} from "express";
import {z} from "zod";
import {createHash} from "node:crypto";
import {pool} from "../db/pool.js";
import {proposalSchema,proposalStatus,readJson} from "../services/commercial-rules.js";
import {proposalDocx,proposalPdf} from "../services/proposal-documents.service.js";
import {createTenantInTransaction} from "../services/tenant-provisioning.service.js";
import {writeAudit} from "../utils/audit.js";
import {safe} from "./saas-commercial.routes.js";
export const proposalsRouter=Router();
const idOf=(v:unknown)=>z.coerce.number().int().positive().parse(v);
const select="SELECT p.*,COALESCE(p.plan_name_snapshot,pl.name) AS plan_name FROM commercial_proposals p JOIN plans pl ON pl.id=p.plan_id";
async function get(id:number){const [rows]=await pool.query<any[]>(`${select} WHERE p.id=?`,[id]);if(!rows[0])throw Object.assign(new Error("Proposta não encontrada."),{status:404});return rows[0];}
const dto=(p:any)=>({...p,status:proposalStatus(p.status,p.valid_until),features:readJson(p.features_json,{})});
async function validatePlan(d:z.infer<typeof proposalSchema>){const [rows]=await pool.query<any[]>("SELECT p.*,s.is_custom FROM plans p LEFT JOIN saas_plan_settings s ON s.plan_id=p.id WHERE p.id=? AND p.active=1",[d.planId]);if(!rows[0])throw Object.assign(new Error("Selecione um plano ativo."),{status:400});if(rows[0].is_custom&&d.maxEmployees<=150)throw Object.assign(new Error("O plano Personalizado deve ter mais de 150 funcionários."),{status:400});return rows[0];}
proposalsRouter.get("/",safe(async(req,res)=>{const where:string[]=[],args:any[]=[];const q=String(req.query.q||"").trim(),status=String(req.query.status||"").trim(),planId=req.query.planId?z.coerce.number().int().positive().parse(req.query.planId):null,from=String(req.query.from||"").trim(),to=String(req.query.to||"").trim(),expired=String(req.query.expired||"")==="1",converted=String(req.query.converted||"")==="1";if(q){where.push("(p.proposal_number LIKE ? OR p.company_name LIKE ? OR p.cnpj LIKE ?)");args.push(`%${q}%`,`%${q}%`,`%${q}%`);}if(status){where.push("p.status=?");args.push(z.enum(["DRAFT","SENT","APPROVED","REJECTED","EXPIRED","CONVERTED"]).parse(status));}if(planId){where.push("p.plan_id=?");args.push(planId);}if(from){where.push("DATE(p.created_at)>=?");args.push(z.string().regex(/^\d{4}-\d{2}-\d{2}$/).parse(from));}if(to){where.push("DATE(p.created_at)<=?");args.push(z.string().regex(/^\d{4}-\d{2}-\d{2}$/).parse(to));}if(expired)where.push("(p.status='EXPIRED' OR (p.status IN ('DRAFT','SENT') AND p.valid_until<CURDATE()))");if(converted)where.push("(p.status='CONVERTED' OR p.converted_tenant_id IS NOT NULL)");const [rows]=await pool.query<any[]>(`${select} ${where.length?"WHERE "+where.join(" AND "):""} ORDER BY p.id DESC LIMIT 500`,args);res.json(rows.map(dto));}));
proposalsRouter.get("/:id(\\d+)",safe(async(req,res)=>{const p=await get(idOf(req.params.id));const [documents]=await pool.query<any[]>("SELECT id,revision,format,filename,sha256,created_at FROM proposal_documents WHERE proposal_id=? ORDER BY id DESC",[p.id]);const [history]=await pool.query<any[]>("SELECT a.id,a.action,a.created_at,u.name AS user_name FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id WHERE a.entity_type='proposal' AND a.entity_id=? ORDER BY a.id DESC LIMIT 200",[p.id]);res.json({...dto(p),documents,history});}));
const values=(d:z.infer<typeof proposalSchema>)=>[d.companyName,d.cnpj,d.responsibleName,d.email,d.phone,d.planId,d.maxEmployees,d.priceMonthly,d.maxBranches,JSON.stringify(d.features),d.implementationDays,d.implementationFee,d.validUntil,d.notes];
proposalsRouter.post("/",safe(async(req,res)=>{const d=proposalSchema.parse(req.body);const plan=await validatePlan(d);const snapshot={planName:plan.name,maxEmployees:d.maxEmployees,priceMonthly:d.priceMonthly,maxBranches:d.maxBranches,features:d.features,implementationDays:d.implementationDays,implementationFee:d.implementationFee};const [r]=await pool.query<any>("INSERT INTO commercial_proposals(proposal_number,company_name,cnpj,responsible_name,email,phone,plan_id,plan_name_snapshot,max_employees,price_monthly,max_branches,features_json,commercial_snapshot_json,implementation_days,implementation_fee,valid_until,notes,created_by,updated_by,created_at,updated_at) VALUES(NULL,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW())",[d.companyName,d.cnpj,d.responsibleName,d.email,d.phone,d.planId,plan.name,d.maxEmployees,d.priceMonthly,d.maxBranches,JSON.stringify(d.features),JSON.stringify(snapshot),d.implementationDays,d.implementationFee,d.validUntil,d.notes,req.auth!.userId,req.auth!.userId]);const number=`PC-${new Date().getFullYear()}-${String(r.insertId).padStart(5,"0")}`;await pool.query("UPDATE commercial_proposals SET proposal_number=? WHERE id=?",[number,r.insertId]);await writeAudit(req,"CREATE","proposal",r.insertId,undefined,{...d,proposalNumber:number,snapshot});res.status(201).json({id:r.insertId,proposalNumber:number});}));
proposalsRouter.put("/:id(\\d+)",safe(async(req,res)=>{const id=idOf(req.params.id),d=proposalSchema.parse(req.body);const plan=await validatePlan(d);const revision=z.number().int().positive().parse(req.body.revision);const snapshot={planName:plan.name,maxEmployees:d.maxEmployees,priceMonthly:d.priceMonthly,maxBranches:d.maxBranches,features:d.features,implementationDays:d.implementationDays,implementationFee:d.implementationFee};const [r]=await pool.query<any>("UPDATE commercial_proposals SET company_name=?,cnpj=?,responsible_name=?,email=?,phone=?,plan_id=?,plan_name_snapshot=?,max_employees=?,price_monthly=?,max_branches=?,features_json=?,commercial_snapshot_json=?,implementation_days=?,implementation_fee=?,valid_until=?,notes=?,updated_by=?,revision=revision+1,status='DRAFT',updated_at=NOW() WHERE id=? AND revision=? AND status IN ('DRAFT','REJECTED','EXPIRED') AND converted_tenant_id IS NULL",[d.companyName,d.cnpj,d.responsibleName,d.email,d.phone,d.planId,plan.name,d.maxEmployees,d.priceMonthly,d.maxBranches,JSON.stringify(d.features),JSON.stringify(snapshot),d.implementationDays,d.implementationFee,d.validUntil,d.notes,req.auth!.userId,id,revision]);if(!r.affectedRows)return res.status(409).json({message:"Proposta alterada ou aprovada. Reabra como rascunho antes de editar."});await writeAudit(req,"UPDATE","proposal",id,undefined,{...d,snapshot});res.json({id});}));
proposalsRouter.patch("/:id(\\d+)/status",safe(async(req,res)=>{const id=idOf(req.params.id),d=z.object({status:z.enum(["DRAFT","SENT","APPROVED","REJECTED","EXPIRED"]),revision:z.number().int().positive()}).parse(req.body);const p=await get(id);if(proposalStatus(p.status,p.valid_until)==="EXPIRED"&&["SENT","APPROVED"].includes(d.status))return res.status(409).json({message:"Proposta expirada. Atualize a validade em um rascunho."});const [r]=await pool.query<any>("UPDATE commercial_proposals SET status=?,updated_by=?,updated_at=NOW(),revision=revision+1 WHERE id=? AND revision=? AND converted_tenant_id IS NULL",[d.status,req.auth!.userId,id,d.revision]);if(!r.affectedRows)return res.status(409).json({message:"A proposta foi alterada ou já convertida. Atualize a tela."});await writeAudit(req,d.status,"proposal",id,{status:p.status},{status:d.status});res.json({ok:true});}));
proposalsRouter.post("/:id(\\d+)/documents/:format",safe(async(req,res)=>{const id=idOf(req.params.id),format=z.enum(["docx","pdf"]).parse(req.params.format),p=await get(id);const docx=await proposalDocx(p);const buffer=format==="pdf"?await proposalPdf(docx):docx;const filename=`proposta-${id}-v${p.revision}.${format}`;const conn=await pool.getConnection();let documentId:number;try{await conn.beginTransaction();const [current]=await conn.query<any[]>("SELECT revision FROM commercial_proposals WHERE id=? FOR UPDATE",[id]);if(Number(current[0]?.revision)!==Number(p.revision))throw Object.assign(new Error("A proposta mudou durante a geração. Gere novamente."),{status:409});const [r]=await conn.query<any>("INSERT INTO proposal_documents(proposal_id,revision,format,filename,sha256,content,created_by,created_at) VALUES(?,?,?,?,?,?,?,NOW())",[id,p.revision,format,filename,createHash("sha256").update(buffer).digest("hex"),buffer,req.auth!.userId]);documentId=r.insertId;await conn.commit();}catch(e){await conn.rollback();throw e;}finally{conn.release();}await writeAudit(req,`GENERATE_${format.toUpperCase()}`,"proposal",id,undefined,{revision:p.revision,documentId});res.status(201).json({id:documentId,filename});}));
proposalsRouter.get("/documents/:documentId(\\d+)/download",safe(async(req,res)=>{const [rows]=await pool.query<any[]>("SELECT * FROM proposal_documents WHERE id=?",[idOf(req.params.documentId)]);const d=rows[0];if(!d)return res.sendStatus(404);await writeAudit(req,"DOWNLOAD","proposal",d.proposal_id,undefined,{documentId:d.id});res.setHeader("Cache-Control","no-store");res.setHeader("Content-Disposition",`attachment; filename="${d.filename}"`);res.type(d.format==="pdf"?"application/pdf":"application/vnd.openxmlformats-officedocument.wordprocessingml.document").send(d.content);}));
proposalsRouter.post("/:id(\\d+)/convert",safe(async(req,res)=>{const id=idOf(req.params.id),d=z.object({slug:z.string().min(2).max(80).regex(/^[a-z0-9-]+$/),adminName:z.string().min(2).max(160),adminEmail:z.string().email().max(190),adminPassword:z.string().min(8).max(128)}).parse(req.body);const conn=await pool.getConnection();let result:any;try{await conn.beginTransaction();const [rows]=await conn.query<any[]>("SELECT p.*,c.id AS contract_id,c.status AS contract_status,c.tenant_id AS contract_tenant_id FROM commercial_proposals p LEFT JOIN commercial_contracts c ON c.proposal_id=p.id WHERE p.id=? FOR UPDATE",[id]);const p=rows[0];if(!p)throw Object.assign(new Error("Proposta não encontrada."),{status:404});if(p.converted_tenant_id||p.contract_tenant_id){await conn.commit();return res.json({tenantId:p.converted_tenant_id||p.contract_tenant_id,alreadyConverted:true});}if(p.contract_status!=="SIGNED")throw Object.assign(new Error("A ativação do cliente exige contrato assinado."),{status:409});result=await createTenantInTransaction(conn,{...d,tenantName:p.company_name,companyName:p.company_name,cnpj:p.cnpj,planId:p.plan_id,trialDays:0});await conn.query("INSERT INTO tenant_contracts(tenant_id,max_employees,price_monthly,max_branches,features_json,updated_at) VALUES(?,?,?,?,?,NOW())",[result.tenantId,p.max_employees,p.price_monthly,p.max_branches,p.features_json]);await conn.query("UPDATE commercial_contracts SET tenant_id=?,updated_at=NOW() WHERE id=?",[result.tenantId,p.contract_id]);await conn.query("UPDATE commercial_proposals SET converted_tenant_id=?,status='CONVERTED',updated_by=?,updated_at=NOW() WHERE id=?",[result.tenantId,req.auth!.userId,id]);await conn.commit();}catch(e){await conn.rollback();throw e;}finally{conn.release();}await writeAudit(req,"CONVERT","proposal",id,undefined,result);res.status(201).json(result);}));
