import {Router} from "express";
import {z} from "zod";
import {createHash} from "node:crypto";
import {pool} from "../db/pool.js";
import {proposalSchema,proposalStatus,readJson} from "../services/commercial-rules.js";
import {proposalDocx,proposalPdf} from "../services/proposal-documents.service.js";
import {createTenantInTransaction} from "../services/tenant-provisioning.service.js";
import {writeAudit} from "../utils/audit.js";
import {safe} from "./saas-commercial.routes.js";
export const proposalsRouter=Router();
const idOf=(v:unknown)=>z.coerce.number().int().positive().parse(v);
const select="SELECT p.*,pl.name AS plan_name FROM commercial_proposals p JOIN plans pl ON pl.id=p.plan_id";
async function get(id:number){const [rows]=await pool.query<any[]>(`${select} WHERE p.id=?`,[id]);if(!rows[0])throw Object.assign(new Error("Proposta não encontrada."),{status:404});return rows[0];}
const dto=(p:any)=>({...p,status:proposalStatus(p.status,p.valid_until),features:readJson(p.features_json,{})});
async function validatePlan(d:z.infer<typeof proposalSchema>){const [rows]=await pool.query<any[]>("SELECT p.*,s.is_custom FROM plans p LEFT JOIN saas_plan_settings s ON s.plan_id=p.id WHERE p.id=? AND p.active=1",[d.planId]);if(!rows[0])throw Object.assign(new Error("Selecione um plano ativo."),{status:400});if(rows[0].is_custom&&d.maxEmployees<=150)throw Object.assign(new Error("O plano Personalizado deve ter mais de 150 funcionários."),{status:400});}
proposalsRouter.get("/",safe(async(_req,res)=>{const [rows]=await pool.query<any[]>(`${select} ORDER BY p.id DESC LIMIT 500`);res.json(rows.map(dto));}));
proposalsRouter.get("/:id",safe(async(req,res)=>{const p=await get(idOf(req.params.id));const [documents]=await pool.query<any[]>("SELECT id,revision,format,filename,sha256,created_at FROM proposal_documents WHERE proposal_id=? ORDER BY id DESC",[p.id]);const [history]=await pool.query<any[]>("SELECT a.id,a.action,a.created_at,u.name AS user_name FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id WHERE a.entity_type='proposal' AND a.entity_id=? ORDER BY a.id DESC LIMIT 200",[p.id]);res.json({...dto(p),documents,history});}));
const values=(d:z.infer<typeof proposalSchema>)=>[d.companyName,d.cnpj,d.responsibleName,d.email,d.phone,d.planId,d.maxEmployees,d.priceMonthly,d.maxBranches,JSON.stringify(d.features),d.implementationDays,d.implementationFee,d.validUntil,d.notes];
proposalsRouter.post("/",safe(async(req,res)=>{const d=proposalSchema.parse(req.body);await validatePlan(d);const [r]=await pool.query<any>("INSERT INTO commercial_proposals(company_name,cnpj,responsible_name,email,phone,plan_id,max_employees,price_monthly,max_branches,features_json,implementation_days,implementation_fee,valid_until,notes,created_by,updated_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW())",[...values(d),req.auth!.userId,req.auth!.userId]);await writeAudit(req,"CREATE","proposal",r.insertId,undefined,d);res.status(201).json({id:r.insertId});}));
proposalsRouter.put("/:id",safe(async(req,res)=>{const id=idOf(req.params.id),d=proposalSchema.parse(req.body);await validatePlan(d);const revision=z.number().int().positive().parse(req.body.revision);const [r]=await pool.query<any>("UPDATE commercial_proposals SET company_name=?,cnpj=?,responsible_name=?,email=?,phone=?,plan_id=?,max_employees=?,price_monthly=?,max_branches=?,features_json=?,implementation_days=?,implementation_fee=?,valid_until=?,notes=?,updated_by=?,revision=revision+1,status='DRAFT',updated_at=NOW() WHERE id=? AND revision=? AND status IN ('DRAFT','REJECTED','EXPIRED') AND converted_tenant_id IS NULL",[...values(d),req.auth!.userId,id,revision]);if(!r.affectedRows)return res.status(409).json({message:"Proposta alterada ou aprovada. Reabra como rascunho antes de editar."});await writeAudit(req,"UPDATE","proposal",id,undefined,d);res.json({id});}));
proposalsRouter.patch("/:id/status",safe(async(req,res)=>{const id=idOf(req.params.id),d=z.object({status:z.enum(["DRAFT","SENT","APPROVED","REJECTED","EXPIRED"]),revision:z.number().int().positive()}).parse(req.body);const p=await get(id);if(proposalStatus(p.status,p.valid_until)==="EXPIRED"&&["SENT","APPROVED"].includes(d.status))return res.status(409).json({message:"Proposta expirada. Atualize a validade em um rascunho."});const [r]=await pool.query<any>("UPDATE commercial_proposals SET status=?,updated_by=?,updated_at=NOW(),revision=revision+1 WHERE id=? AND revision=? AND converted_tenant_id IS NULL",[d.status,req.auth!.userId,id,d.revision]);if(!r.affectedRows)return res.status(409).json({message:"A proposta foi alterada ou já convertida. Atualize a tela."});await writeAudit(req,d.status,"proposal",id,{status:p.status},{status:d.status});res.json({ok:true});}));
proposalsRouter.post("/:id/documents/:format",safe(async(req,res)=>{const id=idOf(req.params.id),format=z.enum(["docx","pdf"]).parse(req.params.format),p=await get(id);const docx=await proposalDocx(p);const buffer=format==="pdf"?await proposalPdf(docx):docx;const filename=`proposta-${id}-v${p.revision}.${format}`;const conn=await pool.getConnection();let documentId:number;try{await conn.beginTransaction();const [current]=await conn.query<any[]>("SELECT revision FROM commercial_proposals WHERE id=? FOR UPDATE",[id]);if(Number(current[0]?.revision)!==Number(p.revision))throw Object.assign(new Error("A proposta mudou durante a geração. Gere novamente."),{status:409});const [r]=await conn.query<any>("INSERT INTO proposal_documents(proposal_id,revision,format,filename,sha256,content,created_by,created_at) VALUES(?,?,?,?,?,?,?,NOW())",[id,p.revision,format,filename,createHash("sha256").update(buffer).digest("hex"),buffer,req.auth!.userId]);documentId=r.insertId;await conn.commit();}catch(e){await conn.rollback();throw e;}finally{conn.release();}await writeAudit(req,`GENERATE_${format.toUpperCase()}`,"proposal",id,undefined,{revision:p.revision,documentId});res.status(201).json({id:documentId,filename});}));
proposalsRouter.get("/documents/:documentId/download",safe(async(req,res)=>{const [rows]=await pool.query<any[]>("SELECT * FROM proposal_documents WHERE id=?",[idOf(req.params.documentId)]);const d=rows[0];if(!d)return res.sendStatus(404);await writeAudit(req,"DOWNLOAD","proposal",d.proposal_id,undefined,{documentId:d.id});res.setHeader("Cache-Control","no-store");res.setHeader("Content-Disposition",`attachment; filename="${d.filename}"`);res.type(d.format==="pdf"?"application/pdf":"application/vnd.openxmlformats-officedocument.wordprocessingml.document").send(d.content);}));
proposalsRouter.post("/:id/convert",safe(async(req,res)=>{const id=idOf(req.params.id),d=z.object({slug:z.string().min(2).max(80).regex(/^[a-z0-9-]+$/),adminName:z.string().min(2).max(160),adminEmail:z.string().email().max(190),adminPassword:z.string().min(8).max(128)}).parse(req.body);const conn=await pool.getConnection();let result:any;try{await conn.beginTransaction();const [rows]=await conn.query<any[]>("SELECT * FROM commercial_proposals WHERE id=? FOR UPDATE",[id]);const p=rows[0];if(!p)throw Object.assign(new Error("Proposta não encontrada."),{status:404});if(p.converted_tenant_id){await conn.commit();return res.json({tenantId:p.converted_tenant_id,alreadyConverted:true});}if(p.status!=="APPROVED")throw Object.assign(new Error("Aprove a proposta antes de converter em cliente."),{status:409});result=await createTenantInTransaction(conn,{...d,tenantName:p.company_name,companyName:p.company_name,cnpj:p.cnpj,planId:p.plan_id,trialDays:0});await conn.query("INSERT INTO tenant_contracts(tenant_id,max_employees,price_monthly,max_branches,features_json,updated_at) VALUES(?,?,?,?,?,NOW())",[result.tenantId,p.max_employees,p.price_monthly,p.max_branches,p.features_json]);await conn.query("UPDATE commercial_proposals SET converted_tenant_id=?,updated_by=?,updated_at=NOW() WHERE id=?",[result.tenantId,req.auth!.userId,id]);await conn.commit();}catch(e){await conn.rollback();throw e;}finally{conn.release();}await writeAudit(req,"CONVERT","proposal",id,undefined,result);res.status(201).json(result);}));
