import { Router } from "express";
import { z } from "zod";
import { safe } from "./saas-commercial.routes.js";
import {
  cancelCharge, createAdHocCharge, createImplementationCharge, createMonthlyCharge, getBillingProfile, getCharge,
  getChargePdf, getFinancialDashboard, getImplementationSuggestion, issueCharge, listCharges, listFinancialEvents,
  listReceipts, reconcileCharge, recordManualPayment, updateBillingProfile,
} from "../services/financial.service.js";
import { getTenantFinancialAccess, grantFinancialException, listFinancialExceptions, revokeFinancialException } from "../services/financial-access.service.js";
import { configurePaymentProviderWebhook, getFinancialProviderSettings, testPaymentProvider, updateFinancialProviderSettings } from "../services/payment-provider-settings.service.js";
import { exceptionEndFromPreset } from "../services/financial-access-core.js";
import { writeAudit } from "../utils/audit.js";
import { listChargeDeliveries, sendFinancialChargeEmail } from "../services/financial-email.service.js";

export const saasFinanceRouter=Router();
const id=(v:unknown)=>z.coerce.number().int().positive().parse(v);
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
const providerSchema=z.enum(["CORA","EFI","MERCADO_PAGO"]);
const methodSchema=z.enum(["HYBRID","PIX","BOLETO"]);
const chargeCommon=z.object({issue:z.boolean().optional().default(true),sendEmailAfterIssue:z.boolean().optional(),sendEmail:z.boolean().optional()});
const chargeEmailPreference=(input:{sendEmailAfterIssue?:boolean;sendEmail?:boolean})=>input.sendEmailAfterIssue??input.sendEmail;
const csvCell=(value:unknown)=>{const text=value==null?"":String(value);return `"${text.replace(/"/g,'""')}"`;};
const csv=(headers:string[],rows:unknown[][])=>`\uFEFF${[headers,...rows].map(row=>row.map(csvCell).join(";")).join("\n")}`;
const sendCsv=(res:any,filename:string,body:string)=>{res.setHeader("Content-Type","text/csv; charset=utf-8");res.setHeader("Content-Disposition",`attachment; filename=${filename}`);res.send(body);};


saasFinanceRouter.get("/dashboard",safe(async(_req,res)=>res.json(await getFinancialDashboard())));
saasFinanceRouter.get("/charges",safe(async(req,res)=>{const q=z.object({tenantId:z.coerce.number().int().positive().optional(),status:z.enum(["DRAFT","ISSUING","OPEN","OVERDUE","PAID","CANCELED","FAILED"]).optional(),type:z.enum(["MONTHLY","IMPLEMENTATION","AD_HOC"]).optional(),provider:providerSchema.optional(),paymentMethod:methodSchema.optional(),from:date.optional(),to:date.optional(),limit:z.coerce.number().int().min(1).max(500).optional()}).parse(req.query);res.json(await listCharges(q));}));
saasFinanceRouter.post("/charges/monthly",safe(async(req,res)=>{const d=chargeCommon.extend({tenantId:z.coerce.number().int().positive(),competence:z.string().regex(/^\d{4}-\d{2}$/)}).parse(req.body);const charge=await createMonthlyCharge(d.tenantId,d.competence,req.auth!.userId,{issue:d.issue,sendEmailAfterIssue:chargeEmailPreference(d)});await writeAudit(req,"CREATE","financial_charge",charge.id,undefined,{type:"MONTHLY",tenantId:d.tenantId,competence:d.competence,provider:charge.provider,paymentMethod:charge.requested_payment_method});res.status(charge.alreadyExists?200:201).json(charge);}));
saasFinanceRouter.post("/charges/implementation",safe(async(req,res)=>{const d=chargeCommon.extend({tenantId:z.coerce.number().int().positive(),amount:z.coerce.number().positive(),dueDate:date,description:z.string().trim().max(255).optional()}).parse(req.body);const charge=await createImplementationCharge({...d,sendEmailAfterIssue:chargeEmailPreference(d),actorUserId:req.auth!.userId});await writeAudit(req,"CREATE","financial_charge",charge.id,undefined,{type:"IMPLEMENTATION",tenantId:d.tenantId,amount:d.amount,dueDate:d.dueDate,provider:charge.provider,paymentMethod:charge.requested_payment_method});res.status(201).json(charge);}));
saasFinanceRouter.post("/charges/ad-hoc",safe(async(req,res)=>{const payerSchema=z.object({personType:z.enum(["PF","PJ"]),name:z.string().trim().min(2).max(190),document:z.string().trim().min(11).max(20),email:z.string().email().optional().nullable(),phone:z.string().max(30).optional().nullable(),zipCode:z.string().max(12).optional().nullable(),street:z.string().max(190).optional().nullable(),number:z.string().max(30).optional().nullable(),complement:z.string().max(120).optional().nullable(),district:z.string().max(120).optional().nullable(),city:z.string().max(120).optional().nullable(),state:z.string().max(2).optional().nullable()});const d=chargeCommon.extend({payerSource:z.enum(["TENANT","EXTERNAL"]),tenantId:z.coerce.number().int().positive().optional().nullable(),payer:payerSchema.optional(),amount:z.coerce.number().positive(),dueDate:date,description:z.string().trim().min(2).max(255),provider:providerSchema.optional(),paymentMethod:methodSchema.optional()}).refine(v=>Boolean(v.provider)===Boolean(v.paymentMethod),"Informe provedor e método juntos.").refine(v=>v.payerSource!=="TENANT"||Boolean(v.tenantId),"Selecione o Cliente SaaS.").refine(v=>v.payerSource!=="EXTERNAL"||(!v.tenantId&&Boolean(v.payer)),"Pagador avulso exige dados próprios e não pode estar vinculado a tenant.").parse(req.body);const charge=await createAdHocCharge({...d,sendEmailAfterIssue:chargeEmailPreference(d),actorUserId:req.auth!.userId});await writeAudit(req,"CREATE","financial_charge",charge.id,undefined,{type:"AD_HOC",tenantId:d.tenantId||null,payerSource:d.payerSource,amount:d.amount,dueDate:d.dueDate,provider:charge.provider,paymentMethod:charge.requested_payment_method});res.status(201).json(charge);}));
saasFinanceRouter.get("/charges/:id",safe(async(req,res)=>res.json(await getCharge(id(req.params.id)))));
saasFinanceRouter.get("/charges/:id/pdf",safe(async(req,res)=>{const chargeId=id(req.params.id);const pdf=await getChargePdf(chargeId);res.setHeader("Content-Type","application/pdf");res.setHeader("Content-Disposition",`inline; filename=boleto-${chargeId}.pdf`);res.send(pdf);}));
saasFinanceRouter.post("/charges/:id/issue",safe(async(req,res)=>res.json(await issueCharge(id(req.params.id),req.auth!.userId))));
saasFinanceRouter.post("/charges/:id/cancel",safe(async(req,res)=>{const chargeId=id(req.params.id);const d=z.object({reason:z.string().trim().min(2).max(100).optional()}).parse(req.body||{});const charge=await cancelCharge(chargeId,req.auth!.userId,d.reason||"SOLICITACAO_ADMIN");await writeAudit(req,"CANCEL","financial_charge",chargeId);res.json(charge);}));
saasFinanceRouter.post("/charges/:id/reconcile",safe(async(req,res)=>res.json(await reconcileCharge(id(req.params.id),req.auth!.userId))));
saasFinanceRouter.post("/charges/:id/manual-payment",safe(async(req,res)=>{const chargeId=id(req.params.id);const d=z.object({paidAt:z.string().datetime().optional()}).parse(req.body||{});const charge=await recordManualPayment(chargeId,req.auth!.userId,d.paidAt);await writeAudit(req,"MANUAL_PAYMENT","financial_charge",chargeId);res.json(charge);}));
saasFinanceRouter.get("/charges/:id/deliveries",safe(async(req,res)=>res.json(await listChargeDeliveries(id(req.params.id)))));
const resendChargeEmail=safe(async(req,res)=>{const chargeId=id(req.params.id);const d=z.object({to:z.string().email().optional(),cc:z.string().email().optional().nullable()}).parse(req.body||{});const delivery=await sendFinancialChargeEmail({chargeId,deliveryType:"MANUAL",actorUserId:req.auth!.userId,to:d.to,cc:d.cc});await writeAudit(req,"SEND_EMAIL","financial_charge",chargeId,undefined,{to:delivery.to,cc:delivery.cc,deliveryId:delivery.id});res.status(201).json(delivery);});
saasFinanceRouter.post("/charges/:id/email",resendChargeEmail);
saasFinanceRouter.post("/charges/:id/send-email",resendChargeEmail);

saasFinanceRouter.get("/tenants/:id/profile",safe(async(req,res)=>{const tenantId=id(req.params.id);res.json({profile:await getBillingProfile(tenantId),access:await getTenantFinancialAccess(tenantId),implementation:await getImplementationSuggestion(tenantId),exceptions:await listFinancialExceptions(tenantId)});}));
saasFinanceRouter.put("/tenants/:id/profile",safe(async(req,res)=>{const tenantId=id(req.params.id);const nullableText=z.string().trim().max(190).nullable().optional();const d=z.object({dueDay:z.union([z.literal(5),z.literal(10),z.literal(15)]),autoBlockEnabled:z.boolean(),autoMonthlyEnabled:z.boolean(),billingLegalName:nullableText,billingTradeName:nullableText,billingDocument:z.string().max(20).nullable().optional(),billingEmail:z.string().email().nullable().optional().or(z.literal("")),billingPhone:z.string().max(30).nullable().optional(),financialContactName:nullableText,financialContactDocument:z.string().max(20).nullable().optional(),financialContactEmail:z.string().email().nullable().optional().or(z.literal("")),financialContactPhone:z.string().max(30).nullable().optional(),billingZipCode:z.string().max(12).nullable().optional(),billingStreet:nullableText,billingNumber:z.string().max(30).nullable().optional(),billingComplement:z.string().max(120).nullable().optional(),billingDistrict:z.string().max(120).nullable().optional(),billingCity:z.string().max(120).nullable().optional(),billingState:z.string().max(2).nullable().optional(),autoEmailCharges:z.boolean().optional().default(true)}).parse(req.body);const profile=await updateBillingProfile(tenantId,d,req.auth!.userId);await writeAudit(req,"UPDATE","saas_billing_profile",tenantId,undefined,d);res.json(profile);}));
saasFinanceRouter.post("/tenants/:id/access-exceptions",safe(async(req,res)=>{const tenantId=id(req.params.id);const d=z.object({chargeId:z.coerce.number().int().positive().nullable().optional(),presetDays:z.union([z.literal(5),z.literal(10),z.literal(30)]).optional(),customEndDate:date.optional(),reason:z.string().trim().min(3).max(500)}).refine(v=>Boolean(v.presetDays)!==Boolean(v.customEndDate),"Informe presetDays ou customEndDate.").parse(req.body);const endsAt=d.customEndDate?`${d.customEndDate}T23:59:59-03:00`:exceptionEndFromPreset(new Date().toISOString(),d.presetDays!);const created=await grantFinancialException({tenantId,chargeId:d.chargeId||null,endsAt,reason:d.reason,actorUserId:req.auth!.userId});await writeAudit(req,"CREATE","financial_access_exception",created.id,undefined,{tenantId,chargeId:d.chargeId||null,endsAt,reason:d.reason});res.status(201).json(created);}));
saasFinanceRouter.delete("/access-exceptions/:id",safe(async(req,res)=>{const exceptionId=id(req.params.id);await revokeFinancialException(exceptionId,req.auth!.userId);await writeAudit(req,"REVOKE","financial_access_exception",exceptionId);res.json({ok:true});}));
saasFinanceRouter.get("/access-exceptions",safe(async(req,res)=>{const tenantId=req.query.tenantId?id(req.query.tenantId):undefined;res.json(await listFinancialExceptions(tenantId));}));
saasFinanceRouter.get("/receipts",safe(async(req,res)=>{const q=z.object({tenantId:z.coerce.number().int().positive().optional(),provider:providerSchema.optional(),paymentMethod:z.enum(["PIX","BOLETO","OTHER","MANUAL"]).optional(),from:date.optional(),to:date.optional(),limit:z.coerce.number().int().min(1).max(500).optional()}).parse(req.query);res.json(await listReceipts(q));}));
saasFinanceRouter.get("/events",safe(async(req,res)=>{const q=z.object({tenantId:z.coerce.number().int().positive().optional(),chargeId:z.coerce.number().int().positive().optional(),provider:providerSchema.optional(),limit:z.coerce.number().int().min(1).max(500).optional()}).parse(req.query);res.json(await listFinancialEvents(q));}));
saasFinanceRouter.get("/reports/charges.csv",safe(async(req,res)=>{
  const q=z.object({tenantId:z.coerce.number().int().positive().optional(),status:z.enum(["DRAFT","ISSUING","OPEN","OVERDUE","PAID","CANCELED","FAILED"]).optional(),type:z.enum(["MONTHLY","IMPLEMENTATION","AD_HOC"]).optional(),provider:providerSchema.optional(),paymentMethod:methodSchema.optional(),from:date.optional(),to:date.optional()}).parse(req.query);
  const rows=await listCharges({...q,limit:500});
  sendCsv(res,"cobrancas-financeiro.csv",csv(["ID","Origem do pagador","Pagador","Documento","E-mail","Cliente SaaS","Tipo","Descrição","Provedor","Método","Valor","Vencimento","Status","Último envio","ID no provedor"],rows.map((r:any)=>[r.id,r.payer_source,r.payer_name,r.payer_document,r.payer_email||"",r.tenant_name||"",r.type,r.description,r.provider,r.requested_payment_method,r.amount,r.due_date,r.status,r.last_delivery_status||"",r.provider_charge_id||""])));
}));
saasFinanceRouter.get("/reports/receipts.csv",safe(async(req,res)=>{
  const q=z.object({tenantId:z.coerce.number().int().positive().optional(),provider:providerSchema.optional(),paymentMethod:z.enum(["PIX","BOLETO","OTHER","MANUAL"]).optional(),from:date.optional(),to:date.optional()}).parse(req.query);
  const rows=await listReceipts({...q,limit:500});
  sendCsv(res,"recebimentos-financeiro.csv",csv(["ID","Pagador","Documento","Cliente SaaS","Cobrança","Provedor","Método solicitado","Método confirmado","Bruto","Tarifa","Líquido","Pago em","ID no provedor"],rows.map((r:any)=>[r.id,r.payer_name||r.tenant_name||"",r.payer_document||"",r.tenant_name||"",r.description,r.provider,r.requested_payment_method,r.payment_method,r.amount,r.provider_fee??"",r.net_amount??"",r.paid_at,r.provider_payment_id||""])));
}));

saasFinanceRouter.get("/providers",safe(async(_req,res)=>res.json(await getFinancialProviderSettings())));
saasFinanceRouter.put("/providers/default",safe(async(req,res)=>{const d=z.object({provider:providerSchema,method:methodSchema}).parse(req.body);const result=await updateFinancialProviderSettings(d,req.auth!.userId);await writeAudit(req,"UPDATE","financial_provider_default",null,undefined,d);res.json(result);}));
saasFinanceRouter.post("/providers/:provider/test",safe(async(req,res)=>{const provider=providerSchema.parse(String(req.params.provider).toUpperCase());const result=await testPaymentProvider(provider);await writeAudit(req,"PROVIDER_CONNECTION_TEST","saas_finance",null,undefined,{provider,ok:true});res.json(result);}));
saasFinanceRouter.put("/providers/:provider/webhook",safe(async(req,res)=>{const provider=providerSchema.parse(String(req.params.provider).toUpperCase());const settings=await getFinancialProviderSettings();const current=settings.providers.find((x:any)=>x.code===provider);const d=z.object({url:z.string().url().optional()}).parse(req.body||{});const url=d.url||current?.webhookUrl;if(!url)throw Object.assign(new Error("Informe uma URL HTTPS de webhook no servidor ou na solicitação."),{status:400,code:"WEBHOOK_URL_MISSING"});const result=await configurePaymentProviderWebhook(provider,url);await writeAudit(req,"PROVIDER_WEBHOOK_CONFIGURED","saas_finance",null,undefined,{provider,url});res.json(result);}));
