import {featureGate} from "../middlewares/commercial-access.js";
import { Router } from "express";
import bcrypt from "bcryptjs";
import { z } from "zod";
import { pool } from "../db/pool.js";
import { authMiddleware } from "../middlewares/auth.js";
import { requireRole } from "../middlewares/require-role.js";
import { permissionsSchema,defaultSupervisorPermissions,readJson,csvCell } from "../services/commercial-rules.js";
import { safe } from "./saas-commercial.routes.js";
import { writeAudit } from "../utils/audit.js";
export const teamRouter=Router();teamRouter.use(authMiddleware,requireRole("TENANT_ADMIN"));
teamRouter.get("/",safe(async(req,res)=>{const [rows]=await pool.query<any[]>("SELECT u.id,u.name,u.email,u.company_id,u.active,p.permissions_json FROM users u LEFT JOIN user_permissions p ON p.user_id=u.id AND p.tenant_id=u.tenant_id WHERE u.tenant_id=? AND u.role='SUPERVISOR' ORDER BY u.name",[req.auth!.tenantId]);res.json(rows.map(r=>({...r,permissions:readJson(r.permissions_json,defaultSupervisorPermissions)})));}));
const teamSchema=z.object({name:z.string().trim().min(2).max(160),email:z.string().email().max(190),password:z.string().min(8).max(128).optional(),active:z.boolean(),permissions:permissionsSchema});
for(const method of ["post","put"] as const)teamRouter[method](method==="post"?"/":"/:id",safe(async(req,res)=>{const d=teamSchema.parse(req.body);if(method==="post"&&!d.password)return res.status(400).json({message:"Informe a senha inicial (mínimo 8 caracteres)."});const conn=await pool.getConnection();let id=Number(req.params.id);try{await conn.beginTransaction();if(method==="post"){const [r]=await conn.query<any>("INSERT INTO users(tenant_id,company_id,name,email,password_hash,role,active,created_at,updated_at) VALUES(?,?,?,?,?,'SUPERVISOR',?,NOW(),NOW())",[req.auth!.tenantId,req.auth!.companyId,d.name,d.email,await bcrypt.hash(d.password!,10),d.active]);id=r.insertId;}else{const [r]=await conn.query<any>("UPDATE users SET name=?,email=?,active=?,updated_at=NOW() WHERE id=? AND tenant_id=? AND role='SUPERVISOR'",[d.name,d.email,d.active,id,req.auth!.tenantId]);if(!r.affectedRows)throw Object.assign(new Error("Supervisor não encontrado."),{status:404});if(d.password)await conn.query("UPDATE users SET password_hash=? WHERE id=? AND tenant_id=?",[await bcrypt.hash(d.password,10),id,req.auth!.tenantId]);}await conn.query("INSERT INTO user_permissions(tenant_id,user_id,permissions_json) VALUES(?,?,?) ON DUPLICATE KEY UPDATE permissions_json=VALUES(permissions_json)",[req.auth!.tenantId,id,JSON.stringify(d.permissions)]);await conn.commit();await writeAudit(req,method==="post"?"CREATE":"UPDATE","supervisor",id,undefined,{...d,password:d.password?"***":undefined});res.json({id});}catch(e){await conn.rollback();throw e;}finally{conn.release();}}));
export const auditRouter=Router();auditRouter.use(authMiddleware,requireRole("TENANT_ADMIN","RH","SUPERVISOR"));
export async function auditList(req:any,res:any,global=false){const q=z.object({page:z.coerce.number().int().min(1).default(1),userId:z.coerce.number().int().positive().optional(),tenantId:z.coerce.number().int().positive().optional(),start:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),end:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),format:z.enum(["json","csv"]).default("json")}).parse(req.query);const where:string[]=[],args:any[]=[];if(!global){where.push("a.tenant_id=?");args.push(req.auth.tenantId);}else if(q.tenantId){where.push("a.tenant_id=?");args.push(q.tenantId);}if(q.userId){where.push("a.user_id=?");args.push(q.userId);}if(q.start){where.push("a.created_at>=?");args.push(q.start);}if(q.end){where.push("a.created_at<DATE_ADD(?,INTERVAL 1 DAY)");args.push(q.end);}const clause=where.length?"WHERE "+where.join(" AND "):"";const [count]=await pool.query<any[]>(`SELECT COUNT(*) AS total FROM audit_logs a ${clause}`,args);const limit=q.format==="csv"?10000:50;const [rows]=await pool.query<any[]>(`SELECT a.id,a.tenant_id,t.name AS tenant_name,u.name AS user_name,a.action,a.entity_type,a.entity_id,a.created_at,a.ip_address,a.after_data FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id LEFT JOIN tenants t ON t.id=a.tenant_id ${clause} ORDER BY a.id DESC LIMIT ? OFFSET ?`,[...args,limit,q.format==="csv"?0:(q.page-1)*50]);res.setHeader("Cache-Control","no-store");if(q.format==="csv"){const keys=["id","tenant_name","user_name","action","entity_type","entity_id","created_at","ip_address"];res.setHeader("Content-Disposition",'attachment; filename="auditoria.csv"');res.type("text/csv").send("\uFEFF"+[keys.join(";"),...rows.map(r=>keys.map(k=>csvCell(r[k])).join(";"))].join("\r\n"));}else res.json({items:rows,total:Number(count[0].total),page:q.page,pages:Math.max(1,Math.ceil(Number(count[0].total)/50))});}
auditRouter.get("/",featureGate("logs"),safe((req,res)=>auditList(req,res)));
