import {featureGate} from "../middlewares/commercial-access.js";
import {Router} from "express";
import bcrypt from "bcryptjs";
import {z} from "zod";
import ExcelJS from "exceljs";
import PDFDocument from "pdfkit";
import {pool} from "../db/pool.js";
import {authMiddleware} from "../middlewares/auth.js";
import {requireRole} from "../middlewares/require-role.js";
import {permissionsSchema,denyAllSupervisorPermissions,sensitivePermissionsSchema,readJson,csvCell} from "../services/commercial-rules.js";
import {safe} from "./saas-commercial.routes.js";
import {writeAudit} from "../utils/audit.js";

export const teamRouter=Router();
teamRouter.use(authMiddleware,requireRole("TENANT_ADMIN"));
teamRouter.get("/",safe(async(req,res)=>{
  const [rows]=await pool.query<any[]>("SELECT u.id,u.name,u.email,u.company_id,u.active,p.permissions_json,p.sensitive_permissions_json FROM users u LEFT JOIN user_permissions p ON p.user_id=u.id AND p.tenant_id=u.tenant_id WHERE u.tenant_id=? AND u.role='SUPERVISOR' ORDER BY u.name",[req.auth!.tenantId]);
  res.json(rows.map(r=>({...r,permissions:r.permissions_json?readJson(r.permissions_json,denyAllSupervisorPermissions):denyAllSupervisorPermissions,sensitivePermissions:readJson(r.sensitive_permissions_json,{})})));
}));
const teamSchema=z.object({name:z.string().trim().min(2).max(160),email:z.string().email().max(190),password:z.string().min(8).max(128).optional(),active:z.boolean(),permissions:permissionsSchema,sensitivePermissions:sensitivePermissionsSchema.default({})});
for(const method of ["post","put"] as const)teamRouter[method](method==="post"?"/":"/:id",safe(async(req,res)=>{
  const d=teamSchema.parse(req.body);if(method==="post"&&!d.password)return res.status(400).json({message:"Informe a senha inicial (mínimo 8 caracteres)."});
  const conn=await pool.getConnection();let id=Number(req.params.id);
  try{await conn.beginTransaction();
    if(method==="post"){const [r]=await conn.query<any>("INSERT INTO users(tenant_id,company_id,name,email,password_hash,role,active,created_at,updated_at) VALUES(?,?,?,?,?,'SUPERVISOR',?,NOW(),NOW())",[req.auth!.tenantId,req.auth!.companyId,d.name,d.email,await bcrypt.hash(d.password!,10),d.active]);id=r.insertId;}
    else{const [r]=await conn.query<any>("UPDATE users SET name=?,email=?,active=?,updated_at=NOW() WHERE id=? AND tenant_id=? AND role='SUPERVISOR'",[d.name,d.email,d.active,id,req.auth!.tenantId]);if(!r.affectedRows)throw Object.assign(new Error("Supervisor não encontrado."),{status:404});if(d.password)await conn.query("UPDATE users SET password_hash=? WHERE id=? AND tenant_id=?",[await bcrypt.hash(d.password,10),id,req.auth!.tenantId]);}
    await conn.query("INSERT INTO user_permissions(tenant_id,user_id,permissions_json,sensitive_permissions_json) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE permissions_json=VALUES(permissions_json),sensitive_permissions_json=VALUES(sensitive_permissions_json)",[req.auth!.tenantId,id,JSON.stringify(d.permissions),JSON.stringify(d.sensitivePermissions)]);
    await conn.commit();await writeAudit(req,method==="post"?"CREATE":"UPDATE","supervisor",id,undefined,{...d,password:d.password?"***":undefined});res.json({id});
  }catch(e){await conn.rollback();throw e;}finally{conn.release();}
}));

export const auditRouter=Router();
auditRouter.use(authMiddleware,requireRole("TENANT_ADMIN","RH","SUPERVISOR"));
const auditQuery=z.object({page:z.coerce.number().int().min(1).default(1),userId:z.coerce.number().int().positive().optional(),tenantId:z.coerce.number().int().positive().optional(),companyId:z.coerce.number().int().positive().optional(),start:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),end:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),range:z.enum(["24h","7d","30d","90d"]).optional(),module:z.string().max(100).optional(),action:z.string().max(100).optional(),result:z.enum(["SUCCESS","ERROR"]).optional(),entity:z.string().max(100).optional(),format:z.enum(["json","csv","xlsx","pdf"]).default("json")});
function auditWhere(req:any,global:boolean,q:z.infer<typeof auditQuery>){const where:string[]=[],args:any[]=[];if(!global){where.push("a.tenant_id=?");args.push(req.auth.tenantId);}else if(q.tenantId){where.push("a.tenant_id=?");args.push(q.tenantId);}if(q.companyId){where.push("a.company_id=?");args.push(q.companyId);}if(q.userId){where.push("a.user_id=?");args.push(q.userId);}if(q.start){where.push("a.created_at>=?");args.push(q.start);}if(q.end){where.push("a.created_at<DATE_ADD(?,INTERVAL 1 DAY)");args.push(q.end);}if(q.range){const hours={"24h":24,"7d":168,"30d":720,"90d":2160}[q.range];where.push("a.created_at>=DATE_SUB(NOW(),INTERVAL ? HOUR)");args.push(hours);}if(q.module){where.push("a.module=?");args.push(q.module);}if(q.action){where.push("a.action=?");args.push(q.action);}if(q.result){where.push("a.result=?");args.push(q.result);}if(q.entity){where.push("a.entity_type=?");args.push(q.entity);}return {clause:where.length?"WHERE "+where.join(" AND "):"",args};}
function auditSelect(){return `SELECT a.id,a.tenant_id,t.name AS tenant_name,a.company_id,c.legal_name AS company_name,a.user_id,COALESCE(a.executor_name,u.name) AS user_name,COALESCE(a.executor_email,u.email) AS user_email,a.executor_role,a.module,a.action,a.entity_type,a.entity_id,a.result,a.created_at,a.ip_address,a.user_agent,a.before_data,a.after_data,a.details FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id LEFT JOIN tenants t ON t.id=a.tenant_id LEFT JOIN companies c ON c.id=a.company_id`;}
function auditCsv(rows:any[]){const keys=["id","tenant_name","company_name","user_name","user_email","executor_role","module","action","entity_type","entity_id","result","created_at","ip_address"];return "\uFEFF"+[keys.join(";"),...rows.map(r=>keys.map(k=>csvCell(r[k])).join(";"))].join("\r\n");}
async function auditXlsx(rows:any[]){const wb=new ExcelJS.Workbook(),ws=wb.addWorksheet("Auditoria");ws.columns=[{header:"ID",key:"id",width:10},{header:"Cliente",key:"tenant_name",width:24},{header:"Empresa",key:"company_name",width:28},{header:"Usuário",key:"user_name",width:24},{header:"E-mail",key:"user_email",width:28},{header:"Perfil",key:"executor_role",width:16},{header:"Módulo",key:"module",width:18},{header:"Ação",key:"action",width:26},{header:"Entidade",key:"entity_type",width:18},{header:"ID entidade",key:"entity_id",width:12},{header:"Resultado",key:"result",width:12},{header:"Data/hora",key:"created_at",width:22},{header:"IP",key:"ip_address",width:18}];for(const r of rows){const safe:any={};for(const col of ws.columns as any[]) {let v=r[col.key];if(typeof v==="string"&&/^[=+\-@]/.test(v))v="'"+v;safe[col.key]=v;}ws.addRow(safe);}ws.getRow(1).font={bold:true};ws.views=[{state:"frozen",ySplit:1}];ws.autoFilter={from:"A1",to:"M1"};return Buffer.from(await wb.xlsx.writeBuffer());}
async function auditPdf(rows:any[],filters:any){return await new Promise<Buffer>((resolve,reject)=>{const doc=new PDFDocument({size:"A4",margin:36}),chunks:Buffer[]=[];doc.on("data",d=>chunks.push(d));doc.on("end",()=>resolve(Buffer.concat(chunks)));doc.on("error",reject);doc.fontSize(18).text("PONTO CERTO — Auditoria de Usuários");doc.moveDown(.4).fontSize(9).text(`Gerado em: ${new Date().toLocaleString("pt-BR")} | Filtros: ${JSON.stringify(filters)}`);doc.moveDown();for(const r of rows){doc.fontSize(8).text(`${r.created_at} | ${r.result} | ${r.tenant_name||""} | ${r.company_name||""} | ${r.user_name||"Sistema"} | ${r.module||""} | ${r.action} | ${r.entity_type}${r.entity_id?` #${r.entity_id}`:""}`);doc.moveDown(.25);}doc.end();});}
export async function auditList(req:any,res:any,global=false){const q=auditQuery.parse(req.query),{clause,args}=auditWhere(req,global,q);const [count]=await pool.query<any[]>(`SELECT COUNT(*) AS total FROM audit_logs a ${clause}`,args);const exportMode=q.format!=="json",limit=exportMode?10000:50;const [rows]=await pool.query<any[]>(`${auditSelect()} ${clause} ORDER BY a.id DESC LIMIT ? OFFSET ?`,[...args,limit,exportMode?0:(q.page-1)*50]);res.setHeader("Cache-Control","no-store");if(q.format==="csv"){res.setHeader("Content-Disposition",'attachment; filename="auditoria.csv"');return res.type("text/csv").send(auditCsv(rows));}if(q.format==="xlsx"){res.setHeader("Content-Disposition",'attachment; filename="auditoria.xlsx"');return res.type("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet").send(await auditXlsx(rows));}if(q.format==="pdf"){res.setHeader("Content-Disposition",'attachment; filename="auditoria.pdf"');return res.type("application/pdf").send(await auditPdf(rows,q));}res.json({items:rows,total:Number(count[0].total),page:q.page,pages:Math.max(1,Math.ceil(Number(count[0].total)/50))});}
auditRouter.get("/",featureGate("audit"),safe((req,res)=>auditList(req,res)));
