import {useEffect,useState} from "react";
import {api} from "../api";
import {apiMessage,brDate} from "../utils";
import {PasswordPage} from "./PasswordPage";

const money=(v:unknown)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

export function BillingBlockedPage({user,logout,onRetry}:{user:any;logout:()=>void;onRetry:()=>Promise<void>}){
  const isAdmin=user?.role==="TENANT_ADMIN";
  const [data,setData]=useState<any>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[password,setPassword]=useState(false),[copied,setCopied]=useState<number|null>(null);
  async function load(){if(!isAdmin)return;setError("");try{const r=await api.get("/billing/self/status");setData(r.data);if(!r.data?.blocked)await onRetry();}catch(e){setError(apiMessage(e));}}
  useEffect(()=>{void load();if(!isAdmin)return;const timer=setInterval(()=>void load(),20000);return()=>clearInterval(timer);},[isAdmin]);
  async function retry(){setBusy(true);try{await onRetry();if(isAdmin)await load();}finally{setBusy(false);}}
  async function copyPix(id:number,text:string){try{await navigator.clipboard.writeText(text);setCopied(id);setTimeout(()=>setCopied(null),2500);}catch{setError("Não foi possível copiar o Pix automaticamente. Selecione o código e copie manualmente.");}}
  async function boleto(id:number){try{const {data}=await api.get(`/billing/self/charges/${id}/pdf`,{responseType:"blob"});const href=URL.createObjectURL(data);const a=document.createElement("a");a.href=href;a.download=`boleto-${id}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(href),1000);}catch(e){setError(apiMessage(e));}}
  if(password)return <main className="billing-blocked-shell"><section className="billing-blocked-card password"><button className="ghost" onClick={()=>setPassword(false)}>← Voltar</button><PasswordPage/></section></main>;
  return <main className="billing-blocked-shell"><section className="billing-blocked-card"><div className="billing-blocked-brand"><img src="/brand/logo.png" alt="Ponto Certo"/><span>Pendência financeira</span></div><div className="billing-blocked-heading"><div className="billing-lock" aria-hidden="true">!</div><div><h1>Acesso temporariamente suspenso</h1><p>{isAdmin?"Identificamos uma cobrança que ultrapassou o prazo de tolerância. O acesso é liberado automaticamente após a confirmação do pagamento.":"O acesso da organização está temporariamente indisponível por uma pendência financeira. Procure o administrador da sua empresa."}</p></div></div>{error&&<div className="form-error" role="alert">{error}</div>}{isAdmin&&<div className="billing-charge-list">{!data?<p>Carregando cobranças…</p>:data.blockingCharges?.map((c:any)=><article key={c.id} className="billing-charge-card"><div className="billing-charge-main"><span>{c.description}</span><strong>{money(c.amount)}</strong><small>Vencimento {brDate(c.dueDate)} · bloqueio após tolerância em {brDate(c.blockAt)}</small></div>{c.pixQrDataUrl&&<img className="billing-qr" src={c.pixQrDataUrl} alt="QR Code Pix"/>}<div className="billing-payment-actions">{c.pixCopyPaste&&<><label>Pix copia e cola<textarea readOnly rows={3} value={c.pixCopyPaste}/></label><button className="primary" onClick={()=>copyPix(c.id,c.pixCopyPaste)}>{copied===c.id?"Pix copiado":"Copiar Pix"}</button></>} {c.providerPdfUrl&&<button className="ghost" onClick={()=>boleto(c.id)}>Baixar boleto</button>}{c.providerPaymentUrl&&<a className="ghost" href={c.providerPaymentUrl} target="_blank" rel="noreferrer">Abrir pagamento</a>}</div></article>)}{data?.globalException&&<div className="info-box">Seu acesso possui uma liberação administrativa válida até {brDate(data.globalException.endsAt)}.</div>}</div>}<div className="billing-blocked-footer"><button className="primary" disabled={busy} onClick={retry}>{busy?"Verificando…":"Já paguei · verificar novamente"}</button><button className="ghost" onClick={()=>setPassword(true)}>Alterar senha</button><button className="ghost" onClick={logout}>Sair da conta</button></div><p className="billing-auto-note">A confirmação do pagamento é processada pelo provedor financeiro da cobrança e conciliada automaticamente pelo Ponto Certo. Não é necessário enviar comprovante para a liberação automática.</p></section></main>;
}
