import {useState} from "react";
import {api} from "../api";
import {apiMessage} from "../utils";
import {Icon} from "../components/Icon";
import {Field,SaveForm,ResourceState,useResource} from "./CommercialUi";

const connectionLabel=(status:string)=>status==="SUCCESS"?"Conectado":status==="ERROR"?"Falha na conexão":"Não testado";
const connectionClass=(status:string)=>status==="SUCCESS"?"status-active":status==="ERROR"?"status-error":"status-draft";
const dateTime=(value:any)=>value?new Date(value).toLocaleString("pt-BR"):"—";

export function SaasEmail(){
  const r=useResource("/saas/settings/email"),[form,setForm]=useState<any>(null),[testing,setTesting]=useState(false),[testError,setTestError]=useState("");
  const d=form||r.data;
  const change=(protocol:string,key:string,value:any)=>setForm({...d,[protocol]:{...d[protocol],[key]:value}});
  async function testSmtp(){setTesting(true);setTestError("");try{await api.post("/saas/settings/email/test",{});await r.reload();}catch(e){setTestError(apiMessage(e));await r.reload();}finally{setTesting(false);}}
  return <><div className="commercial-heading"><div><span className="commercial-kicker">Infraestrutura</span><h1>Configuração de e-mail</h1><p>Configure o SMTP usado para enviar propostas e contratos. As credenciais ficam criptografadas e nunca retornam pela API.</p></div></div><ResourceState resource={r}>{d&&<>
    <SaveForm onSave={async()=>{await api.put("/saas/settings/email",d);setForm(null);await r.reload();}}><div className="commercial-cards email-cards">{["smtp","pop3"].map(protocol=><section className="card" key={protocol}><div className="commercial-plan-card-head"><div className="commercial-plan-icon"><Icon name="mail" size={20}/></div>{protocol==="smtp"?<span className={`commercial-status ${connectionClass(d.smtp.connection?.status)}`}>{connectionLabel(d.smtp.connection?.status)}</span>:<span className={`commercial-status ${d[protocol].passwordConfigured?"status-active":"status-draft"}`}>{d[protocol].passwordConfigured?"Credencial salva":"Não configurado"}</span>}</div><h2>{protocol.toUpperCase()}</h2><p>{protocol==="smtp"?"Servidor de saída usado no envio comercial do PONTO CERTO.":"Servidor de entrada preservado para funcionalidade futura."}</p><Field label="Servidor"><input value={d[protocol].host??""} onChange={e=>change(protocol,"host",e.target.value)}/></Field><Field label="Porta"><input type="number" min={1} max={65535} value={d[protocol].port??""} onChange={e=>change(protocol,"port",Number(e.target.value))}/></Field><Field label="Segurança"><select value={d[protocol].security||"STARTTLS"} onChange={e=>change(protocol,"security",e.target.value)}><option value="NONE">Sem TLS</option><option value="STARTTLS">STARTTLS / TLS</option><option value="SSL_TLS">SSL/TLS</option></select></Field><Field label="Usuário"><input value={d[protocol].username??""} onChange={e=>change(protocol,"username",e.target.value)}/></Field>{protocol==="smtp"&&<><Field label="Nome do remetente"><input value={d.smtp.senderName??""} onChange={e=>change("smtp","senderName",e.target.value)}/></Field><Field label="E-mail remetente"><input type="email" value={d.smtp.senderEmail??""} onChange={e=>change("smtp","senderEmail",e.target.value)}/></Field></>}<Field label={d[protocol].passwordConfigured?"Nova senha (vazio mantém a salva)":"Senha"}><input type="password" autoComplete="new-password" value={d[protocol].password??""} onChange={e=>change(protocol,"password",e.target.value)}/></Field>{d[protocol].passwordConfigured&&<label className="commercial-danger-check"><input type="checkbox" checked={Boolean(d[protocol].clearPassword)} onChange={e=>change(protocol,"clearPassword",e.target.checked)}/> Remover senha salva</label>}{protocol==="smtp"&&<div className="commercial-email-connection"><strong>{connectionLabel(d.smtp.connection?.status)}</strong><span>{d.smtp.connection?.message||"Conexão SMTP ainda não testada."}</span><small>Último teste: {dateTime(d.smtp.connection?.lastTestAt)}</small></div>}</section>)}</div><div className="commercial-security-note"><span className="commercial-security-dot"/><span><strong>Segurança:</strong> senhas persistidas permanecem criptografadas. POP3 continua desabilitado; somente SMTP é usado para envio comercial.</span></div></SaveForm>
    <section className="commercial-panel commercial-email-test-panel"><div><h2>Teste de conexão SMTP</h2><p>{form?"Existem alterações ainda não salvas. Salve antes de testar.":"Valide autenticação e TLS antes de liberar o envio de propostas e contratos."}</p>{testError&&<p role="alert" className="error">{testError}</p>}</div><button className="primary" disabled={testing||Boolean(form)||!d.smtp.passwordConfigured} onClick={testSmtp}>{testing?"Testando…":"Testar conexão SMTP"}</button></section>
  </>}</ResourceState></>;
}
