import { useEffect, useState, type ReactNode } from "react";
import { api } from "../api";
import { apiMessage } from "../utils";
import { PageSkeleton } from "../components/PageSkeleton";
export const labels:Record<string,string>={whatsapp:"WhatsApp",branches:"Filiais",offline:"Ponto offline",pwa:"PWA iPhone",android:"Android",erp:"Exportação ERP",logs:"Logs"};
export const modules:Record<string,string>={dashboard:"Visão geral",companies:"Empresas",employees:"Funcionários",schedules:"Escalas e jornadas",locations:"Locais",points:"Marcações",occurrences:"Ocorrências",adjustments:"Ajustes",reports:"Relatórios",logs:"Auditoria e logs"};
export const defaults=Object.fromEntries(Object.keys(labels).map(k=>[k,true]));
export const money=(v:unknown)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
export function Field({label,children}:{label:string;children:ReactNode}){return <label className="commercial-field"><span>{label}</span>{children}</label>;}
export function Features({value,onChange,overrides=false}:{value:any;onChange:(v:any)=>void;overrides?:boolean}){return <fieldset className="commercial-features"><legend>{overrides?"Exceções comerciais (padrão do contrato quando não alterado)":"Recursos contratados"}</legend>{Object.entries(labels).map(([k,label])=>overrides?<Field key={k} label={label}><select value={value[k]===undefined?"inherit":String(value[k])} onChange={e=>{const next={...value};if(e.target.value==="inherit")delete next[k];else next[k]=e.target.value==="true";onChange(next);}}><option value="inherit">Usar padrão</option><option value="true">Liberado</option><option value="false">Bloqueado</option></select></Field>:<label key={k}><input type="checkbox" checked={Boolean(value[k])} onChange={e=>onChange({...value,[k]:e.target.checked})}/>{label}</label>)}</fieldset>;}
export function useResource(url:string){const [data,setData]=useState<any>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);async function reload(){setLoading(true);setError("");try{setData((await api.get(url)).data);}catch(e){setError(apiMessage(e));}finally{setLoading(false);}}useEffect(()=>{setData(null);void reload();},[url]);return {data,error,loading,reload};}
export function ResourceState({resource,children}:{resource:ReturnType<typeof useResource>;children:ReactNode}){if(resource.error)return <div className="error-card" role="alert">{resource.error}<button onClick={resource.reload}>Tentar novamente</button></div>;if(!resource.data)return <PageSkeleton/>;return <div aria-busy={resource.loading}>{children}</div>;}
export async function download(url:string,name:string){const {data}=await api.get(url,{responseType:"blob"});const href=URL.createObjectURL(data);const a=document.createElement("a");a.href=href;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(href),1000);}
export function SaveForm({onSave,children,label="Salvar"}:{onSave:()=>Promise<void>;children:ReactNode;label?:string}){const [busy,setBusy]=useState(false),[error,setError]=useState(""),[saved,setSaved]=useState(false);return <form className="commercial-form" aria-busy={busy} onChange={()=>setSaved(false)} onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError("");setSaved(false);try{await onSave();setSaved(true);}catch(err){setError(apiMessage(err));}finally{setBusy(false);}}}><fieldset disabled={busy} className="commercial-form-body">{children}</fieldset>{error&&<p role="alert" className="error">{error}</p>}{saved&&<p role="status">Salvo com sucesso.</p>}<button className="primary" disabled={busy}>{busy?"Salvando…":label}</button></form>;}
