import {useState} from "react";
import {api} from "../api";
import {Icon} from "../components/Icon";
import {Modal} from "../components/Modal";
import {Field,ResourceState,SaveForm,download,money,useResource} from "./CommercialUi";
import {CommercialEmailComposer,CommercialEmailHistory} from "./CommercialEmailComposer";
import {apiMessage} from "../utils";

const labels:Record<string,string>={DRAFT:"Rascunho",GENERATED:"Gerado",SENT:"Enviado",SIGNED:"Assinado",CANCELED:"Cancelado"};
const editable=(c:any)=>({revision:c.revision,contractDate:c.contract_date?.slice(0,10)||"",startDate:c.start_date?.slice(0,10)||null,termMonths:c.term_months==null?null:Number(c.term_months),dueDay:c.due_day==null?null:Number(c.due_day),paymentMethod:c.payment_method||null,adjustmentRule:c.adjustment_rule||null,notes:c.notes||null,forum:c.forum||null,clientRepresentative:c.client_representative||null,pontoCertoRepresentative:c.ponto_certo_representative||null});
const statusClass=(status:string)=>`commercial-status status-${String(status||"").toLowerCase()}`;

export function ContractsPage(){
  const [q,setQ]=useState(""),[status,setStatus]=useState(""),[selected,setSelected]=useState<number|null>(null);
  const params=new URLSearchParams();if(q)params.set("q",q);if(status)params.set("status",status);
  const r=useResource(`/saas/contracts${params.size?`?${params}`:""}`);
  return <><div className="commercial-heading"><div><span className="commercial-kicker">Negociações</span><h1>Contratos</h1><p>Controle contratos originados de propostas aprovadas, revisões, documentos e ativação do cliente após assinatura.</p></div></div><div className="commercial-filters"><Field label="Buscar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Contrato, cliente ou CNPJ"/></Field><Field label="Status"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field></div><ResourceState resource={r}>{r.data?.length?<section className="commercial-panel table-panel"><div className="table-scroll"><table><thead><tr><th>Contrato</th><th>Cliente</th><th>Plano</th><th>Valor</th><th>Início</th><th>Status</th><th>Proposta</th><th>Ações</th></tr></thead><tbody>{r.data.map((c:any)=><tr key={c.id}><td><strong>{c.contract_number}</strong><small>Revisão {c.revision||1}</small></td><td><strong>{c.company_name}</strong><small>{c.cnpj}</small></td><td>{c.plan_name_snapshot}</td><td><strong>{money(c.price_monthly)}</strong></td><td>{c.start_date?.slice(0,10).split("-").reverse().join("/")||"—"}</td><td><span className={statusClass(c.status)}>{labels[c.status]||c.status}</span></td><td>{c.proposal_number}</td><td><button className="secondary compact" onClick={()=>setSelected(c.id)}>Abrir</button></td></tr>)}</tbody></table></div></section>:<div className="commercial-empty"><div className="commercial-empty-icon"><Icon name="contract" size={24}/></div><strong>Nenhum contrato encontrado</strong><p>Gere um contrato a partir de uma proposta aprovada.</p><a className="secondary" href="#saas/proposals">Ir para propostas</a></div>}</ResourceState>{selected&&<ContractDetails id={selected} onClose={()=>setSelected(null)} onChange={r.reload}/>}</>;
}

function ContractDetails({id,onClose,onChange}:{id:number;onClose:()=>void;onChange:()=>Promise<void>}){
  const r=useResource(`/saas/contracts/${id}`),[busy,setBusy]=useState(false),[error,setError]=useState(""),[conversion,setConversion]=useState<any>(null),[edit,setEdit]=useState<any>(null),[emailing,setEmailing]=useState(false);const c=r.data;
  async function act(fn:()=>Promise<unknown>){setBusy(true);setError("");try{await fn();await r.reload();await onChange();}catch(e){setError(apiMessage(e));}finally{setBusy(false);}}
  return <Modal title={c?.contract_number||`Contrato #${id}`} onClose={onClose} wide protectChanges={Boolean(conversion||edit)}><ResourceState resource={r}>{c&&<>
    <div className="commercial-detail-hero"><div><span className={statusClass(c.status)}>{labels[c.status]||c.status}</span><h2>{c.company_name}</h2><p>{c.plan_name_snapshot} · {money(c.price_monthly)}/mês · {c.max_employees} funcionários</p></div><div className="commercial-detail-meta"><span>Origem <strong>{c.proposal_number}</strong></span><span>Revisão <strong>{c.revision}</strong></span></div></div>
    {error&&<p role="alert" className="error">{error}</p>}
    <div className="commercial-actions" aria-busy={busy}>{["docx","pdf"].map(format=><button key={format} disabled={busy||c.status==="CANCELED"} onClick={()=>act(async()=>{const {data}=await api.post(`/saas/contracts/${id}/documents/${format}`,{},{timeout:120000});await download(`/saas/contracts/documents/${data.id}/download`,data.filename);})}>Gerar {format.toUpperCase()}</button>)}{["DRAFT","GENERATED","SENT"].includes(c.status)&&<button className="primary" disabled={busy} onClick={()=>setEmailing(true)}>Enviar por e-mail</button>}{["DRAFT","GENERATED"].includes(c.status)&&<button disabled={busy} onClick={()=>setEdit(editable(c))}>Editar contrato</button>}{c.status==="GENERATED"&&<button onClick={()=>act(()=>api.patch(`/saas/contracts/${id}/status`,{status:"SENT"}))}>Marcar como enviado</button>}{c.status==="SENT"&&<button className="primary" onClick={()=>act(()=>api.patch(`/saas/contracts/${id}/status`,{status:"SIGNED"}))}>Marcar como assinado</button>}{c.status!=="CANCELED"&&c.status!=="SIGNED"&&<button onClick={()=>act(()=>api.patch(`/saas/contracts/${id}/status`,{status:"CANCELED"}))}>Cancelar contrato</button>}{c.status==="SIGNED"&&!c.tenant_id&&<button className="primary" onClick={()=>setConversion({slug:"",adminName:c.responsible_name,adminEmail:c.email,adminPassword:""})}>Criar / ativar cliente SaaS</button>}</div>
    {emailing&&<CommercialEmailComposer kind="contracts" id={id} defaultTo={c.email} defaultSubject={`Contrato PONTO CERTO – ${c.contract_number}`} defaultMessage={`Olá ${c.responsible_name},\n\nSegue em anexo o contrato do PONTO CERTO referente à proposta ${c.proposal_number}.\n\nFicamos à disposição para quaisquer esclarecimentos.\n\nAtenciosamente,\nPONTO CERTO`} onClose={()=>setEmailing(false)} onSent={async()=>{setEmailing(false);await r.reload();await onChange();}}/>}
    {edit&&<section className="commercial-section-card"><h2>Editar dados contratuais</h2><SaveForm label="Salvar revisão" onSave={async()=>{await api.put(`/saas/contracts/${id}`,edit);setEdit(null);await r.reload();await onChange();}}><div className="commercial-grid"><Field label="Data do contrato"><input type="date" required value={edit.contractDate} onChange={e=>setEdit({...edit,contractDate:e.target.value})}/></Field><Field label="Início da vigência"><input type="date" value={edit.startDate||""} onChange={e=>setEdit({...edit,startDate:e.target.value||null})}/></Field><Field label="Prazo (meses)"><input type="number" min={1} value={edit.termMonths||""} onChange={e=>setEdit({...edit,termMonths:e.target.value?Number(e.target.value):null})}/></Field><Field label="Dia do vencimento"><input type="number" min={1} max={31} value={edit.dueDay||""} onChange={e=>setEdit({...edit,dueDay:e.target.value?Number(e.target.value):null})}/></Field><Field label="Forma de pagamento"><input value={edit.paymentMethod||""} onChange={e=>setEdit({...edit,paymentMethod:e.target.value||null})}/></Field><Field label="Regra de reajuste"><input value={edit.adjustmentRule||""} onChange={e=>setEdit({...edit,adjustmentRule:e.target.value||null})}/></Field><Field label="Foro"><input value={edit.forum||""} onChange={e=>setEdit({...edit,forum:e.target.value||null})}/></Field><Field label="Representante da contratante"><input value={edit.clientRepresentative||""} onChange={e=>setEdit({...edit,clientRepresentative:e.target.value||null})}/></Field><Field label="Representante PONTO CERTO"><input value={edit.pontoCertoRepresentative||""} onChange={e=>setEdit({...edit,pontoCertoRepresentative:e.target.value||null})}/></Field></div><Field label="Observações"><textarea rows={4} value={edit.notes||""} onChange={e=>setEdit({...edit,notes:e.target.value||null})}/></Field></SaveForm></section>}
    <section className="commercial-section-card"><h2>Anexar contrato assinado</h2><div className="commercial-upload"><input type="file" accept="application/pdf" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;const form=new FormData();form.append("file",file);await act(()=>api.post(`/saas/contracts/${id}/signed`,form,{headers:{"Content-Type":"multipart/form-data"}}));e.currentTarget.value="";}}/><small>Somente PDF, até 10 MB. O arquivo fica versionado com SHA-256.</small></div></section>
    {conversion&&<section className="commercial-section-card"><h2>Criar acesso Master e ativar cliente</h2><SaveForm label="Ativar cliente SaaS" onSave={async()=>{await api.post(`/saas/contracts/${id}/convert`,conversion);setConversion(null);await r.reload();await onChange();}}><div className="commercial-grid">{Object.entries({slug:"Identificador",adminName:"Nome do Master",adminEmail:"E-mail do Master",adminPassword:"Senha inicial"}).map(([k,l])=><Field key={k} label={l}><input required type={k==="adminPassword"?"password":k==="adminEmail"?"email":"text"} minLength={k==="adminPassword"?8:2} pattern={k==="slug"?"[a-z0-9-]+":undefined} value={conversion[k]} onChange={e=>setConversion({...conversion,[k]:e.target.value})}/></Field>)}</div></SaveForm></section>}
    <h2 className="commercial-section-title">Documentos</h2>{c.documents?.length?<ul className="commercial-document-list">{c.documents.map((d:any)=><li key={d.id}><Icon name="contract" size={16}/><button onClick={()=>download(`/saas/contracts/documents/${d.id}/download`,d.filename)}>{d.filename}</button><span>revisão {d.revision}</span><span>SHA-256 {String(d.sha256).slice(0,12)}…</span></li>)}</ul>:<div className="commercial-empty compact-empty"><p>Nenhum documento gerado.</p></div>}
    <h2 className="commercial-section-title">Contratos assinados</h2>{c.signed?.length?<ul className="commercial-document-list">{c.signed.map((d:any)=><li key={d.id}><Icon name="check" size={16}/><button onClick={()=>download(`/saas/contracts/signed/${d.id}/download`,d.filename)}>{d.filename}</button><span>{d.uploaded_at}</span><span>SHA-256 {String(d.sha256).slice(0,12)}…</span></li>)}</ul>:<div className="commercial-empty compact-empty"><p>Nenhum arquivo assinado anexado.</p></div>}
    <div className="commercial-section-head"><h2 className="commercial-section-title">Envios por e-mail</h2><button className="secondary compact" type="button" onClick={()=>r.reload()}>Atualizar status</button></div><CommercialEmailHistory deliveries={c.deliveries}/>
    <h2 className="commercial-section-title">Histórico</h2>{c.history?.length?<ul className="commercial-history-list">{c.history.map((h:any)=><li key={h.id}><Icon name="audit" size={16}/><span>{h.created_at}</span><strong>{h.executor_name||h.executor_email||"Sistema"}</strong><span>{h.action}</span><span className={statusClass(h.result||"SUCCESS")}>{h.result||"SUCCESS"}</span></li>)}</ul>:<div className="commercial-empty compact-empty"><p>Nenhum evento administrativo registrado.</p></div>}
    {c.tenant_id&&<div className="commercial-settings-intro">Cliente SaaS #{c.tenant_id} já ativado por este contrato.</div>}
  </>}</ResourceState></Modal>;
}
