import {useState} from "react";
import {api} from "../api";
import {apiMessage} from "../utils";
import {Icon} from "../components/Icon";
import {Modal} from "../components/Modal";
import {defaults,Field,Features,SaveForm,ResourceState,useResource,money,download} from "./CommercialUi";

const statuses:Record<string,string>={DRAFT:"Rascunho",SENT:"Enviada",APPROVED:"Aprovada",REJECTED:"Rejeitada",EXPIRED:"Expirada",CONVERTED:"Convertida"};
const input=(p:any)=>({revision:p.revision,companyName:p.company_name,cnpj:p.cnpj,responsibleName:p.responsible_name,email:p.email,phone:p.phone,planId:p.plan_id,maxEmployees:p.max_employees,priceMonthly:Number(p.price_monthly),maxBranches:p.max_branches,features:p.features,implementationDays:p.implementation_days,implementationFee:Number(p.implementation_fee),validUntil:p.valid_until.slice(0,10),notes:p.notes||""});
const statusClass=(status:string)=>`commercial-status status-${status.toLowerCase()}`;

export function ProposalsPage(){
  const plans=useResource("/saas/plans/all"),[form,setForm]=useState<any>(null),[selected,setSelected]=useState<number|null>(null),[filters,setFilters]=useState({q:"",status:"",planId:"",from:"",to:"",expired:false,converted:false});
  const params=new URLSearchParams();if(filters.q)params.set("q",filters.q);if(filters.status)params.set("status",filters.status);if(filters.planId)params.set("planId",filters.planId);if(filters.from)params.set("from",filters.from);if(filters.to)params.set("to",filters.to);if(filters.expired)params.set("expired","1");if(filters.converted)params.set("converted","1");
  const r=useResource(`/saas/proposals${params.size?`?${params}`:""}`);
  const newProposal=()=>setForm({companyName:"",cnpj:"",responsibleName:"",email:"",phone:"",planId:0,maxEmployees:15,priceMonthly:69.9,maxBranches:0,features:{...defaults,whatsapp:false,branches:false},implementationDays:5,implementationFee:250,validUntil:new Date(Date.now()+15*86400000).toISOString().slice(0,10),notes:""});
  return <>
    <div className="commercial-heading"><div><span className="commercial-kicker">Negociações</span><h1>Propostas comerciais</h1><p>Crie, acompanhe e preserve o histórico comercial com snapshot, revisões e documentos PDF/DOCX.</p></div><div className="commercial-heading-actions"><button className="primary" onClick={newProposal}>+ Nova proposta</button></div></div>
    <div className="commercial-filters">
      <Field label="Buscar"><input type="search" value={filters.q} placeholder="Número, empresa ou CNPJ" onChange={e=>setFilters({...filters,q:e.target.value})}/></Field>
      <Field label="Status"><select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">Todos</option>{Object.entries(statuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field>
      <Field label="Plano"><select value={filters.planId} onChange={e=>setFilters({...filters,planId:e.target.value})}><option value="">Todos</option>{plans.data?.map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field>
      <Field label="Emissão inicial"><input type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/></Field>
      <Field label="Emissão final"><input type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></Field>
      <label><input type="checkbox" checked={filters.expired} onChange={e=>setFilters({...filters,expired:e.target.checked})}/> Somente vencidas</label>
      <label><input type="checkbox" checked={filters.converted} onChange={e=>setFilters({...filters,converted:e.target.checked})}/> Somente convertidas</label>
    </div>
    <ResourceState resource={r}>{r.data?.length?<section className="commercial-panel table-panel"><div className="table-scroll"><table><thead><tr><th>Proposta</th><th>Empresa</th><th>Plano</th><th>Mensalidade</th><th>Validade</th><th>Status</th><th>Ações</th></tr></thead><tbody>{r.data.map((p:any)=>{const status=p.converted_tenant_id?"CONVERTED":p.status;return <tr key={p.id}><td><strong>{p.proposal_number||`#${p.id}`}</strong><small>Revisão {p.revision||1}</small></td><td><strong>{p.company_name}</strong><small>{p.cnpj}</small></td><td>{p.plan_name}</td><td><strong>{money(p.price_monthly)}</strong></td><td>{p.valid_until.slice(0,10).split("-").reverse().join("/")}</td><td><span className={statusClass(status)}>{p.converted_tenant_id?"Convertida":statuses[p.status]||p.status}</span></td><td><button className="secondary compact" onClick={()=>setSelected(p.id)}>Abrir</button></td></tr>})}</tbody></table></div></section>:<div className="commercial-empty"><div className="commercial-empty-icon"><Icon name="proposal" size={24}/></div><strong>Nenhuma proposta encontrada</strong><p>Ajuste os filtros ou crie uma nova proposta comercial.</p><button className="primary" onClick={newProposal}>+ Nova proposta</button></div>}</ResourceState>
    {selected&&<ProposalDetails id={selected} onClose={()=>setSelected(null)} onChange={r.reload} onEdit={p=>{setSelected(null);setForm({id:p.id,...input(p)});}}/>}
    {form&&<Modal title={form.id?"Editar proposta":"Nova proposta"} onClose={()=>setForm(null)} wide><SaveForm label="Salvar proposta" onSave={async()=>{const response=form.id?await api.put(`/saas/proposals/${form.id}`,form):await api.post("/saas/proposals",form);setForm(null);await r.reload();setSelected(response.data.id);}}><div className="commercial-settings-intro">Os dados comerciais são congelados no momento da proposta para preservar o histórico, mesmo que o plano seja alterado depois.</div><div className="commercial-grid">{Object.entries({companyName:"Empresa / cliente",cnpj:"CNPJ",responsibleName:"Responsável",email:"E-mail",phone:"Telefone"}).map(([k,l])=><Field key={k} label={l}><input required={k!=="phone"} type={k==="email"?"email":"text"} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></Field>)}<Field label="Plano"><select required value={form.planId||""} onChange={e=>{const p=plans.data.find((p:any)=>p.id===Number(e.target.value));setForm({...form,planId:p.id,maxEmployees:p.max_employees||151,priceMonthly:Number(p.price_monthly)||form.priceMonthly,maxBranches:p.max_branches??null,features:{...defaults,...p.features}});}}><option value="">Selecione o plano</option>{plans.data?.filter((p:any)=>p.active).map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field>{Object.entries({maxEmployees:"Limite de funcionários",priceMonthly:"Mensalidade (R$)",maxBranches:"Limite de filiais (vazio = ilimitado)",implementationDays:"Implantação (dias)",implementationFee:"Valor de implantação (R$)"}).map(([k,l])=><Field key={k} label={l}><input type="number" required={k!=="maxBranches"} min={k==="maxEmployees"?1:k==="priceMonthly"?0.01:0} step={k==="priceMonthly"||k==="implementationFee"?"0.01":"1"} value={form[k]??""} onChange={e=>setForm({...form,[k]:e.target.value===""?null:Number(e.target.value)})}/></Field>)}<Field label="Válida até"><input type="date" required value={form.validUntil} onChange={e=>setForm({...form,validUntil:e.target.value})}/></Field></div><Features value={form.features} onChange={features=>setForm({...form,features})}/><Field label="Observações comerciais"><textarea rows={4} maxLength={6000} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field></SaveForm></Modal>}
  </>;
}

function ProposalDetails({id,onClose,onEdit,onChange}:{id:number;onClose:()=>void;onEdit:(p:any)=>void;onChange:()=>Promise<void>}){
  const r=useResource(`/saas/proposals/${id}`),[busy,setBusy]=useState(false),[error,setError]=useState(""),[contract,setContract]=useState<any>(null);
  async function act(fn:()=>Promise<unknown>){setBusy(true);setError("");try{await fn();await r.reload();await onChange();}catch(e){setError(apiMessage(e));}finally{setBusy(false);}}
  const p=r.data;const today=new Date().toISOString().slice(0,10);
  return <Modal title={`Proposta ${p?.proposal_number||`#${id}`}`} onClose={onClose} wide protectChanges={Boolean(contract)}><ResourceState resource={r}>{p&&<>
    <div className="commercial-detail-hero"><div><span className={statusClass(p.converted_tenant_id?"CONVERTED":p.status)}>{p.converted_tenant_id?"Convertida":statuses[p.status]||p.status}</span><h2>{p.company_name}</h2><p>{p.plan_name} · {money(p.price_monthly)}/mês · {p.max_employees} funcionários</p></div><div className="commercial-detail-meta"><span>Validade <strong>{p.valid_until.slice(0,10).split("-").reverse().join("/")}</strong></span><span>Revisão <strong>{p.revision}</strong></span></div></div>
    {error&&<p role="alert" className="error">{error}</p>}
    <div className="commercial-actions" aria-busy={busy}>{["docx","pdf"].map(format=><button disabled={busy} key={format} onClick={()=>act(async()=>{const {data}=await api.post(`/saas/proposals/${id}/documents/${format}`,{},{timeout:120000});await download(`/saas/proposals/documents/${data.id}/download`,data.filename);})}>{busy?"Aguarde…":`Gerar ${format.toUpperCase()}`}</button>)}{!p.converted_tenant_id&&<><button disabled={busy||!["DRAFT","REJECTED","EXPIRED"].includes(p.status)} onClick={()=>onEdit(p)}>Editar dados</button>{Object.entries(statuses).filter(([s])=>s!==p.status&&s!=="CONVERTED").map(([status,label])=><button disabled={busy} key={status} onClick={()=>act(()=>api.patch(`/saas/proposals/${id}/status`,{status,revision:p.revision}))}>{status==="DRAFT"?"Reabrir rascunho":`Marcar como ${label.toLowerCase()}`}</button>)}{p.status==="APPROVED"&&<button className="primary" disabled={busy} onClick={()=>setContract({contractDate:today,startDate:today,termMonths:12,dueDay:10,paymentMethod:"Boleto / PIX",adjustmentRule:"Reajuste anual conforme índice definido entre as partes",notes:p.notes||"",forum:"Recife/PE",clientRepresentative:p.responsible_name,pontoCertoRepresentative:""})}>Gerar contrato</button>}</>}</div>
    {p.converted_tenant_id&&<div className="commercial-settings-intro">Cliente SaaS #{p.converted_tenant_id} criado com os termos desta negociação.</div>}
    {contract&&<section className="commercial-section-card"><h2>Dados do contrato</h2><SaveForm label="Criar contrato" onSave={async()=>{await api.post(`/saas/contracts/from-proposal/${id}`,contract);setContract(null);location.hash="#saas/contracts";}}><div className="commercial-grid"><Field label="Data do contrato"><input type="date" required value={contract.contractDate} onChange={e=>setContract({...contract,contractDate:e.target.value})}/></Field><Field label="Início da vigência"><input type="date" value={contract.startDate||""} onChange={e=>setContract({...contract,startDate:e.target.value||null})}/></Field><Field label="Prazo (meses)"><input type="number" min="1" value={contract.termMonths||""} onChange={e=>setContract({...contract,termMonths:e.target.value?Number(e.target.value):null})}/></Field><Field label="Dia de vencimento"><input type="number" min="1" max="31" value={contract.dueDay||""} onChange={e=>setContract({...contract,dueDay:e.target.value?Number(e.target.value):null})}/></Field><Field label="Forma de pagamento"><input value={contract.paymentMethod||""} onChange={e=>setContract({...contract,paymentMethod:e.target.value||null})}/></Field><Field label="Regra de reajuste"><input value={contract.adjustmentRule||""} onChange={e=>setContract({...contract,adjustmentRule:e.target.value||null})}/></Field><Field label="Foro"><input value={contract.forum||""} onChange={e=>setContract({...contract,forum:e.target.value||null})}/></Field><Field label="Representante da contratante"><input value={contract.clientRepresentative||""} onChange={e=>setContract({...contract,clientRepresentative:e.target.value||null})}/></Field><Field label="Representante PONTO CERTO"><input value={contract.pontoCertoRepresentative||""} onChange={e=>setContract({...contract,pontoCertoRepresentative:e.target.value||null})}/></Field></div><Field label="Observações"><textarea rows={4} value={contract.notes||""} onChange={e=>setContract({...contract,notes:e.target.value||null})}/></Field></SaveForm></section>}
    <h2 className="commercial-section-title">Documentos armazenados</h2>{!p.documents.length?<div className="commercial-empty compact-empty"><p>Nenhum documento gerado ainda.</p></div>:<ul className="commercial-document-list">{p.documents.map((d:any)=><li key={d.id}><Icon name="proposal" size={16}/><button disabled={busy} onClick={()=>act(()=>download(`/saas/proposals/documents/${d.id}/download`,d.filename))}>{d.filename}</button><span>{d.created_at}</span></li>)}</ul>}
    <h2 className="commercial-section-title">Histórico</h2><ul className="commercial-history-list">{p.history.map((h:any)=><li key={h.id}><Icon name="audit" size={16}/><span>{h.created_at}</span><strong>{h.user_name||"Sistema"}</strong><span>{h.action}</span></li>)}</ul>
  </>}</ResourceState></Modal>;
}
