import {useEffect,useState} from 'react';
import {api} from '../api';
import {PageHeader,Badge,Empty} from '../components/Ui';
import {DataTable} from '../components/DataTable';
import {apiMessage} from '../utils';

export function SaasProductSubscriptions(){
  const [rows,setRows]=useState<any[]>([]),[editing,setEditing]=useState<any>(null),[error,setError]=useState(''),[saving,setSaving]=useState(false);
  const load=async()=>{const {data}=await api.get('/saas/product-subscriptions');setRows(data);};
  useEffect(()=>{void load();},[]);
  async function save(){if(!editing)return;setSaving(true);setError('');try{await api.put(`/saas/product-subscriptions/${editing.id}`,{billingProvider:editing.billingProvider,billingMethod:editing.billingMethod,graceDays:Number(editing.graceDays),autoBlock:Boolean(editing.autoBlock),firstCycleProrataEnabled:Boolean(editing.firstCycleProrataEnabled)});setEditing(null);await load();}catch(e){setError(apiMessage(e));}finally{setSaving(false);}}
  async function grant(id:number,days?:5|10|30){const custom=!days;const endsAt=custom?window.prompt('Data personalizada (AAAA-MM-DD):',''):null;if(custom&&!endsAt)return;const reason=window.prompt('Motivo da liberação temporária:',days?`Liberação temporária +${days} dias`:'Liberação temporária personalizada');if(!reason)return;setError('');try{await api.post(`/saas/product-subscriptions/${id}/access-exception`,days?{days,reason}:{endsAt:`${endsAt}T23:59:59-03:00`,reason});await load();}catch(e){setError(apiMessage(e));}}
  async function revoke(id:number){setError('');try{await api.post(`/saas/product-subscriptions/${id}/revoke-access-exception`);await load();}catch(e){setError(apiMessage(e));}}
  return <><PageHeader title="Assinaturas por Produto" subtitle="Planos, preços, vencimentos e integração operacional de cada produto contratado."/>
    {error&&<div className="commercial-toast error">{error}</div>}
    <div className="panel table-panel">{rows.length===0?<Empty>Nenhuma assinatura de produto cadastrada.</Empty>:<div className="table-wrap"><DataTable><thead><tr><th>Cliente</th><th>Produto</th><th>Plano</th><th>Valor efetivo</th><th>Próximo vencimento</th><th>1ª cobrança</th><th>Cobrança</th><th>Status</th><th>Ações</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.customer_name}</td><td><strong>{r.product_name}</strong><div className="muted">{r.product_code}</div></td><td>{r.plan_name||'Personalizado'}</td><td>{Number(r.effective_price||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</td><td>{r.next_due_date?String(r.next_due_date).slice(0,10):'—'}</td><td><Badge tone={Number(r.first_cycle_prorata_enabled||0)===1?'success':'neutral'}>{Number(r.first_cycle_prorata_enabled||0)===1?'Pró-rata automático':'Integral'}</Badge></td><td>{r.billing_provider||r.default_provider||'Padrão'} / {r.billing_method||r.default_payment_method||'Padrão'}</td><td><Badge tone={r.status==='ACTIVE'||r.status==='GRACE'?'success':r.status==='PENDING_DATA'?'warning':'danger'}>{r.status}</Badge>{r.grace_until&&<div className="muted">liberado até {String(r.grace_until).slice(0,10)}</div>}</td><td><div className="row gap"><button className="secondary compact" onClick={()=>setEditing({id:r.id,billingProvider:r.billing_provider||null,billingMethod:r.billing_method||null,graceDays:Number(r.grace_days??3),autoBlock:Boolean(Number(r.auto_block??1)),firstCycleProrataEnabled:Boolean(Number(r.first_cycle_prorata_enabled||0))})}>Sobrescrever cobrança</button><button className="secondary compact" onClick={()=>void grant(r.id,5)}>+5 dias</button><button className="secondary compact" onClick={()=>void grant(r.id,10)}>+10 dias</button><button className="secondary compact" onClick={()=>void grant(r.id,30)}>+30 dias</button><button className="secondary compact" onClick={()=>void grant(r.id)}>Data personalizada</button>{r.grace_until&&<button className="secondary compact" onClick={()=>void revoke(r.id)}>Revogar liberação</button>}</div></td></tr>)}</tbody></DataTable></div>}</div>
    {editing&&<section className="panel"><div className="commercial-panel-head"><div><h2>Sobrescrever cobrança da assinatura</h2><span className="muted">Deixe provedor e método vazios para herdar a configuração do produto.</span></div><button className="secondary" onClick={()=>setEditing(null)}>Cancelar</button></div><div className="form-grid"><label>Provedor<select value={editing.billingProvider||''} onChange={e=>{const billingProvider=e.target.value||null;setEditing({...editing,billingProvider,billingMethod:billingProvider?(editing.billingMethod||(billingProvider==='MERCADO_PAGO'?'BOLETO':'HYBRID')):null});}}><option value="">Herdar do produto</option><option value="EFI">Efí</option><option value="CORA">Cora</option><option value="MERCADO_PAGO">Mercado Pago</option></select></label><label>Método<select disabled={!editing.billingProvider} value={editing.billingMethod||''} onChange={e=>setEditing({...editing,billingMethod:e.target.value||null})}><option value="">Herdar do produto</option><option value="HYBRID">BolePix / Híbrido</option><option value="BOLETO">Boleto</option><option value="PIX">Pix</option></select></label><label>Tolerância (dias)<input type="number" min={0} max={365} value={editing.graceDays} onChange={e=>setEditing({...editing,graceDays:Number(e.target.value)})}/></label><label className="checkbox-row"><input type="checkbox" checked={editing.autoBlock} onChange={e=>setEditing({...editing,autoBlock:e.target.checked})}/> Bloqueio automático</label><label className="checkbox-row"><input type="checkbox" checked={editing.firstCycleProrataEnabled} onChange={e=>setEditing({...editing,firstCycleProrataEnabled:e.target.checked})}/> Pró-rata automático na primeira cobrança</label></div><button className="primary" disabled={saving} onClick={()=>void save()}>{saving?'Salvando…':'Salvar cobrança'}</button></section>}
  </>;
}
