import {useEffect,useState} from "react";
import {SaasPage} from "./SaasPage";
import {SaasPlans,ContractEditor} from "./SaasPlans";
import {ProposalsPage} from "./ProposalsPage";
import {SaasEmail} from "./SaasEmail";
import {AuditPage} from "./AuditPage";
import {PasswordPage} from "./PasswordPage";
import {ResourceState,useResource,money} from "./CommercialUi";
import "./commercial.css";
const sections:Record<string,string>={overview:"Dashboard SaaS",clients:"Empresas",plans:"Planos",proposals:"Propostas comerciais",contracts:"Assinaturas e recursos",audit:"Auditoria global",email:"Configurações de e-mail",password:"Alterar senha"};
const current=()=>location.hash.replace("#saas/","");
export default function SaasPortal({logout}:{logout:()=>void}){const [page,setPage]=useState(sections[current()]?current():"overview"),[message,setMessage]=useState<{text:string;error:boolean}|null>(null);useEffect(()=>{const change=()=>{setPage(sections[current()]?current():"overview");setMessage(null);};window.addEventListener("hashchange",change);return()=>window.removeEventListener("hashchange",change);},[]);return <div className="commercial-shell"><header className="commercial-topbar"><a href="#saas/overview"><img src="/brand/logo.png" alt="Ponto Certo"/></a><span>Administração SaaS</span><button onClick={logout}>Sair</button></header><nav className="commercial-nav" aria-label="Navegação SaaS">{Object.entries(sections).map(([key,label])=><a key={key} href={`#saas/${key}`} aria-current={page===key?"page":undefined}>{label}</a>)}</nav><main className="commercial-main" id="main-content">{message&&<p role={message.error?"alert":"status"}>{message.text}</p>}{page==="overview"?<Overview/>:page==="clients"?<SaasPage notify={(text,t)=>setMessage({text,error:t==="error"})}/>:page==="plans"?<SaasPlans/>:page==="proposals"?<ProposalsPage/>:page==="contracts"?<Contracts/>:page==="audit"?<AuditPage global/>:page==="email"?<SaasEmail/>:<PasswordPage/>}</main></div>;}
function Overview(){const r=useResource("/saas/dashboard");return <><h1>Dashboard SaaS</h1><p>Clientes, contratos e negociações do Ponto Certo.</p><ResourceState resource={r}><div className="commercial-cards">{[["Clientes",r.data?.counts.clients],["Clientes ativos",r.data?.counts.active],["Mensalidade contratada ativa",money(r.data?.monthly)],["Propostas em aberto",r.data?.proposals.open]].map(([l,v])=><article className="card" key={l}><p>{l}</p><strong className="commercial-price">{v||0}</strong></article>)}</div><div className="commercial-actions"><a className="primary" href="#saas/proposals">Gerenciar propostas</a><a href="#saas/clients">Consultar empresas</a></div></ResourceState></>;}
function Contracts(){const r=useResource("/saas/tenants"),[selected,setSelected]=useState<number|null>(null);return <><h1>Assinaturas e recursos</h1><p>Valores negociados, capacidade e liberações individuais por empresa.</p><ResourceState resource={r}><div className="table-scroll"><table><thead><tr><th>Cliente</th><th>Plano</th><th>Funcionários</th><th>Status</th><th>Contrato</th></tr></thead><tbody>{r.data?.map((t:any)=><tr key={t.id}><td>{t.name}</td><td>{t.plan_name||"Sem plano"}</td><td>{t.employee_count}</td><td>{t.subscription_status||t.status}</td><td><button onClick={()=>setSelected(t.id)}>Configurar contrato</button></td></tr>)}</tbody></table></div></ResourceState>{selected&&<ContractEditor tenantId={selected} onClose={()=>{setSelected(null);void r.reload();}}/>}</>;}
