import {useEffect,useState} from 'react';
import {api} from '../api';
import {PageHeader,Badge,Empty} from '../components/Ui';
import {DataTable} from '../components/DataTable';
import {Modal} from '../components/Modal';
import {MaskedInput} from '../components/MaskedInput';
import {apiMessage} from '../utils';

const empty={legalName:'',tradeName:'',document:'',email:'',phone:'',financialContactName:'',financialContactEmail:'',financialContactPhone:'',zipCode:'',street:'',number:'',complement:'',district:'',city:'',state:'',status:'ACTIVE'};
export function SaasCommercialCustomers(){
  const [rows,setRows]=useState<any[]>([]),[open,setOpen]=useState(false),[form,setForm]=useState<any>(empty),[error,setError]=useState('');
  const load=()=>api.get('/saas/commercial-customers').then(r=>setRows(r.data));useEffect(()=>{void load();},[]);
  async function save(e:React.FormEvent){e.preventDefault();setError('');try{await api.post('/saas/commercial-customers',{...form,personType:String(form.document).replace(/\D/g,'').length===11?'PF':'PJ'});setOpen(false);setForm(empty);await load();}catch(err){setError(apiMessage(err));}}
  return <><PageHeader title="Clientes Comerciais" subtitle="Cadastro único para clientes que podem contratar Ponto Certo, Movyo e outros produtos." action={<button className="primary" onClick={()=>setOpen(true)}>+ Novo cliente comercial</button>}/>
  <div className="panel table-panel">{rows.length===0?<Empty>Nenhum cliente comercial cadastrado.</Empty>:<div className="table-wrap"><DataTable><thead><tr><th>Cliente</th><th>Documento</th><th>Financeiro</th><th>Produtos</th><th>MRR</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.legal_name}</strong><div className="muted">{r.trade_name||r.email||''}</div></td><td>{r.document||'—'}</td><td>{r.financial_contact_email||r.email||'—'}</td><td>{r.subscriptions_count}</td><td>{Number(r.mrr||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</td><td><Badge tone={r.status==='ACTIVE'?'success':'warning'}>{r.status}</Badge></td></tr>)}</tbody></DataTable></div>}</div>
  {open&&<Modal title="Novo cliente comercial" onClose={()=>setOpen(false)} wide><form className="form-grid" onSubmit={save}>{error&&<div className="error span-2">{error}</div>}<label>Razão social / Nome<input required value={form.legalName} onChange={e=>setForm({...form,legalName:e.target.value})}/></label><label>Nome fantasia<input value={form.tradeName} onChange={e=>setForm({...form,tradeName:e.target.value})}/></label><label>CPF/CNPJ<MaskedInput mask="cnpj" value={form.document} onChange={document=>setForm({...form,document})}/></label><label>E-mail<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Responsável financeiro<input value={form.financialContactName} onChange={e=>setForm({...form,financialContactName:e.target.value})}/></label><label>E-mail financeiro<input type="email" value={form.financialContactEmail} onChange={e=>setForm({...form,financialContactEmail:e.target.value})}/></label><label>CEP<input value={form.zipCode} onChange={e=>setForm({...form,zipCode:e.target.value})}/></label><label>Logradouro<input value={form.street} onChange={e=>setForm({...form,street:e.target.value})}/></label><label>Número<input value={form.number} onChange={e=>setForm({...form,number:e.target.value})}/></label><label>Bairro<input value={form.district} onChange={e=>setForm({...form,district:e.target.value})}/></label><label>Cidade<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>UF<input maxLength={2} value={form.state} onChange={e=>setForm({...form,state:e.target.value.toUpperCase()})}/></label><div className="form-actions span-2"><button type="button" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary" type="submit">Salvar</button></div></form></Modal>}</>;
}
