import {useEffect,useState} from "react";
import {SaasPage} from "./SaasPage";
import {SaasPlans,ContractEditor} from "./SaasPlans";
import {ProposalsPage} from "./ProposalsPage";
import {SaasEmail} from "./SaasEmail";
import {SaasGeneral} from "./SaasGeneral";
import {AuditPage} from "./AuditPage";
import {PasswordPage} from "./PasswordPage";
import {ContractsPage} from "./ContractsPage";
import {ResourceState,useResource,money} from "./CommercialUi";
import "./commercial.css";
const sections:Record<string,string>={overview:"Dashboard SaaS",clients:"Clientes / Empresas",plans:"Planos",subscriptions:"Assinaturas e Recursos",proposals:"Propostas Comerciais",contracts:"Contratos",audit:"Auditoria SaaS",settings:"Configurações SaaS",email:"Configuração de e-mail",password:"Alterar senha"};
const current=()=>location.hash.replace("#saas/","");
export default function SaasPortal({logout}:{logout:()=>void}){const [page,setPage]=useState(sections[current()]?current():"overview"),[message,setMessage]=useState<{text:string;error:boolean}|null>(null);useEffect(()=>{const change=()=>{setPage(sections[current()]?current():"overview");setMessage(null);};window.addEventListener("hashchange",change);return()=>window.removeEventListener("hashchange",change);},[]);return <div className="commercial-shell"><header className="commercial-topbar"><a href="#saas/overview"><img src="/brand/logo.png" alt="Ponto Certo"/></a><span>Administração SaaS</span><button onClick={logout}>Sair</button></header><nav className="commercial-nav" aria-label="Navegação SaaS">{Object.entries(sections).map(([key,label])=><a key={key} href={`#saas/${key}`} aria-current={page===key?"page":undefined}>{label}</a>)}</nav><main className="commercial-main" id="main-content">{message&&<p role={message.error?"alert":"status"}>{message.text}</p>}{page==="overview"?<Overview/>:page==="clients"?<SaasPage notify={(text,t)=>setMessage({text,error:t==="error"})}/>:page==="plans"?<SaasPlans/>:page==="proposals"?<ProposalsPage/>:page==="subscriptions"?<Subscriptions/>:page==="contracts"?<ContractsPage/>:page==="audit"?<AuditPage global/>:page==="settings"?<SaasGeneral/>:page==="email"?<SaasEmail/>:<PasswordPage/>}</main></div>;}
function Overview(){const r=useResource("/saas/dashboard");const cards=[
  ["Total de clientes",r.data?.counts.clients],["Clientes ativos",r.data?.counts.active],["Suspensos",r.data?.counts.suspended],["Cancelados",r.data?.counts.canceled],["Em teste",r.data?.counts.trial],
  ["Funcionários ativos",r.data?.counts.employees],["Empresas / filiais",r.data?.counts.companies],["Propostas em aberto",r.data?.proposals.open],["Propostas aprovadas",r.data?.proposals.approved],["Propostas expiradas",r.data?.proposals.expired],["Propostas convertidas",r.data?.proposals.converted],
  ["Contratos ativos",r.data?.contracts.active],["Aguardando assinatura",r.data?.contracts.awaiting_signature],["Contratos cancelados",r.data?.contracts.canceled],["MRR",money(r.data?.monthly)],["Implantação contratada",money(r.data?.contracts.implementation_value)]
];return <><h1>Dashboard SaaS</h1><p>Visão comercial e administrativa do Ponto Certo.</p><ResourceState resource={r}><div className="commercial-cards">{cards.map(([l,v])=><article className="card" key={String(l)}><p>{l}</p><strong className="commercial-price">{v??0}</strong></article>)}</div><section className="card"><h2>Distribuição por plano</h2>{r.data?.plans?.length?<div className="table-scroll"><table><thead><tr><th>Plano</th><th>Clientes</th></tr></thead><tbody>{r.data.plans.map((p:any)=><tr key={p.id}><td>{p.name}</td><td>{p.clients}</td></tr>)}</tbody></table></div>:<p>Nenhum cliente contratado.</p>}</section><div className="commercial-actions"><a className="primary" href="#saas/proposals">Gerenciar propostas</a><a href="#saas/contracts">Contratos</a><a href="#saas/clients">Consultar empresas</a></div></ResourceState></>;}
function Subscriptions(){const r=useResource("/saas/tenants"),[selected,setSelected]=useState<number|null>(null);return <><h1>Assinaturas e recursos</h1><p>Valores negociados, capacidade e liberações individuais por empresa.</p><ResourceState resource={r}><div className="table-scroll"><table><thead><tr><th>Cliente</th><th>Plano</th><th>Funcionários</th><th>Status</th><th>Contrato</th></tr></thead><tbody>{r.data?.map((t:any)=><tr key={t.id}><td>{t.name}</td><td>{t.plan_name||"Sem plano"}</td><td>{t.employee_count}</td><td>{t.subscription_status||t.status}</td><td><button onClick={()=>setSelected(t.id)}>Configurar contrato</button></td></tr>)}</tbody></table></div></ResourceState>{selected&&<ContractEditor tenantId={selected} onClose={()=>{setSelected(null);void r.reload();}}/>}</>;}
