import {useEffect,useState} from "react";
import {api} from "../api";
import {apiMessage,brDate} from "../utils";

export function SaasFinanceInter(){
  const [data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
  async function load(){setError("");try{setData((await api.get("/saas/finance/inter/status")).data);}catch(e){setError(apiMessage(e));}}
  useEffect(()=>{void load();},[]);
  async function action(type:"test"|"webhook"){setBusy(true);setError("");setMessage("");try{if(type==="test")await api.post("/saas/finance/inter/test");else await api.put("/saas/finance/inter/webhook",{});setMessage(type==="test"?"Conexão com o Banco Inter confirmada.":"Webhook de cobrança configurado no Banco Inter.");await load();}catch(e){setError(apiMessage(e));}finally{setBusy(false);}}
  return <><div className="commercial-heading"><div><span className="commercial-kicker">Financeiro · Integração</span><h1>Banco Inter</h1><p>Saúde da API Cobrança (Boleto com Pix), certificado e webhook. Segredos nunca são exibidos nesta tela.</p></div></div>{error&&<div className="error-card">{error}</div>}{message&&<div className="commercial-toast success">{message}</div>}{!data?<div className="panel">Carregando integração…</div>:<div className="commercial-grid-2"><section className="panel finance-inter-card"><h2>Credenciais e certificado</h2><dl><div><dt>Integração</dt><dd>{data.enabled?"Ativada":"Desativada"}</dd></div><div><dt>Ambiente</dt><dd>{data.environment}</dd></div><div><dt>Client ID</dt><dd>{data.clientIdConfigured?"Configurado":"Ausente"}</dd></div><div><dt>Client Secret</dt><dd>{data.clientSecretConfigured?"Configurado":"Ausente"}</dd></div><div><dt>Certificado</dt><dd>{data.certExists?data.certificateFilename||"Encontrado":"Arquivo não encontrado"}</dd></div><div><dt>Chave privada</dt><dd>{data.keyExists?"Encontrada":"Arquivo não encontrado"}</dd></div><div><dt>Validade do certificado</dt><dd>{data.certificateValidTo?brDate(data.certificateValidTo):"—"}</dd></div></dl><button className="primary" disabled={busy||!data.enabled} onClick={()=>action("test")}>{busy?"Testando…":"Testar conexão"}</button></section><section className="panel finance-inter-card"><h2>Webhook de pagamentos</h2><p>O webhook recebe o aviso do Inter, mas a baixa só é confirmada depois que o Ponto Certo consulta a cobrança no banco.</p><dl><div><dt>URL configurada no servidor</dt><dd className="finance-break">{data.defaultWebhookUrl||"INTER_WEBHOOK_URL não configurada"}</dd></div><div><dt>Retorno do Inter</dt><dd className="finance-break">{data.configuredWebhook?JSON.stringify(data.configuredWebhook):"Ainda não consultado/configurado"}</dd></div></dl><button disabled={busy||!data.enabled||!data.defaultWebhookUrl} onClick={()=>action("webhook")}>Configurar webhook no Inter</button></section></div>}</>;
}
