import {useEffect,useMemo,useState} from "react";
import {api} from "../api";
import {Icon} from "../components/Icon";

type Mapping={
  id:number;movyo_restaurant_id:string;migration_status:string;commercial_customer_id?:number|null;product_subscription_id?:number|null;
  customer_name?:string|null;customer_document?:string|null;customer_financial_email?:string|null;customer_zip_code?:string|null;customer_street?:string|null;customer_number?:string|null;customer_district?:string|null;customer_city?:string|null;customer_state?:string|null;
  plan_code?:string|null;plan_name?:string|null;monthly_price?:number|null;discount_percent?:number|null;current_period_end?:string|null;next_due_date?:string|null;last_error?:string|null;last_sync_at?:string|null;remote?:any;
};
type Status={bridgeEnabled:boolean;bridgeConfigured:boolean;counts:Record<string,number>;total:number;lastSyncAt?:string|null};
type Rollout={movyoPilotApproved:boolean;bulkCutoverEnabled:boolean};
const FILTERS=["ALL","LEGACY_MOVYO","PENDING_DATA","CONFLICT","READY_TO_MIGRATE","PONTO_CERTO","ERROR"] as const;
const labels:Record<string,string>={ALL:"Todos",LEGACY_MOVYO:"Legado Movyo",PENDING_DATA:"Pendência cadastral",CONFLICT:"Conflito",READY_TO_MIGRATE:"Pronto para migrar",PONTO_CERTO:"Gerido pelo Ponto Certo",ERROR:"Erro"};
const statusClass=(v:string)=>v==="PONTO_CERTO"||v==="READY_TO_MIGRATE"?"active":v==="ERROR"||v==="CONFLICT"?"canceled":v==="PENDING_DATA"?"past_due":"trial";
const doc=(v:any)=>String(v||"").replace(/\D/g,"");
const money=(v:any)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const when=(v:any)=>v?new Date(v).toLocaleString("pt-BR"):"—";

export function SaasMovyoIntegration(){
  const [status,setStatus]=useState<Status|null>(null),[rows,setRows]=useState<Mapping[]>([]),[filter,setFilter]=useState<string>("ALL"),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null),[message,setMessage]=useState<{text:string;error?:boolean}|null>(null),[selected,setSelected]=useState<Mapping|null>(null),[commercialCustomers,setCommercialCustomers]=useState<any[]>([]),[linkCustomerId,setLinkCustomerId]=useState("");
  const [checked,setChecked]=useState<Set<string>>(new Set());
  const [rollout,setRollout]=useState<Rollout>({movyoPilotApproved:false,bulkCutoverEnabled:false}),[rolloutDraft,setRolloutDraft]=useState<Rollout>({movyoPilotApproved:false,bulkCutoverEnabled:false});
  const load=async()=>{setLoading(true);try{const params=new URLSearchParams();if(filter!=="ALL")params.set("status",filter);if(q.trim())params.set("q",q.trim());const [s,c,cc,ro]=await Promise.all([api.get("/saas/integrations/movyo/status"),api.get(`/saas/integrations/movyo/customers?${params}`),api.get("/saas/commercial-customers"),api.get("/saas/integrations/movyo/rollout")]);setStatus(s.data);setRows(c.data||[]);setCommercialCustomers(cc.data||[]);setRollout(ro.data);setRolloutDraft(ro.data);}catch(e:any){setMessage({text:e.response?.data?.message||e.response?.data?.mensagem||"Não foi possível carregar a integração Movyo.",error:true});}finally{setLoading(false);}};
  useEffect(()=>{void load();},[filter]);
  const readySelected=useMemo(()=>rows.filter(r=>checked.has(r.movyo_restaurant_id)&&r.migration_status==="READY_TO_MIGRATE"),[rows,checked]);
  const act=async(key:string,fn:()=>Promise<any>,success:string)=>{setBusy(key);setMessage(null);try{await fn();setMessage({text:success});await load();}catch(e:any){setMessage({text:e.response?.data?.mensagem||e.response?.data?.message||e.message||"Falha na operação Movyo.",error:true});}finally{setBusy(null);}};
  const sync=()=>act("sync",()=>api.post("/saas/integrations/movyo/sync"),"Clientes Movyo sincronizados. Nenhuma cobrança foi criada.");
  const importOne=(r:Mapping)=>act(`import:${r.movyo_restaurant_id}`,()=>api.post(`/saas/integrations/movyo/customers/${encodeURIComponent(r.movyo_restaurant_id)}/import`),"Cliente Movyo importado para a Central Comercial.");
  const reconcile=(r:Mapping)=>act(`reconcile:${r.movyo_restaurant_id}`,()=>api.post(`/saas/integrations/movyo/customers/${encodeURIComponent(r.movyo_restaurant_id)}/reconcile`),"Estado Movyo reconciliado.");
  const cutover=(r:Mapping)=>{if(!confirm(`Ativar a gestão financeira pelo Ponto Certo para ${r.remote?.nome||r.customer_name||r.movyo_restaurant_id}?\n\nA Movyo deixará de gerar novas mensalidades Pix para este cliente.`))return;void act(`cutover:${r.movyo_restaurant_id}`,()=>api.post(`/saas/integrations/movyo/customers/${encodeURIComponent(r.movyo_restaurant_id)}/cutover`,{confirm:true}),"Gestão financeira transferida para o Ponto Certo.");};
  const rollback=(r:Mapping)=>{if(!confirm("Executar rollback piloto e devolver a mensalidade para o billing legado da Movyo?"))return;void act(`rollback:${r.movyo_restaurant_id}`,()=>api.post(`/saas/integrations/movyo/customers/${encodeURIComponent(r.movyo_restaurant_id)}/rollback`,{confirm:true}),"Rollback piloto executado.");};
  const resolve=()=>{if(!selected||!linkCustomerId)return;void act(`resolve:${selected.movyo_restaurant_id}`,()=>api.put(`/saas/integrations/movyo/customers/${encodeURIComponent(selected.movyo_restaurant_id)}/resolve`,{commercialCustomerId:Number(linkCustomerId)}),"Cadastro Movyo vinculado ao Cliente Comercial selecionado.");};
  const toggle=(r:Mapping)=>{if(r.migration_status!=="READY_TO_MIGRATE")return;setChecked(prev=>{const next=new Set(prev);next.has(r.movyo_restaurant_id)?next.delete(r.movyo_restaurant_id):next.add(r.movyo_restaurant_id);return next;});};
  const saveRollout=()=>act("rollout",()=>api.put("/saas/integrations/movyo/rollout",rolloutDraft),"Controles de rollout Movyo atualizados.");
  const bulkCutover=()=>{if(!rollout.movyoPilotApproved||!rollout.bulkCutoverEnabled||readySelected.length===0)return;if(!confirm(`Migrar ${readySelected.length} cliente(s) Movyo em lote? Cada cliente ainda será validado individualmente.`))return;void act("bulk",()=>api.post("/saas/integrations/movyo/bulk-cutover",{externalIds:readySelected.map(r=>r.movyo_restaurant_id)}),"Migração em lote processada. Revise eventuais falhas na lista.");};
  return <>
    <div className="commercial-heading"><div><span className="commercial-kicker">Integrações de produto</span><h1>Integração Movyo</h1><p>Importe restaurantes existentes, valide cadastro e migre a assinatura SaaS para cobrança centralizada no Ponto Certo.</p></div><div className="commercial-heading-actions"><button className="primary" disabled={busy==="sync"} onClick={sync}><Icon name="refresh" size={16}/>{busy==="sync"?"Sincronizando...":"Sincronizar Movyo"}</button></div></div>
    {message&&<div className={`commercial-toast ${message.error?"error":"success"}`}>{message.text}</div>}
    <section className="movyo-status-grid">
      <article><small>Bridge</small><strong>{status?.bridgeEnabled&&status?.bridgeConfigured?"Configurado":"Pendente"}</strong><span>{status?.bridgeEnabled?"Integração habilitada":"Integração desabilitada"}</span></article>
      <article><small>Encontrados</small><strong>{status?.total||0}</strong><span>restaurantes sincronizados</span></article>
      <article><small>Prontos</small><strong>{status?.counts?.READY_TO_MIGRATE||0}</strong><span>aptos ao cutover</span></article>
      <article><small>Pendências / conflitos</small><strong>{(status?.counts?.PENDING_DATA||0)+(status?.counts?.CONFLICT||0)}</strong><span>requerem revisão</span></article>
      <article><small>Geridos pelo Ponto Certo</small><strong>{status?.counts?.PONTO_CERTO||0}</strong><span>billing centralizado</span></article>
    </section>
    <section className="commercial-panel movyo-rollout-panel"><div className="commercial-panel-head"><div><span className="commercial-kicker">Proteção de produção</span><h2>Controles de rollout</h2><small>Por padrão, a migração em lote permanece bloqueada até validação explícita do piloto.</small></div><button className="secondary compact" disabled={busy==="rollout"} onClick={saveRollout}>Salvar controles</button></div><div className="movyo-rollout-controls"><label><input type="checkbox" checked={rolloutDraft.movyoPilotApproved} onChange={e=>setRolloutDraft(v=>({movyoPilotApproved:e.target.checked,bulkCutoverEnabled:e.target.checked?v.bulkCutoverEnabled:false}))}/> Piloto Movyo validado em produção</label><label><input type="checkbox" disabled={!rolloutDraft.movyoPilotApproved} checked={rolloutDraft.bulkCutoverEnabled} onChange={e=>setRolloutDraft(v=>({...v,bulkCutoverEnabled:e.target.checked}))}/> Liberar migração em lote</label><span className={`commercial-status status-${rollout.bulkCutoverEnabled?"active":"trial"}`}>{rollout.bulkCutoverEnabled?"LOTE LIBERADO":"LOTE BLOQUEADO"}</span></div></section>
    <section className="commercial-panel movyo-panel">
      <div className="commercial-panel-head"><div><span className="commercial-kicker">Migração controlada</span><h2>Clientes Movyo</h2><small>Última sincronização: {when(status?.lastSyncAt)}</small></div><div className="movyo-search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Nome, CNPJ..." onKeyDown={e=>{if(e.key==="Enter")void load();}}/><button className="secondary compact" onClick={()=>void load()}>Buscar</button></div></div>
      <div className="movyo-filters">{FILTERS.map(f=><button key={f} className={filter===f?"active":""} onClick={()=>setFilter(f)}>{labels[f]} {f!=="ALL"&&status?.counts?.[f]!=null?<b>{status.counts[f]}</b>:null}</button>)}</div>
      {readySelected.length>0&&<div className="movyo-bulk"><strong>{readySelected.length} cliente(s) pronto(s) selecionado(s)</strong><button disabled={!rollout.movyoPilotApproved||!rollout.bulkCutoverEnabled||busy==="bulk"} title={!rollout.bulkCutoverEnabled?"Liberado somente após o piloto real ser aprovado":undefined} onClick={bulkCutover}>{busy==="bulk"?"Migrando...":rollout.bulkCutoverEnabled?"Executar migração em lote":"Migração em lote bloqueada"}</button></div>}
      {loading?<div className="commercial-empty compact-empty"><strong>Carregando clientes Movyo...</strong></div>:rows.length===0?<div className="commercial-empty"><strong>Nenhum cliente neste filtro</strong><p>Use Sincronizar Movyo para atualizar o diretório.</p></div>:<div className="table-scroll"><table><thead><tr><th></th><th>Restaurante</th><th>Plano / valor</th><th>Vencimento atual</th><th>Status</th><th>Ações</th></tr></thead><tbody>{rows.map(r=><tr key={r.movyo_restaurant_id}><td><input aria-label="Selecionar para migração" type="checkbox" disabled={r.migration_status!=="READY_TO_MIGRATE"} checked={checked.has(r.movyo_restaurant_id)} onChange={()=>toggle(r)}/></td><td><strong>{r.remote?.nome||r.customer_name||`Movyo #${r.movyo_restaurant_id}`}</strong><small>{r.remote?.cnpj||r.customer_document||"CNPJ não informado"}</small><button className="movyo-detail-link" onClick={()=>{setSelected(r);setLinkCustomerId(r.commercial_customer_id?String(r.commercial_customer_id):"");}}>Comparar dados</button></td><td><strong>{r.plan_name||r.remote?.plano||"—"}</strong><small>{r.monthly_price!=null?money(Number(r.monthly_price)*(1-Number(r.discount_percent||0)/100)):r.remote?.valorMensalidadeCustomizado?money(r.remote.valorMensalidadeCustomizado):"valor a validar"}</small></td><td>{r.current_period_end?String(r.current_period_end).slice(0,10).split("-").reverse().join("/"):r.remote?.dataFimPlano?String(r.remote.dataFimPlano).slice(0,10).split("-").reverse().join("/"):"—"}</td><td><span className={`commercial-status status-${statusClass(r.migration_status)}`}>{labels[r.migration_status]||r.migration_status}</span>{r.last_error&&<small className="movyo-error">{r.last_error}</small>}</td><td><div className="movyo-actions">{!r.product_subscription_id&&r.migration_status!=="CONFLICT"&&<button disabled={!!busy} onClick={()=>void importOne(r)}>Importar</button>}{["PENDING_DATA","CONFLICT"].includes(r.migration_status)&&<button onClick={()=>{setSelected(r);setLinkCustomerId(r.commercial_customer_id?String(r.commercial_customer_id):"");}}>Regularizar cadastro</button>}{r.migration_status==="READY_TO_MIGRATE"&&<button className="primary" onClick={()=>cutover(r)}>Ativar gestão pelo Ponto Certo</button>}{["PONTO_CERTO","ERROR","CUTOVER_PENDING"].includes(r.migration_status)&&<button onClick={()=>void reconcile(r)}>Reconciliar</button>}{r.migration_status==="PONTO_CERTO"&&<button className="danger-link" onClick={()=>rollback(r)}>Rollback piloto</button>}</div></td></tr>)}</tbody></table></div>}
    </section>
    {selected&&<div className="commercial-modal-backdrop" role="presentation" onMouseDown={()=>setSelected(null)}><section className="commercial-modal movyo-detail" role="dialog" aria-modal="true" aria-label="Comparar cadastro Movyo" onMouseDown={e=>e.stopPropagation()}><div className="commercial-modal-head"><div><span className="commercial-kicker">Movyo × Ponto Certo</span><h2>{selected.remote?.nome||selected.customer_name||selected.movyo_restaurant_id}</h2></div><button className="commercial-icon-btn" onClick={()=>setSelected(null)}>×</button></div><div className="movyo-compare"><Compare label="CNPJ" remote={selected.remote?.cnpj} local={selected.customer_document}/><Compare label="E-mail cobrança" remote={selected.remote?.emailCobranca||selected.remote?.email} local={selected.customer_financial_email}/><Compare label="CEP" remote={selected.remote?.enderecoCep} local={selected.customer_zip_code}/><Compare label="Endereço" remote={[selected.remote?.enderecoRua,selected.remote?.enderecoNumero,selected.remote?.enderecoBairro,selected.remote?.enderecoCidade,selected.remote?.enderecoEstado].filter(Boolean).join(", ")} local={[selected.customer_street,selected.customer_number,selected.customer_district,selected.customer_city,selected.customer_state].filter(Boolean).join(", ")}/><Compare label="Plano" remote={selected.remote?.plano} local={selected.plan_code}/></div><div className="movyo-link-customer"><label>Vincular/regularizar com Cliente Comercial<select value={linkCustomerId} onChange={e=>setLinkCustomerId(e.target.value)}><option value="">Selecione...</option>{commercialCustomers.map(c=><option key={c.id} value={c.id}>{c.legal_name} · {doc(c.document)||"sem documento"}</option>)}</select></label><button className="primary" disabled={!linkCustomerId||!!busy} onClick={resolve}>Vincular e validar</button><a className="secondary" href="#saas/commercial-customers">Abrir Clientes Comerciais</a></div></section></div>}
  </>;
}
function Compare({label,remote,local}:{label:string;remote:any;local:any}){const same=String(remote||"").replace(/\D/g," ").trim()===String(local||"").replace(/\D/g," ").trim();return <div className="movyo-compare-row"><strong>{label}</strong><div><small>Movyo</small><span>{remote||"—"}</span></div><div><small>Ponto Certo</small><span>{local||"—"}</span></div><b className={same?"match":"diff"}>{same?"OK":"Revisar"}</b></div>}
