import { useEffect, useState } from "react";
import { api } from "../api";
import { Company, Schedule } from "../types";
import { Modal } from "../components/Modal";
import { Badge, Empty, PageHeader } from "../components/Ui";
import { apiMessage, minutesToHHMM } from "../utils";

const names=["Domingo","Segunda","Terça","Quarta","Quinta","Sexta","Sábado"];
const defaultDays=names.map((_,weekday)=>({weekday,isDayOff:weekday===0||weekday===6,entry1:weekday===0||weekday===6?"":"08:00",exit1:weekday===0||weekday===6?"":"12:00",entry2:weekday===0||weekday===6?"":"13:00",exit2:weekday===0||weekday===6?"":"17:00"}));
const blank={companyId:0,name:"",toleranceLateMinutes:10,toleranceOvertimeMinutes:10,active:true,days:defaultDays};

export function SchedulesPage({notify}:{notify:(m:string,t?:"ok"|"error")=>void}){
 const [items,setItems]=useState<Schedule[]>([]),[companies,setCompanies]=useState<Company[]>([]),[editing,setEditing]=useState<Schedule|null|undefined>(undefined),[form,setForm]=useState<any>(blank);
 const load=()=>Promise.all([api.get("/schedules"),api.get("/companies")]).then(([a,b])=>{setItems(a.data);setCompanies(b.data)}); useEffect(()=>{load()},[]);
 async function open(item?:Schedule){if(!item){setEditing(null);setForm({...blank,companyId:companies.find(c=>c.active)?.id||0,days:defaultDays.map(d=>({...d}))});return}const {data}=await api.get(`/schedules/${item.id}`);setEditing(item);setForm({companyId:data.company_id,name:data.name,toleranceLateMinutes:data.tolerance_late_minutes,toleranceOvertimeMinutes:data.tolerance_overtime_minutes,active:Boolean(data.active),days:names.map((_,weekday)=>{const d=data.days.find((x:any)=>Number(x.weekday)===weekday);return{weekday,isDayOff:Boolean(d?.is_day_off),entry1:d?.entry_1?.slice(0,5)||"",exit1:d?.exit_1?.slice(0,5)||"",entry2:d?.entry_2?.slice(0,5)||"",exit2:d?.exit_2?.slice(0,5)||""}})});}
 function updateDay(idx:number,key:string,value:any){setForm({...form,days:form.days.map((d:any,i:number)=>i===idx?{...d,[key]:value}:d)})}
 async function save(e:React.FormEvent){e.preventDefault();try{const payload={...form,companyId:Number(form.companyId)};editing?await api.put(`/schedules/${editing.id}`,payload):await api.post("/schedules",payload);notify("Jornada salva com sucesso.");setEditing(undefined);load()}catch(err){notify(apiMessage(err),"error")}}
 return <><PageHeader title="Escalas e jornadas" subtitle="Defina horários, folgas e tolerâncias" action={<button className="primary" onClick={()=>open()}>+ Nova jornada</button>}/><div className="panel">{items.length===0?<Empty>Nenhuma jornada cadastrada.</Empty>:<div className="cards-list">{items.map(s=><div className="schedule-card" key={s.id}><div><h3>{s.name}</h3><p>{s.company_name}</p></div><div className="schedule-meta"><span><b>{minutesToHHMM(s.weekly_minutes)}</b> semanais</span><span><b>{s.employee_count}</b> funcionários</span><Badge tone={s.active?"success":"neutral"}>{s.active?"Ativa":"Inativa"}</Badge><button className="ghost" onClick={()=>open(s)}>Editar</button></div></div>)}</div>}</div>
 {editing!==undefined&&<Modal title={editing?"Editar jornada":"Nova jornada"} onClose={()=>setEditing(undefined)} wide><form onSubmit={save} className="form-grid"><label>Empresa<select required value={form.companyId} onChange={e=>setForm({...form,companyId:Number(e.target.value)})}><option value={0}>Selecione</option>{companies.filter(c=>c.active).map(c=><option key={c.id} value={c.id}>{c.trade_name||c.legal_name}</option>)}</select></label><label>Nome da jornada<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ex.: Administrativo 08h às 17h"/></label><label>Tolerância atraso (min)<input type="number" min={0} value={form.toleranceLateMinutes} onChange={e=>setForm({...form,toleranceLateMinutes:Number(e.target.value)})}/></label><label>Tolerância extra (min)<input type="number" min={0} value={form.toleranceOvertimeMinutes} onChange={e=>setForm({...form,toleranceOvertimeMinutes:Number(e.target.value)})}/></label><div className="section-label span-2">Horários da semana</div><div className="schedule-editor span-2">{form.days.map((d:any,i:number)=><div className="schedule-day" key={d.weekday}><strong>{names[d.weekday]}</strong><label className="mini-check"><input type="checkbox" checked={d.isDayOff} onChange={e=>updateDay(i,"isDayOff",e.target.checked)}/> Folga</label><input type="time" disabled={d.isDayOff} value={d.entry1} onChange={e=>updateDay(i,"entry1",e.target.value)}/><input type="time" disabled={d.isDayOff} value={d.exit1} onChange={e=>updateDay(i,"exit1",e.target.value)}/><input type="time" disabled={d.isDayOff} value={d.entry2} onChange={e=>updateDay(i,"entry2",e.target.value)}/><input type="time" disabled={d.isDayOff} value={d.exit2} onChange={e=>updateDay(i,"exit2",e.target.value)}/></div>)}</div><label className="checkbox-row span-2"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Jornada ativa</label><div className="form-actions span-2"><button type="button" className="ghost" onClick={()=>setEditing(undefined)}>Cancelar</button><button className="primary">Salvar jornada</button></div></form></Modal>}</>;
}
