import { useEffect, useState } from "react";
import { api } from "../api";
import { Company } from "../types";
import { Empty, PageHeader } from "../components/Ui";
import { apiMessage, brDate, localIsoDate } from "../utils";

export function SettingsPage({notify}:{notify:(m:string,t?:"ok"|"error")=>void}){
 const [settings,setSettings]=useState<any>(null),[companies,setCompanies]=useState<Company[]>([]),[holidays,setHolidays]=useState<any[]>([]),[holiday,setHoliday]=useState<any>({companyId:null,holidayDate:localIsoDate(),name:"",scope:"COMPANY"});
 const load=()=>Promise.all([api.get("/settings"),api.get("/companies"),api.get("/holidays")]).then(([a,b,c])=>{setSettings(a.data);setCompanies(b.data);setHolidays(c.data)});useEffect(()=>{load()},[]);
 async function saveSettings(e:React.FormEvent){e.preventDefault();try{await api.put("/settings",{name:settings.name,reportTitle:settings.report_title||"Relatório de Pontos",reportFooter:settings.report_footer||"",timezone:settings.timezone||"America/Sao_Paulo"});notify("Configurações salvas.");load()}catch(err){notify(apiMessage(err),"error")}}
 async function addHoliday(e:React.FormEvent){e.preventDefault();try{await api.post("/holidays",{...holiday,companyId:holiday.companyId?Number(holiday.companyId):null});notify("Feriado cadastrado.");setHoliday({...holiday,name:""});load()}catch(err){notify(apiMessage(err),"error")}}
 async function del(id:number){if(!confirm("Excluir feriado?"))return;await api.delete(`/holidays/${id}`);load()}
 if(!settings)return <><PageHeader title="Configurações"/><div className="panel">Carregando...</div></>;
 return <><PageHeader title="Configurações" subtitle="Identidade do tenant, relatório e feriados"/><div className="settings-grid"><form className="panel form-grid" onSubmit={saveSettings}><div className="section-label span-2">Tenant e relatório</div><label className="span-2">Nome do tenant<input value={settings.name||""} onChange={e=>setSettings({...settings,name:e.target.value})}/></label><label className="span-2">Título do relatório<input value={settings.report_title||""} onChange={e=>setSettings({...settings,report_title:e.target.value})}/></label><label className="span-2">Rodapé do relatório<input value={settings.report_footer||""} onChange={e=>setSettings({...settings,report_footer:e.target.value})}/></label><label className="span-2">Timezone<input value={settings.timezone||"America/Sao_Paulo"} onChange={e=>setSettings({...settings,timezone:e.target.value})}/></label><div className="form-actions span-2"><button className="primary">Salvar configurações</button></div></form><div className="panel"><div className="section-label">Feriados</div><form className="holiday-form" onSubmit={addHoliday}><select value={holiday.companyId||""} onChange={e=>setHoliday({...holiday,companyId:e.target.value||null})}><option value="">Todas as empresas</option>{companies.map(c=><option key={c.id} value={c.id}>{c.trade_name||c.legal_name}</option>)}</select><input type="date" value={holiday.holidayDate} onChange={e=>setHoliday({...holiday,holidayDate:e.target.value})}/><input placeholder="Nome do feriado" required value={holiday.name} onChange={e=>setHoliday({...holiday,name:e.target.value})}/><select value={holiday.scope} onChange={e=>setHoliday({...holiday,scope:e.target.value})}><option value="NATIONAL">Nacional</option><option value="STATE">Estadual</option><option value="MUNICIPAL">Municipal</option><option value="COMPANY">Empresa</option></select><button className="secondary">Adicionar</button></form><div className="holiday-list">{holidays.length===0?<Empty>Nenhum feriado cadastrado.</Empty>:holidays.slice(0,20).map(h=><div className="holiday-row" key={h.id}><div><strong>{h.name}</strong><span>{brDate(h.holiday_date)} · {h.company_name||"Todas as empresas"}</span></div><button className="danger-link" onClick={()=>del(h.id)}>Excluir</button></div>)}</div></div></div></>;
}
