CREATE TABLE IF NOT EXISTS system_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  company_id BIGINT UNSIGNED NOT NULL,
  level ENUM('INFO','WARNING','ERROR') NOT NULL DEFAULT 'INFO',
  module ENUM('WHATSAPP','POINT','OFFLINE','SYNC','API','SYSTEM') NOT NULL DEFAULT 'SYSTEM',
  event_type VARCHAR(80) NOT NULL,
  message VARCHAR(500) NOT NULL,
  details_json JSON NULL,
  employee_id BIGINT UNSIGNED NULL,
  recipient VARCHAR(20) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_system_logs_company_date (tenant_id, company_id, created_at),
  KEY idx_system_logs_module_date (tenant_id, company_id, module, created_at),
  KEY idx_system_logs_level_date (tenant_id, company_id, level, created_at),
  KEY idx_system_logs_event_date (tenant_id, company_id, event_type, created_at),
  CONSTRAINT fk_system_logs_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_system_logs_company FOREIGN KEY (company_id) REFERENCES companies(id),
  CONSTRAINT fk_system_logs_employee FOREIGN KEY (employee_id) REFERENCES employees(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
