CREATE TABLE IF NOT EXISTS commercial_email_deliveries (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  entity_type VARCHAR(20) NOT NULL,
  entity_id BIGINT UNSIGNED NOT NULL,
  document_id BIGINT UNSIGNED NOT NULL,
  revision INT UNSIGNED NOT NULL,
  recipient_email VARCHAR(190) NOT NULL,
  subject VARCHAR(255) NOT NULL,
  message_text TEXT NOT NULL,
  smtp_message_id VARCHAR(255) NULL,
  tracking_token_hash CHAR(64) NOT NULL,
  read_receipt_requested TINYINT(1) NOT NULL DEFAULT 1,
  sent_by BIGINT UNSIGNED NOT NULL,
  sent_at DATETIME NULL,
  first_opened_at DATETIME NULL,
  last_opened_at DATETIME NULL,
  open_count INT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL,
  UNIQUE KEY uq_commercial_email_tracking(tracking_token_hash),
  KEY idx_commercial_email_entity(entity_type,entity_id,sent_at),
  KEY idx_commercial_email_document(document_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
